/* Collapse.vapi generated by valac 0.36.6, do not modify. */

using GLib;

namespace JSDOC {
	public class Collapse : TokenStream {
		public Collapse (Gee.ArrayList<Token> tokens, Packer pk, string filename);
	}
}
