/* DocBuilder.vapi generated by valac 0.36.6, do not modify. */

using GLib;

namespace JSDOC {
	public class DocBuilder : Object {
		public string VERSION;
		public Symbol getSymbol (string name);
		public DocBuilder (Packer p);
	}
}
