/* Identifier.vapi generated by valac 0.36.6, do not modify. */

using GLib;

namespace JSDOC {
	public class Identifier : Object {
		public string name;
		public int refcount;
		public string mungedValue;
		public Scope scope;
		public bool toMunge;
		public Identifier (string name, Scope scope);
	}
}
