/* PrettyPrint.vapi generated by valac 0.36.6, do not modify. */

using GLib;

namespace JSDOC {
	internal class PrettyPrint : Object {
		public static string toPretty (string str);
		public PrettyPrint ();
	}
}
