/* ScopeParser.vapi generated by valac 0.36.6, do not modify. */

using GLib;

namespace JSDOC {
	public class ScopeParser : Object {
		public ScopeParser (TokenStream ts, Packer packer, string filename);
		public void buildSymbolTree ();
		public void mungeSymboltree ();
		public void printWarnings ();
	}
	public enum ScopeParserMode {
		BUILDING_SYMBOL_TREE,
		PASS2_SYMBOL_TREE
	}
}
