/* DocComment.c generated by valac 0.36.6, the Vala compiler
 * generated from DocComment.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define JSDOC_TYPE_DOC_COMMENT (jsdoc_doc_comment_get_type ())
#define JSDOC_DOC_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_DOC_COMMENT, JSDOCDocComment))
#define JSDOC_DOC_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_DOC_COMMENT, JSDOCDocCommentClass))
#define JSDOC_IS_DOC_COMMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_DOC_COMMENT))
#define JSDOC_IS_DOC_COMMENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_DOC_COMMENT))
#define JSDOC_DOC_COMMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_DOC_COMMENT, JSDOCDocCommentClass))

typedef struct _JSDOCDocComment JSDOCDocComment;
typedef struct _JSDOCDocCommentClass JSDOCDocCommentClass;
typedef struct _JSDOCDocCommentPrivate JSDOCDocCommentPrivate;

#define JSDOC_TYPE_DOC_TAG (jsdoc_doc_tag_get_type ())
#define JSDOC_DOC_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_DOC_TAG, JSDOCDocTag))
#define JSDOC_DOC_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_DOC_TAG, JSDOCDocTagClass))
#define JSDOC_IS_DOC_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_DOC_TAG))
#define JSDOC_IS_DOC_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_DOC_TAG))
#define JSDOC_DOC_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_DOC_TAG, JSDOCDocTagClass))

typedef struct _JSDOCDocTag JSDOCDocTag;
typedef struct _JSDOCDocTagClass JSDOCDocTagClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))

#define JSDOC_TYPE_DOC_TAG_TITLE (jsdoc_doc_tag_title_get_type ())
typedef struct _JSDOCDocTagPrivate JSDOCDocTagPrivate;

struct _JSDOCDocComment {
	GObject parent_instance;
	JSDOCDocCommentPrivate * priv;
	gboolean isUserComment;
	gboolean hasTags;
	gchar* src;
	GeeArrayList* tags;
};

struct _JSDOCDocCommentClass {
	GObjectClass parent_class;
};

typedef enum  {
	JSDOC_DOC_TAG_TITLE_NO_VALUE,
	JSDOC_DOC_TAG_TITLE_PARAM,
	JSDOC_DOC_TAG_TITLE_PROPERTY,
	JSDOC_DOC_TAG_TITLE_CFG,
	JSDOC_DOC_TAG_TITLE_EXAMPLE,
	JSDOC_DOC_TAG_TITLE_SINGLETON,
	JSDOC_DOC_TAG_TITLE_AUTHOR,
	JSDOC_DOC_TAG_TITLE_METHOD,
	JSDOC_DOC_TAG_TITLE_DESC,
	JSDOC_DOC_TAG_TITLE_OVERVIEW,
	JSDOC_DOC_TAG_TITLE_SINCE,
	JSDOC_DOC_TAG_TITLE_CONSTANT,
	JSDOC_DOC_TAG_TITLE_VERSION,
	JSDOC_DOC_TAG_TITLE_DEPRECATED,
	JSDOC_DOC_TAG_TITLE_SEE,
	JSDOC_DOC_TAG_TITLE_CLASS,
	JSDOC_DOC_TAG_TITLE_NAMESPACE,
	JSDOC_DOC_TAG_TITLE_CONSTRUCTOR,
	JSDOC_DOC_TAG_TITLE_STATIC,
	JSDOC_DOC_TAG_TITLE_INNER,
	JSDOC_DOC_TAG_TITLE_FIELD,
	JSDOC_DOC_TAG_TITLE_FUNCTION,
	JSDOC_DOC_TAG_TITLE_EVENT,
	JSDOC_DOC_TAG_TITLE_NAME,
	JSDOC_DOC_TAG_TITLE_RETURN,
	JSDOC_DOC_TAG_TITLE_THROWS,
	JSDOC_DOC_TAG_TITLE_REQUIRES,
	JSDOC_DOC_TAG_TITLE_TYPE,
	JSDOC_DOC_TAG_TITLE_PRIVATE,
	JSDOC_DOC_TAG_TITLE_IGNORE,
	JSDOC_DOC_TAG_TITLE_ARGUMENTS,
	JSDOC_DOC_TAG_TITLE_EXTENDS,
	JSDOC_DOC_TAG_TITLE_DEFAULT,
	JSDOC_DOC_TAG_TITLE_MEMBEROF,
	JSDOC_DOC_TAG_TITLE_PUBLIC,
	JSDOC_DOC_TAG_TITLE_SCOPE,
	JSDOC_DOC_TAG_TITLE_SCOPEALIAS
} JSDOCDocTagTitle;

struct _JSDOCDocTag {
	GObject parent_instance;
	JSDOCDocTagPrivate * priv;
	JSDOCDocTagTitle title;
	gchar* type;
	gchar* name;
	gboolean isOptional;
	gchar* defaultValue;
	gchar* desc;
	GeeArrayList* optvalues;
	gchar* memberOf;
};

struct _JSDOCDocTagClass {
	GObjectClass parent_class;
};


static gpointer jsdoc_doc_comment_parent_class = NULL;
static GRegex* jsdoc_doc_comment_has_tag_regex;
static GRegex* jsdoc_doc_comment_has_tag_regex = NULL;
static GRegex* jsdoc_doc_comment_tag_regex;
static GRegex* jsdoc_doc_comment_tag_regex = NULL;
static GRegex* jsdoc_doc_comment_comment_line_start_regex;
static GRegex* jsdoc_doc_comment_comment_line_start_regex = NULL;
static GRegex* jsdoc_doc_comment_comment_line_start_white_space_regex;
static GRegex* jsdoc_doc_comment_comment_line_start_white_space_regex = NULL;
static GRegex* jsdoc_doc_comment_comment_needs_desc_regex;
static GRegex* jsdoc_doc_comment_comment_needs_desc_regex = NULL;
extern gchar* jsdoc_doc_comment_shared;
gchar* jsdoc_doc_comment_shared = NULL;
static gboolean jsdoc_doc_comment_done_init;
static gboolean jsdoc_doc_comment_done_init = FALSE;

GType jsdoc_doc_comment_get_type (void) G_GNUC_CONST;
GType jsdoc_doc_tag_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_DOC_COMMENT_DUMMY_PROPERTY
};
static void jsdoc_doc_comment_initRegex (void);
JSDOCDocComment* jsdoc_doc_comment_new (const gchar* comment);
JSDOCDocComment* jsdoc_doc_comment_construct (GType object_type, const gchar* comment);
gchar* jsdoc_doc_comment_unwrapComment (const gchar* comment);
static void jsdoc_doc_comment_fixDesc (JSDOCDocComment* self);
JSDOCDocTag* jsdoc_doc_tag_new (const gchar* in_src);
JSDOCDocTag* jsdoc_doc_tag_construct (GType object_type, const gchar* in_src);
GType jsdoc_doc_tag_title_get_type (void) G_GNUC_CONST;
GeeArrayList* jsdoc_doc_comment_getTag (JSDOCDocComment* self, JSDOCDocTagTitle tagTitle);
gchar* jsdoc_doc_comment_getTagAsString (JSDOCDocComment* self, JSDOCDocTagTitle tagTitle);
static void _vala_array_add9 (gchar** * array, int* length, int* size, gchar* value);
static void jsdoc_doc_comment_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

static GRegex* _tmp_regex_0 = NULL;
static GRegex* _tmp_regex_1 = NULL;
static GRegex* _tmp_regex_2 = NULL;
static GRegex* _tmp_regex_3 = NULL;

static void jsdoc_doc_comment_initRegex (void) {
	gboolean _tmp0_;
	GRegex* _tmp1_ = NULL;
	GRegex* _tmp2_;
	GRegex* _tmp3_;
	GRegex* _tmp4_ = NULL;
	GRegex* _tmp5_;
	GRegex* _tmp6_;
	GRegex* _tmp7_ = NULL;
	GRegex* _tmp8_;
	GRegex* _tmp9_;
	GRegex* _tmp10_ = NULL;
	GRegex* _tmp11_;
	GRegex* _tmp12_;
	GRegex* _tmp13_ = NULL;
	GRegex* _tmp14_;
	GRegex* _tmp15_;
	GError * _inner_error_ = NULL;
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = jsdoc_doc_comment_done_init;
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (_tmp0_) {
#line 39 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 177 "DocComment.c"
	}
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp2_ = g_regex_new ("^\\s*@\\s*\\S+", 0, 0, &_inner_error_);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp1_ = _tmp2_;
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 191 "DocComment.c"
	}
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp3_ = _tmp1_;
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp1_ = NULL;
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (jsdoc_doc_comment_has_tag_regex);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_has_tag_regex = _tmp3_;
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp5_ = g_regex_new ("(^|[\\r\\n])\\s*@", 0, 0, &_inner_error_);
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp4_ = _tmp5_;
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp1_);
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 215 "DocComment.c"
	}
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp6_ = _tmp4_;
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp4_ = NULL;
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (jsdoc_doc_comment_tag_regex);
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_tag_regex = _tmp6_;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp8_ = g_regex_new ("(^\\/\\*\\*|\\*\\/$)", 0, 0, &_inner_error_);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp7_ = _tmp8_;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp4_);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp1_);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 241 "DocComment.c"
	}
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp9_ = _tmp7_;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp7_ = NULL;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (jsdoc_doc_comment_comment_line_start_regex);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_comment_line_start_regex = _tmp9_;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp11_ = g_regex_new ("\\s*\\* ?", 0, 0, &_inner_error_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp10_ = _tmp11_;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp7_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp4_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp1_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 269 "DocComment.c"
	}
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp12_ = _tmp10_;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp10_ = NULL;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (jsdoc_doc_comment_comment_line_start_white_space_regex);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_comment_line_start_white_space_regex = _tmp12_;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp14_ = g_regex_new ("\\s*@(class|event|property)", 0, 0, &_inner_error_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp13_ = _tmp14_;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp10_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp7_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp4_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_regex_unref0 (_tmp1_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 299 "DocComment.c"
	}
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp15_ = _tmp13_;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp13_ = NULL;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (jsdoc_doc_comment_comment_needs_desc_regex);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_comment_needs_desc_regex = _tmp15_;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_done_init = TRUE;
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (_tmp13_);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (_tmp10_);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (_tmp7_);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (_tmp4_);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_regex_unref0 (_tmp1_);
#line 321 "DocComment.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
#line 1234 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1235 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1235 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1236 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1236 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1237 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	result = _result_;
#line 1237 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	return result;
#line 344 "DocComment.c"
}


static inline GRegex* _thread_safe_regex_init (GRegex** re, const gchar * pattern, GRegexMatchFlags match_options) {
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (g_once_init_enter ((volatile gsize*) re)) {
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		GRegex* val = g_regex_new (pattern, match_options, 0, NULL);
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_once_init_leave ((volatile gsize*) re, (gsize) val);
#line 355 "DocComment.c"
	}
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return *re;
#line 359 "DocComment.c"
}


JSDOCDocComment* jsdoc_doc_comment_construct (GType object_type, const gchar* comment) {
	JSDOCDocComment * self = NULL;
	const gchar* _tmp0_;
	GeeArrayList* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gboolean _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	const gchar* _tmp8_;
	gboolean _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_;
	gchar** bits = NULL;
	const gchar* _tmp15_;
	gchar** _tmp16_;
	gchar** _tmp17_;
	gint bits_length1;
	gint _bits_size_;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_return_val_if_fail (comment != NULL, NULL);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self = (JSDOCDocComment*) g_object_new (object_type, NULL);
#line 56 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_initRegex ();
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = comment;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_debug ("DocComment.vala:58: parse comment : %s", _tmp0_);
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp1_ = gee_array_list_new (JSDOC_TYPE_DOC_TAG, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_object_unref0 (self->tags);
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->tags = _tmp1_;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp2_ = comment;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp3_ = string_strip (_tmp2_);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp4_ = _tmp3_;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp5_ = g_strcmp0 (_tmp4_, "") == 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (_tmp4_);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (_tmp5_) {
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		comment = "/** @desc */";
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		self->isUserComment = FALSE;
#line 418 "DocComment.c"
	}
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp6_ = comment;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp7_ = jsdoc_doc_comment_unwrapComment (_tmp6_);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (self->src);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->src = _tmp7_;
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp8_ = self->src;
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp9_ = g_regex_match (_thread_safe_regex_init (&_tmp_regex_0, "^\\s*@\\s*\\S+", 0), _tmp8_, 0, NULL);
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->hasTags = _tmp9_;
#line 83 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_fixDesc (self);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp10_ = jsdoc_doc_comment_shared;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp11_ = g_strconcat (_tmp10_, "\n", NULL);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp12_ = _tmp11_;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp13_ = self->src;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp14_ = g_strconcat (_tmp12_, _tmp13_, NULL);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (self->src);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->src = _tmp14_;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (_tmp12_);
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp15_ = self->src;
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp17_ = _tmp16_ = g_regex_split (_thread_safe_regex_init (&_tmp_regex_1, "(^|[\\r\\n])\\s*@", 0), _tmp15_, 0);
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	bits = _tmp17_;
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	bits_length1 = _vala_array_length (_tmp16_);
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_bits_size_ = bits_length1;
#line 462 "DocComment.c"
	{
		gint i = 0;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		i = 0;
#line 467 "DocComment.c"
		{
			gboolean _tmp18_ = FALSE;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp18_ = TRUE;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			while (TRUE) {
#line 474 "DocComment.c"
				gint _tmp20_;
				gchar** _tmp21_;
				gint _tmp21__length1;
				gchar* sa = NULL;
				gchar** _tmp22_;
				gint _tmp22__length1;
				gint _tmp23_;
				const gchar* _tmp24_;
				gchar* _tmp25_;
				const gchar* _tmp26_;
				gchar* _tmp27_;
				gchar* _tmp28_;
				gint _tmp29_;
				gint _tmp30_;
				gboolean _tmp31_;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (!_tmp18_) {
#line 492 "DocComment.c"
					gint _tmp19_;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp19_ = i;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					i = _tmp19_ + 1;
#line 498 "DocComment.c"
				}
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp18_ = FALSE;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp20_ = i;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp21_ = bits;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp21__length1 = bits_length1;
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (!(_tmp20_ < _tmp21__length1)) {
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					break;
#line 512 "DocComment.c"
				}
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp22_ = bits;
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp22__length1 = bits_length1;
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp23_ = i;
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp24_ = _tmp22_[_tmp23_];
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp25_ = g_strdup (_tmp24_);
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				sa = _tmp25_;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp26_ = sa;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp27_ = string_strip (_tmp26_);
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp28_ = _tmp27_;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp29_ = strlen (_tmp28_);
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp30_ = _tmp29_;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp31_ = _tmp30_ > 0;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (_tmp28_);
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (_tmp31_) {
#line 542 "DocComment.c"
					GeeArrayList* _tmp32_;
					const gchar* _tmp33_;
					JSDOCDocTag* _tmp34_;
					JSDOCDocTag* _tmp35_;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp32_ = self->tags;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp33_ = sa;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp34_ = jsdoc_doc_tag_new (_tmp33_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp35_ = _tmp34_;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp32_, _tmp35_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_object_unref0 (_tmp35_);
#line 559 "DocComment.c"
				}
#line 95 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (sa);
#line 563 "DocComment.c"
			}
		}
	}
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	bits = (_vala_array_free (bits, bits_length1, (GDestroyNotify) g_free), NULL);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return self;
#line 571 "DocComment.c"
}


JSDOCDocComment* jsdoc_doc_comment_new (const gchar* comment) {
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return jsdoc_doc_comment_construct (JSDOC_TYPE_DOC_COMMENT, comment);
#line 578 "DocComment.c"
}


/**
 * Remove slash-star comment wrapper from a raw comment string.
 *  @type String
 */
gchar* jsdoc_doc_comment_unwrapComment (const gchar* comment) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gchar* ret = NULL;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_ = NULL;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	GError * _inner_error_ = NULL;
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_return_val_if_fail (comment != NULL, NULL);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = comment;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp1_ = strlen (_tmp0_);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp2_ = _tmp1_;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (_tmp2_ < 1) {
#line 617 "DocComment.c"
		gchar* _tmp3_;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp3_ = g_strdup ("");
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		result = _tmp3_;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return result;
#line 625 "DocComment.c"
	}
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp4_ = comment;
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp5_ = comment;
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp6_ = strlen (_tmp5_);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp7_ = _tmp6_;
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp8_ = g_regex_replace (_thread_safe_regex_init (&_tmp_regex_2, "^\\/\\*\\*|\\*\\/$", 0), _tmp4_, (gssize) _tmp7_, 0, "", 0, &_inner_error_);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret = _tmp8_;
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return NULL;
#line 647 "DocComment.c"
	}
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp10_ = ret;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp11_ = ret;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp12_ = strlen (_tmp11_);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp13_ = _tmp12_;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp14_ = g_regex_replace (_thread_safe_regex_init (&_tmp_regex_3, "(^|[\\r\\n])\\s*\\* ?", 0), _tmp10_, (gssize) _tmp13_, 0, "\n", 0, &_inner_error_);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp9_ = _tmp14_;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_free0 (ret);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		g_clear_error (&_inner_error_);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return NULL;
#line 671 "DocComment.c"
	}
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp15_ = _tmp9_;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp9_ = NULL;
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (ret);
#line 122 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret = _tmp15_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp16_ = ret;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp17_ = string_strip (_tmp16_);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	result = _tmp17_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (_tmp9_);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (ret);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return result;
#line 693 "DocComment.c"
}


/**
        If no @desc tag is provided, this function will add it.
     */
static void jsdoc_doc_comment_fixDesc (JSDOCDocComment* self) {
	gboolean _tmp0_;
	GRegex* _tmp3_;
	const gchar* _tmp4_;
	gboolean _tmp5_;
	gchar** lines = NULL;
	const gchar* _tmp6_;
	gchar** _tmp7_;
	gchar** _tmp8_;
	gint lines_length1;
	gint _lines_size_;
	gchar* nsrc = NULL;
	gchar* _tmp9_;
	gboolean gotf = FALSE;
	const gchar* _tmp39_;
	gchar* _tmp40_;
#line 129 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_return_if_fail (self != NULL);
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = self->hasTags;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (!_tmp0_) {
#line 722 "DocComment.c"
		const gchar* _tmp1_;
		gchar* _tmp2_;
#line 138 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp1_ = self->src;
#line 138 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp2_ = g_strconcat ("@desc ", _tmp1_, NULL);
#line 138 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_free0 (self->src);
#line 138 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		self->src = _tmp2_;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 735 "DocComment.c"
	}
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp3_ = jsdoc_doc_comment_comment_needs_desc_regex;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp4_ = self->src;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp5_ = g_regex_match (_tmp3_, _tmp4_, G_REGEX_MATCH_NEWLINE_ANYCRLF, NULL);
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if (!_tmp5_) {
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		return;
#line 747 "DocComment.c"
	}
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp6_ = self->src;
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp8_ = _tmp7_ = g_strsplit (_tmp6_, "\n", 0);
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	lines = _tmp8_;
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	lines_length1 = _vala_array_length (_tmp7_);
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_lines_size_ = lines_length1;
#line 154 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp9_ = g_strdup ("");
#line 154 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	nsrc = _tmp9_;
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	gotf = FALSE;
#line 765 "DocComment.c"
	{
		gint i = 0;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		i = 0;
#line 770 "DocComment.c"
		{
			gboolean _tmp10_ = FALSE;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp10_ = TRUE;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			while (TRUE) {
#line 777 "DocComment.c"
				gint _tmp12_;
				gchar** _tmp13_;
				gint _tmp13__length1;
				gchar* line = NULL;
				gchar** _tmp14_;
				gint _tmp14__length1;
				gint _tmp15_;
				const gchar* _tmp16_;
				gchar* _tmp17_;
				gboolean _tmp18_;
				GRegex* _tmp24_;
				const gchar* _tmp25_;
				gboolean _tmp26_;
				const gchar* _tmp32_;
				const gchar* _tmp33_;
				gchar* _tmp34_;
				gchar* _tmp35_;
				gchar* _tmp36_;
				gchar* _tmp37_;
				gchar* _tmp38_;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (!_tmp10_) {
#line 800 "DocComment.c"
					gint _tmp11_;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp11_ = i;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					i = _tmp11_ + 1;
#line 806 "DocComment.c"
				}
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp10_ = FALSE;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp12_ = i;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp13_ = lines;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp13__length1 = lines_length1;
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (!(_tmp12_ < _tmp13__length1)) {
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					break;
#line 820 "DocComment.c"
				}
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp14_ = lines;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp14__length1 = lines_length1;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp15_ = i;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp16_ = _tmp14_[_tmp15_];
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp17_ = g_strdup (_tmp16_);
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				line = _tmp17_;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp18_ = gotf;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (_tmp18_) {
#line 838 "DocComment.c"
					const gchar* _tmp19_;
					const gchar* _tmp20_;
					gchar* _tmp21_;
					gchar* _tmp22_;
					gchar* _tmp23_;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp19_ = nsrc;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp20_ = line;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp21_ = g_strconcat (_tmp20_, "\n", NULL);
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp22_ = _tmp21_;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp23_ = g_strconcat (_tmp19_, _tmp22_, NULL);
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (nsrc);
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					nsrc = _tmp23_;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (_tmp22_);
#line 161 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (line);
#line 161 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					continue;
#line 864 "DocComment.c"
				}
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp24_ = jsdoc_doc_comment_has_tag_regex;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp25_ = line;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp26_ = g_regex_match (_tmp24_, _tmp25_, 0, NULL);
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				if (_tmp26_) {
#line 874 "DocComment.c"
					const gchar* _tmp27_;
					const gchar* _tmp28_;
					gchar* _tmp29_;
					gchar* _tmp30_;
					gchar* _tmp31_;
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp27_ = nsrc;
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp28_ = line;
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp29_ = g_strconcat (_tmp28_, "\n", NULL);
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp30_ = _tmp29_;
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_tmp31_ = g_strconcat (_tmp27_, _tmp30_, NULL);
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (nsrc);
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					nsrc = _tmp31_;
#line 164 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (_tmp30_);
#line 165 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					_g_free0 (line);
#line 165 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
					continue;
#line 900 "DocComment.c"
				}
#line 167 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				gotf = TRUE;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp32_ = nsrc;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp33_ = line;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp34_ = g_strconcat ("@desc ", _tmp33_, NULL);
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp35_ = _tmp34_;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp36_ = g_strconcat (_tmp35_, "\n", NULL);
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp37_ = _tmp36_;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp38_ = g_strconcat (_tmp32_, _tmp37_, NULL);
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (nsrc);
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				nsrc = _tmp38_;
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (_tmp37_);
#line 168 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (_tmp35_);
#line 157 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_g_free0 (line);
#line 928 "DocComment.c"
			}
		}
	}
#line 172 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp39_ = nsrc;
#line 172 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp40_ = g_strdup (_tmp39_);
#line 172 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (self->src);
#line 172 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->src = _tmp40_;
#line 129 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (nsrc);
#line 129 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
#line 944 "DocComment.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return self ? g_object_ref (self) : NULL;
#line 951 "DocComment.c"
}


GeeArrayList* jsdoc_doc_comment_getTag (JSDOCDocComment* self, JSDOCDocTagTitle tagTitle) {
	GeeArrayList* result = NULL;
	GeeArrayList* ret = NULL;
	GeeArrayList* _tmp0_;
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 180 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = gee_array_list_new (JSDOC_TYPE_DOC_TAG, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 180 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret = _tmp0_;
#line 965 "DocComment.c"
	{
		GeeArrayList* _tag_list = NULL;
		GeeArrayList* _tmp1_;
		GeeArrayList* _tmp2_;
		gint _tag_size = 0;
		GeeArrayList* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		gint _tag_index = 0;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp1_ = self->tags;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp2_ = _g_object_ref0 (_tmp1_);
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_list = _tmp2_;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp3_ = _tag_list;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp5_ = _tmp4_;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_size = _tmp5_;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_index = -1;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		while (TRUE) {
#line 993 "DocComment.c"
			gint _tmp6_;
			gint _tmp7_;
			gint _tmp8_;
			JSDOCDocTag* tag = NULL;
			GeeArrayList* _tmp9_;
			gint _tmp10_;
			gpointer _tmp11_;
			JSDOCDocTag* _tmp12_;
			JSDOCDocTagTitle _tmp13_;
			JSDOCDocTagTitle _tmp14_;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp6_ = _tag_index;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tag_index = _tmp6_ + 1;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp7_ = _tag_index;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp8_ = _tag_size;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			if (!(_tmp7_ < _tmp8_)) {
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				break;
#line 1016 "DocComment.c"
			}
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp9_ = _tag_list;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp10_ = _tag_index;
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			tag = (JSDOCDocTag*) _tmp11_;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp12_ = tag;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp13_ = _tmp12_->title;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp14_ = tagTitle;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			if (_tmp13_ == _tmp14_) {
#line 1034 "DocComment.c"
				GeeArrayList* _tmp15_;
				JSDOCDocTag* _tmp16_;
#line 183 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp15_ = ret;
#line 183 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp16_ = tag;
#line 183 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp15_, _tmp16_);
#line 1043 "DocComment.c"
			}
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_g_object_unref0 (tag);
#line 1047 "DocComment.c"
		}
#line 181 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_object_unref0 (_tag_list);
#line 1051 "DocComment.c"
	}
#line 186 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	result = ret;
#line 186 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return result;
#line 1057 "DocComment.c"
}


static void _vala_array_add9 (gchar** * array, int* length, int* size, gchar* value) {
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	if ((*length) == (*size)) {
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 1068 "DocComment.c"
	}
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	(*array)[(*length)++] = value;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	(*array)[*length] = NULL;
#line 1074 "DocComment.c"
}


static gchar* _vala_g_strjoinv (const gchar* separator, gchar** str_array, int str_array_length1) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_;
	gint _tmp3__length1;
#line 1078 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_tmp0_ = separator;
#line 1078 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	if (_tmp0_ == NULL) {
#line 1079 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		separator = "";
#line 1091 "DocComment.c"
	}
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_tmp3_ = str_array;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	_tmp3__length1 = str_array_length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp2_ = TRUE;
#line 1101 "DocComment.c"
	} else {
		gchar** _tmp4_;
		gint _tmp4__length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp4_ = str_array;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp4__length1 = str_array_length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp4__length1 > 0;
#line 1111 "DocComment.c"
	}
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	if (_tmp2_) {
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 1117 "DocComment.c"
	} else {
		gboolean _tmp5_ = FALSE;
		gchar** _tmp6_;
		gint _tmp6__length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp6_ = str_array;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp6__length1 = str_array_length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		if (_tmp6__length1 == -1) {
#line 1128 "DocComment.c"
			gchar** _tmp7_;
			gint _tmp7__length1;
			const gchar* _tmp8_;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp7_ = str_array;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp7__length1 = str_array_length1;
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp8_ = _tmp7_[0];
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp5_ = _tmp8_ != NULL;
#line 1140 "DocComment.c"
		} else {
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp5_ = FALSE;
#line 1144 "DocComment.c"
		}
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp1_ = _tmp5_;
#line 1148 "DocComment.c"
	}
#line 1081 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
	if (_tmp1_) {
#line 1152 "DocComment.c"
		gint i = 0;
		gsize len = 0UL;
		gint _tmp31_;
		gint _tmp33_;
		gint _tmp34_;
		gsize _tmp35_;
		const gchar* _tmp36_;
		gint _tmp37_;
		gint _tmp38_;
		gint _tmp39_;
		const gchar* res = NULL;
		gsize _tmp40_;
		void* _tmp41_;
		void* ptr = NULL;
		const gchar* _tmp42_;
		gchar** _tmp43_;
		gint _tmp43__length1;
		const gchar* _tmp44_;
		void* _tmp45_;
		const gchar* _tmp62_;
#line 1083 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		len = (gsize) 1;
#line 1175 "DocComment.c"
		{
			gboolean _tmp9_ = FALSE;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			i = 0;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp9_ = TRUE;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			while (TRUE) {
#line 1184 "DocComment.c"
				gboolean _tmp11_ = FALSE;
				gboolean _tmp12_ = FALSE;
				gchar** _tmp13_;
				gint _tmp13__length1;
				gint _tmp21_ = 0;
				gchar** _tmp22_;
				gint _tmp22__length1;
				gint _tmp23_;
				const gchar* _tmp24_;
				gsize _tmp30_;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (!_tmp9_) {
#line 1197 "DocComment.c"
					gint _tmp10_;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp10_ = i;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					i = _tmp10_ + 1;
#line 1203 "DocComment.c"
				}
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp9_ = FALSE;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp13_ = str_array;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp13__length1 = str_array_length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (_tmp13__length1 != -1) {
#line 1213 "DocComment.c"
					gint _tmp14_;
					gchar** _tmp15_;
					gint _tmp15__length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp14_ = i;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp15_ = str_array;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp15__length1 = str_array_length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp12_ = _tmp14_ < _tmp15__length1;
#line 1225 "DocComment.c"
				} else {
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp12_ = FALSE;
#line 1229 "DocComment.c"
				}
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (_tmp12_) {
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp11_ = TRUE;
#line 1235 "DocComment.c"
				} else {
					gboolean _tmp16_ = FALSE;
					gchar** _tmp17_;
					gint _tmp17__length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp17_ = str_array;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp17__length1 = str_array_length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					if (_tmp17__length1 == -1) {
#line 1246 "DocComment.c"
						gchar** _tmp18_;
						gint _tmp18__length1;
						gint _tmp19_;
						const gchar* _tmp20_;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp18_ = str_array;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp18__length1 = str_array_length1;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp19_ = i;
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp20_ = _tmp18_[_tmp19_];
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp16_ = _tmp20_ != NULL;
#line 1261 "DocComment.c"
					} else {
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
						_tmp16_ = FALSE;
#line 1265 "DocComment.c"
					}
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp11_ = _tmp16_;
#line 1269 "DocComment.c"
				}
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (!_tmp11_) {
#line 1084 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					break;
#line 1275 "DocComment.c"
				}
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp22_ = str_array;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp22__length1 = str_array_length1;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp23_ = i;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp24_ = _tmp22_[_tmp23_];
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (_tmp24_ != NULL) {
#line 1287 "DocComment.c"
					gchar** _tmp25_;
					gint _tmp25__length1;
					gint _tmp26_;
					const gchar* _tmp27_;
					gint _tmp28_;
					gint _tmp29_;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp25_ = str_array;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp25__length1 = str_array_length1;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp26_ = i;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp27_ = _tmp25_[_tmp26_];
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp28_ = strlen ((const gchar*) _tmp27_);
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp29_ = _tmp28_;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp21_ = _tmp29_;
#line 1308 "DocComment.c"
				} else {
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp21_ = 0;
#line 1312 "DocComment.c"
				}
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp30_ = len;
#line 1085 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				len = _tmp30_ + _tmp21_;
#line 1318 "DocComment.c"
			}
		}
#line 1087 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp31_ = i;
#line 1087 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		if (_tmp31_ == 0) {
#line 1325 "DocComment.c"
			gchar* _tmp32_;
#line 1088 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp32_ = g_strdup ("");
#line 1088 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			result = _tmp32_;
#line 1088 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			return result;
#line 1333 "DocComment.c"
		}
#line 1090 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp33_ = i;
#line 1090 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		str_array_length1 = _tmp33_;
#line 1090 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp34_ = str_array_length1;
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp35_ = len;
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp36_ = separator;
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp37_ = strlen ((const gchar*) _tmp36_);
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp38_ = _tmp37_;
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp39_ = i;
#line 1091 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		len = _tmp35_ + (_tmp38_ * (_tmp39_ - 1));
#line 1093 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp40_ = len;
#line 1093 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp41_ = g_malloc (_tmp40_);
#line 1093 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		res = _tmp41_;
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp42_ = res;
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp43_ = str_array;
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp43__length1 = str_array_length1;
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp44_ = _tmp43_[0];
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp45_ = g_stpcpy ((void*) _tmp42_, (const gchar*) _tmp44_);
#line 1094 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		ptr = _tmp45_;
#line 1371 "DocComment.c"
		{
			gboolean _tmp46_ = FALSE;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			i = 1;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			_tmp46_ = TRUE;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
			while (TRUE) {
#line 1380 "DocComment.c"
				gint _tmp48_;
				gchar** _tmp49_;
				gint _tmp49__length1;
				void* _tmp50_;
				const gchar* _tmp51_;
				void* _tmp52_;
				const gchar* _tmp53_ = NULL;
				gchar** _tmp54_;
				gint _tmp54__length1;
				gint _tmp55_;
				const gchar* _tmp56_;
				void* _tmp60_;
				void* _tmp61_;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (!_tmp46_) {
#line 1396 "DocComment.c"
					gint _tmp47_;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp47_ = i;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					i = _tmp47_ + 1;
#line 1402 "DocComment.c"
				}
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp46_ = FALSE;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp48_ = i;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp49_ = str_array;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp49__length1 = str_array_length1;
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (!(_tmp48_ < _tmp49__length1)) {
#line 1095 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					break;
#line 1416 "DocComment.c"
				}
#line 1096 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp50_ = ptr;
#line 1096 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp51_ = separator;
#line 1096 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp52_ = g_stpcpy (_tmp50_, (const gchar*) _tmp51_);
#line 1096 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				ptr = _tmp52_;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp54_ = str_array;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp54__length1 = str_array_length1;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp55_ = i;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp56_ = _tmp54_[_tmp55_];
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				if (_tmp56_ != NULL) {
#line 1436 "DocComment.c"
					gchar** _tmp57_;
					gint _tmp57__length1;
					gint _tmp58_;
					const gchar* _tmp59_;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp57_ = str_array;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp57__length1 = str_array_length1;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp58_ = i;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp59_ = _tmp57_[_tmp58_];
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp53_ = (const gchar*) _tmp59_;
#line 1451 "DocComment.c"
				} else {
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
					_tmp53_ = "";
#line 1455 "DocComment.c"
				}
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp60_ = ptr;
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				_tmp61_ = g_stpcpy (_tmp60_, _tmp53_);
#line 1097 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
				ptr = _tmp61_;
#line 1463 "DocComment.c"
			}
		}
#line 1100 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp62_ = res;
#line 1100 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		res = NULL;
#line 1100 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		result = (gchar*) _tmp62_;
#line 1100 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		return result;
#line 1474 "DocComment.c"
	} else {
		gchar* _tmp63_;
#line 1102 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		_tmp63_ = g_strdup ("");
#line 1102 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		result = _tmp63_;
#line 1102 "/usr/share/vala-0.36/vapi/glib-2.0.vapi"
		return result;
#line 1483 "DocComment.c"
	}
}


gchar* jsdoc_doc_comment_getTagAsString (JSDOCDocComment* self, JSDOCDocTagTitle tagTitle) {
	gchar* result = NULL;
	gchar** ret = NULL;
	gchar** _tmp0_;
	gint ret_length1;
	gint _ret_size_;
	gchar** _tmp19_;
	gint _tmp19__length1;
	gchar* _tmp20_;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = g_new0 (gchar*, 0 + 1);
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret = _tmp0_;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret_length1 = 0;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_ret_size_ = ret_length1;
#line 1507 "DocComment.c"
	{
		GeeArrayList* _tag_list = NULL;
		GeeArrayList* _tmp1_;
		GeeArrayList* _tmp2_;
		gint _tag_size = 0;
		GeeArrayList* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		gint _tag_index = 0;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp1_ = self->tags;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp2_ = _g_object_ref0 (_tmp1_);
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_list = _tmp2_;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp3_ = _tag_list;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tmp5_ = _tmp4_;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_size = _tmp5_;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_tag_index = -1;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		while (TRUE) {
#line 1535 "DocComment.c"
			gint _tmp6_;
			gint _tmp7_;
			gint _tmp8_;
			JSDOCDocTag* tag = NULL;
			GeeArrayList* _tmp9_;
			gint _tmp10_;
			gpointer _tmp11_;
			JSDOCDocTag* _tmp12_;
			JSDOCDocTagTitle _tmp13_;
			JSDOCDocTagTitle _tmp14_;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp6_ = _tag_index;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tag_index = _tmp6_ + 1;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp7_ = _tag_index;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp8_ = _tag_size;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			if (!(_tmp7_ < _tmp8_)) {
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				break;
#line 1558 "DocComment.c"
			}
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp9_ = _tag_list;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp10_ = _tag_index;
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			tag = (JSDOCDocTag*) _tmp11_;
#line 191 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp12_ = tag;
#line 191 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp13_ = _tmp12_->title;
#line 191 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_tmp14_ = tagTitle;
#line 191 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			if (_tmp13_ == _tmp14_) {
#line 1576 "DocComment.c"
				gchar** _tmp15_;
				gint _tmp15__length1;
				JSDOCDocTag* _tmp16_;
				const gchar* _tmp17_;
				gchar* _tmp18_;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp15_ = ret;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp15__length1 = ret_length1;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp16_ = tag;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp17_ = _tmp16_->desc;
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_tmp18_ = g_strdup (_tmp17_);
#line 192 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
				_vala_array_add9 (&ret, &ret_length1, &_ret_size_, _tmp18_);
#line 1594 "DocComment.c"
			}
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
			_g_object_unref0 (tag);
#line 1598 "DocComment.c"
		}
#line 190 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
		_g_object_unref0 (_tag_list);
#line 1602 "DocComment.c"
	}
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp19_ = ret;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp19__length1 = ret_length1;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp20_ = _vala_g_strjoinv ("\n", _tmp19_, _tmp19__length1);
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	result = _tmp20_;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	ret = (_vala_array_free (ret, ret_length1, (GDestroyNotify) g_free), NULL);
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	return result;
#line 1616 "DocComment.c"
}


static void jsdoc_doc_comment_class_init (JSDOCDocCommentClass * klass) {
	gchar* _tmp0_;
#line 11 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_parent_class = g_type_class_peek_parent (klass);
#line 11 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_doc_comment_finalize;
#line 32 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = g_strdup ("");
#line 32 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	jsdoc_doc_comment_shared = _tmp0_;
#line 1630 "DocComment.c"
}


static void jsdoc_doc_comment_instance_init (JSDOCDocComment * self) {
	gchar* _tmp0_;
#line 14 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->isUserComment = TRUE;
#line 15 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->hasTags = FALSE;
#line 16 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_tmp0_ = g_strdup ("");
#line 16 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self->src = _tmp0_;
#line 1644 "DocComment.c"
}


static void jsdoc_doc_comment_finalize (GObject * obj) {
	JSDOCDocComment * self;
#line 11 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_DOC_COMMENT, JSDOCDocComment);
#line 16 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_free0 (self->src);
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	_g_object_unref0 (self->tags);
#line 11 "/home/alan/gitlive/roojspacker/src/jsdoc/DocComment.vala"
	G_OBJECT_CLASS (jsdoc_doc_comment_parent_class)->finalize (obj);
#line 1658 "DocComment.c"
}


GType jsdoc_doc_comment_get_type (void) {
	static volatile gsize jsdoc_doc_comment_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_doc_comment_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCDocCommentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_doc_comment_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCDocComment), 0, (GInstanceInitFunc) jsdoc_doc_comment_instance_init, NULL };
		GType jsdoc_doc_comment_type_id;
		jsdoc_doc_comment_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCDocComment", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_doc_comment_type_id__volatile, jsdoc_doc_comment_type_id);
	}
	return jsdoc_doc_comment_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



