/* TokenStream.c generated by valac 0.36.6, the Vala compiler
 * generated from TokenStream.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define JSDOC_TYPE_TOKEN_STREAM (jsdoc_token_stream_get_type ())
#define JSDOC_TOKEN_STREAM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStream))
#define JSDOC_TOKEN_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStreamClass))
#define JSDOC_IS_TOKEN_STREAM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN_STREAM))
#define JSDOC_IS_TOKEN_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN_STREAM))
#define JSDOC_TOKEN_STREAM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStreamClass))

typedef struct _JSDOCTokenStream JSDOCTokenStream;
typedef struct _JSDOCTokenStreamClass JSDOCTokenStreamClass;
typedef struct _JSDOCTokenStreamPrivate JSDOCTokenStreamPrivate;

#define JSDOC_TYPE_TOKEN (jsdoc_token_get_type ())
#define JSDOC_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN, JSDOCToken))
#define JSDOC_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN, JSDOCTokenClass))
#define JSDOC_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN))
#define JSDOC_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN))
#define JSDOC_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN, JSDOCTokenClass))

typedef struct _JSDOCToken JSDOCToken;
typedef struct _JSDOCTokenClass JSDOCTokenClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define JSDOC_TYPE_TOKEN_TYPE (jsdoc_token_type_get_type ())

#define JSDOC_TYPE_TOKEN_NAME (jsdoc_token_name_get_type ())
typedef struct _JSDOCTokenPrivate JSDOCTokenPrivate;

#define JSDOC_TYPE_IDENTIFIER (jsdoc_identifier_get_type ())
#define JSDOC_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifier))
#define JSDOC_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))
#define JSDOC_IS_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IS_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IDENTIFIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))

typedef struct _JSDOCIdentifier JSDOCIdentifier;
typedef struct _JSDOCIdentifierClass JSDOCIdentifierClass;

#define JSDOC_TYPE_TOKEN_KEY_MAP (jsdoc_token_key_map_get_type ())
#define JSDOC_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMap))
#define JSDOC_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))
#define JSDOC_IS_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_IS_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_TOKEN_KEY_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))

typedef struct _JSDOCTokenKeyMap JSDOCTokenKeyMap;
typedef struct _JSDOCTokenKeyMapClass JSDOCTokenKeyMapClass;

#define JSDOC_TYPE_LANGCLASS (jsdoc_langclass_get_type ())
#define JSDOC_LANGCLASS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_LANGCLASS, JSDOCLang_Class))
#define JSDOC_LANGCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_LANGCLASS, JSDOCLang_ClassClass))
#define JSDOC_IS_LANGCLASS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_LANGCLASS))
#define JSDOC_IS_LANGCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_LANGCLASS))
#define JSDOC_LANGCLASS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_LANGCLASS, JSDOCLang_ClassClass))

typedef struct _JSDOCLang_Class JSDOCLang_Class;
typedef struct _JSDOCLang_ClassClass JSDOCLang_ClassClass;
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

typedef enum  {
	JSDOC_TOKEN_STREAM_ERROR_ArgumentError
} JSDOCTokenStreamError;
#define JSDOC_TOKEN_STREAM_ERROR jsdoc_token_stream_error_quark ()
struct _JSDOCTokenStream {
	GObject parent_instance;
	JSDOCTokenStreamPrivate * priv;
	GeeArrayList* tokens;
	gint cursor;
};

struct _JSDOCTokenStreamClass {
	GObjectClass parent_class;
};

typedef enum  {
	JSDOC_TOKEN_TYPE_TOKN,
	JSDOC_TOKEN_TYPE_KEYW,
	JSDOC_TOKEN_TYPE_NAME,
	JSDOC_TOKEN_TYPE_COMM,
	JSDOC_TOKEN_TYPE_PUNC,
	JSDOC_TOKEN_TYPE_WHIT,
	JSDOC_TOKEN_TYPE_STRN,
	JSDOC_TOKEN_TYPE_NUMB,
	JSDOC_TOKEN_TYPE_REGX,
	JSDOC_TOKEN_TYPE_VOID
} JSDOCTokenType;

typedef enum  {
	JSDOC_TOKEN_NAME_UNKNOWN_TOKEN,
	JSDOC_TOKEN_NAME_BREAK,
	JSDOC_TOKEN_NAME_CASE,
	JSDOC_TOKEN_NAME_CATCH,
	JSDOC_TOKEN_NAME_CONST,
	JSDOC_TOKEN_NAME_CONTINUE,
	JSDOC_TOKEN_NAME_DEFAULT,
	JSDOC_TOKEN_NAME_DELETE,
	JSDOC_TOKEN_NAME_DO,
	JSDOC_TOKEN_NAME_ELSE,
	JSDOC_TOKEN_NAME_FALSE,
	JSDOC_TOKEN_NAME_FINALLY,
	JSDOC_TOKEN_NAME_FOR,
	JSDOC_TOKEN_NAME_FUNCTION,
	JSDOC_TOKEN_NAME_IF,
	JSDOC_TOKEN_NAME_IN,
	JSDOC_TOKEN_NAME_INSTANCEOF,
	JSDOC_TOKEN_NAME_NEW,
	JSDOC_TOKEN_NAME_NULL,
	JSDOC_TOKEN_NAME_RETURN,
	JSDOC_TOKEN_NAME_SWITCH,
	JSDOC_TOKEN_NAME_THIS,
	JSDOC_TOKEN_NAME_THROW,
	JSDOC_TOKEN_NAME_TRUE,
	JSDOC_TOKEN_NAME_TRY,
	JSDOC_TOKEN_NAME_TYPEOF,
	JSDOC_TOKEN_NAME_VOID,
	JSDOC_TOKEN_NAME_WHILE,
	JSDOC_TOKEN_NAME_WITH,
	JSDOC_TOKEN_NAME_VAR,
	JSDOC_TOKEN_NAME_EVAL,
	JSDOC_TOKEN_NAME_NAME,
	JSDOC_TOKEN_NAME_MULTI_LINE_COMM,
	JSDOC_TOKEN_NAME_JSDOC,
	JSDOC_TOKEN_NAME_SINGLE_LINE_COMM,
	JSDOC_TOKEN_NAME_SEMICOLON,
	JSDOC_TOKEN_NAME_COMMA,
	JSDOC_TOKEN_NAME_HOOK,
	JSDOC_TOKEN_NAME_COLON,
	JSDOC_TOKEN_NAME_OR,
	JSDOC_TOKEN_NAME_AND,
	JSDOC_TOKEN_NAME_BITWISE_OR,
	JSDOC_TOKEN_NAME_BITWISE_XOR,
	JSDOC_TOKEN_NAME_BITWISE_AND,
	JSDOC_TOKEN_NAME_STRICT_EQ,
	JSDOC_TOKEN_NAME_EQ,
	JSDOC_TOKEN_NAME_ASSIGN,
	JSDOC_TOKEN_NAME_STRICT_NE,
	JSDOC_TOKEN_NAME_NE,
	JSDOC_TOKEN_NAME_LSH,
	JSDOC_TOKEN_NAME_LE,
	JSDOC_TOKEN_NAME_LT,
	JSDOC_TOKEN_NAME_URSH,
	JSDOC_TOKEN_NAME_RSH,
	JSDOC_TOKEN_NAME_GE,
	JSDOC_TOKEN_NAME_GT,
	JSDOC_TOKEN_NAME_INCREMENT,
	JSDOC_TOKEN_NAME_DECREMENT,
	JSDOC_TOKEN_NAME_PLUS,
	JSDOC_TOKEN_NAME_MINUS,
	JSDOC_TOKEN_NAME_MUL,
	JSDOC_TOKEN_NAME_DIV,
	JSDOC_TOKEN_NAME_MOD,
	JSDOC_TOKEN_NAME_NOT,
	JSDOC_TOKEN_NAME_BITWISE_NOT,
	JSDOC_TOKEN_NAME_DOT,
	JSDOC_TOKEN_NAME_LEFT_BRACE,
	JSDOC_TOKEN_NAME_RIGHT_BRACE,
	JSDOC_TOKEN_NAME_LEFT_CURLY,
	JSDOC_TOKEN_NAME_RIGHT_CURLY,
	JSDOC_TOKEN_NAME_LEFT_PAREN,
	JSDOC_TOKEN_NAME_RIGHT_PAREN,
	JSDOC_TOKEN_NAME_SPACE,
	JSDOC_TOKEN_NAME_NEWLINE,
	JSDOC_TOKEN_NAME_DOUBLE_QUOTE,
	JSDOC_TOKEN_NAME_SINGLE_QUOTE,
	JSDOC_TOKEN_NAME_OCTAL,
	JSDOC_TOKEN_NAME_DECIMAL,
	JSDOC_TOKEN_NAME_HEX_DEC,
	JSDOC_TOKEN_NAME_REGX,
	JSDOC_TOKEN_NAME_START_OF_STREAM,
	JSDOC_TOKEN_NAME_END_OF_STREAM,
	JSDOC_TOKEN_NAME_UNKNOWN
} JSDOCTokenName;

struct _JSDOCToken {
	GObject parent_instance;
	JSDOCTokenPrivate * priv;
	gint id;
	gchar* data;
	JSDOCTokenType type;
	JSDOCTokenName name;
	gint line;
	gchar* prefix;
	gchar* outData;
	JSDOCIdentifier* identifier;
	GeeArrayList* items;
	GeeHashMap* props;
	GeeArrayList* keyseq;
};

struct _JSDOCTokenClass {
	GObjectClass parent_class;
};

typedef enum  {
	JSDOC_LANG_ERROR_ArgumentError
} JSDOCLangError;
#define JSDOC_LANG_ERROR jsdoc_lang_error_quark ()

static gpointer jsdoc_token_stream_parent_class = NULL;
extern JSDOCLang_Class* jsdoc_Lang;

GQuark jsdoc_token_stream_error_quark (void);
GType jsdoc_token_stream_get_type (void) G_GNUC_CONST;
GType jsdoc_token_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_TOKEN_STREAM_DUMMY_PROPERTY
};
JSDOCTokenStream* jsdoc_token_stream_new (GeeArrayList* tokens);
JSDOCTokenStream* jsdoc_token_stream_construct (GType object_type, GeeArrayList* tokens);
void jsdoc_token_stream_rewind (JSDOCTokenStream* self);
GeeArrayList* jsdoc_token_stream_toArray (JSDOCTokenStream* self);
JSDOCToken* jsdoc_token_stream_look (JSDOCTokenStream* self, gint n, gboolean considerWhitespace);
GType jsdoc_token_type_get_type (void) G_GNUC_CONST;
GType jsdoc_token_name_get_type (void) G_GNUC_CONST;
JSDOCToken* jsdoc_token_new (const gchar* data, JSDOCTokenType type, JSDOCTokenName name, gint line);
JSDOCToken* jsdoc_token_construct (GType object_type, const gchar* data, JSDOCTokenType type, JSDOCTokenName name, gint line);
gboolean jsdoc_token_isType (JSDOCToken* self, JSDOCTokenType what);
JSDOCToken* jsdoc_token_stream_lookAny (JSDOCTokenStream* self, gint n);
gint jsdoc_token_stream_lookFor (JSDOCTokenStream* self, const gchar* data);
GType jsdoc_identifier_get_type (void) G_GNUC_CONST;
GType jsdoc_token_key_map_get_type (void) G_GNUC_CONST;
JSDOCToken* jsdoc_token_stream_lookTok (JSDOCTokenStream* self, gint n);
JSDOCToken* jsdoc_token_stream_next (JSDOCTokenStream* self);
GeeArrayList* jsdoc_token_stream_nextM (JSDOCTokenStream* self, gint howMany, GError** error);
JSDOCToken* jsdoc_token_stream_nextTok (JSDOCTokenStream* self);
JSDOCToken* jsdoc_token_stream_nextNonSpace (JSDOCTokenStream* self);
GeeArrayList* jsdoc_token_stream_balance (JSDOCTokenStream* self, JSDOCTokenName in_start, GError** error);
GType jsdoc_langclass_get_type (void) G_GNUC_CONST;
GQuark jsdoc_lang_error_quark (void);
JSDOCTokenName* jsdoc_langclass_matching (JSDOCLang_Class* self, JSDOCTokenName name, GError** error);
const gchar* jsdoc_token_name_to_string (JSDOCTokenName self);
gboolean jsdoc_token_isName (JSDOCToken* self, JSDOCTokenName what);
JSDOCToken* jsdoc_token_stream_getMatchingTokenEnd (JSDOCTokenStream* self, JSDOCTokenName end);
JSDOCToken* jsdoc_token_stream_getMatchingToken (JSDOCTokenStream* self, JSDOCTokenName start, gint depth);
GeeArrayList* jsdoc_token_stream_remaining (JSDOCTokenStream* self);
void jsdoc_token_stream_printRange (JSDOCTokenStream* self, gint start, gint end);
gchar* jsdoc_token_asString (JSDOCToken* self);
void jsdoc_token_stream_dump (JSDOCTokenStream* self, gint start, gint end);
void jsdoc_token_stream_dumpAll (JSDOCTokenStream* self, const gchar* indent);
void jsdoc_token_dump (JSDOCToken* self, const gchar* indent);
void jsdoc_token_stream_dumpAllFlat (JSDOCTokenStream* self);
static void jsdoc_token_stream_finalize (GObject * obj);


GQuark jsdoc_token_stream_error_quark (void) {
	return g_quark_from_static_string ("jsdoc_token_stream_error-quark");
}


static gpointer _g_object_ref0 (gpointer self) {
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return self ? g_object_ref (self) : NULL;
#line 264 "TokenStream.c"
}


JSDOCTokenStream* jsdoc_token_stream_construct (GType object_type, GeeArrayList* tokens) {
	JSDOCTokenStream * self = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (tokens != NULL, NULL);
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self = (JSDOCTokenStream*) g_object_new (object_type, NULL);
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = tokens;
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (self->tokens);
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self->tokens = _tmp1_;
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	jsdoc_token_stream_rewind (self);
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return self;
#line 288 "TokenStream.c"
}


JSDOCTokenStream* jsdoc_token_stream_new (GeeArrayList* tokens) {
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return jsdoc_token_stream_construct (JSDOC_TYPE_TOKEN_STREAM, tokens);
#line 295 "TokenStream.c"
}


GeeArrayList* jsdoc_token_stream_toArray (JSDOCTokenStream* self) {
	GeeArrayList* result = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 31 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = self->tokens;
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = _tmp1_;
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 313 "TokenStream.c"
}


void jsdoc_token_stream_rewind (JSDOCTokenStream* self) {
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (self != NULL);
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self->cursor = -1;
#line 322 "TokenStream.c"
}


/**
    @type JSDOC.Token
*/
JSDOCToken* jsdoc_token_stream_look (JSDOCTokenStream* self, gint n, gboolean considerWhitespace) {
	JSDOCToken* result = NULL;
	gboolean _tmp0_;
	gint count = 0;
	gint i = 0;
	gint _tmp14_;
#line 44 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = considerWhitespace;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp0_ == TRUE) {
#line 341 "TokenStream.c"
		gboolean _tmp1_ = FALSE;
		gint _tmp2_;
		gint _tmp3_;
		GeeArrayList* _tmp10_;
		gint _tmp11_;
		gint _tmp12_;
		gpointer _tmp13_;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp2_ = self->cursor;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp3_ = n;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if ((_tmp2_ + _tmp3_) < 0) {
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp1_ = TRUE;
#line 357 "TokenStream.c"
		} else {
			gint _tmp4_;
			gint _tmp5_;
			GeeArrayList* _tmp6_;
			gint _tmp7_;
			gint _tmp8_;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp4_ = self->cursor;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp5_ = n;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp6_ = self->tokens;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp7_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp6_);
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp8_ = _tmp7_;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp1_ = (_tmp4_ + _tmp5_) > (_tmp8_ - 1);
#line 376 "TokenStream.c"
		}
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp1_) {
#line 380 "TokenStream.c"
			JSDOCToken* _tmp9_;
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp9_ = jsdoc_token_new ("", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_START_OF_STREAM, -1);
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = _tmp9_;
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 388 "TokenStream.c"
		}
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp10_ = self->tokens;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp11_ = self->cursor;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp12_ = n;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp13_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_ + _tmp12_);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		result = (JSDOCToken*) _tmp13_;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return result;
#line 402 "TokenStream.c"
	}
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	count = 0;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp14_ = self->cursor;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	i = _tmp14_;
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 412 "TokenStream.c"
		gint _tmp15_;
		gint _tmp17_;
		GeeArrayList* _tmp18_;
		gint _tmp19_;
		gint _tmp20_;
		gboolean _tmp22_ = FALSE;
		gint _tmp23_;
		gint _tmp24_;
		gint _tmp33_;
		gint _tmp34_;
		gint _tmp38_;
		gint _tmp39_ = 0;
		gint _tmp40_;
		gint _tmp41_;
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp15_ = i;
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp15_ < 0) {
#line 431 "TokenStream.c"
			JSDOCToken* _tmp16_;
#line 62 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp16_ = jsdoc_token_new ("", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_START_OF_STREAM, -1);
#line 62 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = _tmp16_;
#line 62 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 439 "TokenStream.c"
		}
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp17_ = i;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp18_ = self->tokens;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp19_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp18_);
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp20_ = _tmp19_;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp17_ >= _tmp20_) {
#line 451 "TokenStream.c"
			JSDOCToken* _tmp21_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp21_ = jsdoc_token_new ("", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_END_OF_STREAM, -1);
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = _tmp21_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 459 "TokenStream.c"
		}
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp23_ = i;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp24_ = self->cursor;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp23_ != _tmp24_) {
#line 467 "TokenStream.c"
			GeeArrayList* _tmp25_;
			gint _tmp26_;
			gpointer _tmp27_;
			JSDOCToken* _tmp28_;
			gboolean _tmp29_;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp25_ = self->tokens;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp26_ = i;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp27_ = gee_abstract_list_get ((GeeAbstractList*) _tmp25_, _tmp26_);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp28_ = (JSDOCToken*) _tmp27_;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp29_ = jsdoc_token_isType (_tmp28_, JSDOC_TOKEN_TYPE_WHIT);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp22_ = _tmp29_;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (_tmp28_);
#line 487 "TokenStream.c"
		} else {
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp22_ = FALSE;
#line 491 "TokenStream.c"
		}
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp22_) {
#line 495 "TokenStream.c"
			gint _tmp30_ = 0;
			gint _tmp31_;
			gint _tmp32_;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp31_ = n;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			if (_tmp31_ < 0) {
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp30_ = -1;
#line 505 "TokenStream.c"
			} else {
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp30_ = 1;
#line 509 "TokenStream.c"
			}
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp32_ = i;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			i = _tmp32_ + _tmp30_;
#line 70 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			continue;
#line 517 "TokenStream.c"
		}
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp33_ = count;
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp34_ = n;
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp33_ == _tmp34_) {
#line 525 "TokenStream.c"
			GeeArrayList* _tmp35_;
			gint _tmp36_;
			gpointer _tmp37_;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp35_ = self->tokens;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp36_ = i;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp37_ = gee_abstract_list_get ((GeeAbstractList*) _tmp35_, _tmp36_);
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = (JSDOCToken*) _tmp37_;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 539 "TokenStream.c"
		}
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp38_ = count;
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		count = _tmp38_ + 1;
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp40_ = n;
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp40_ < 0) {
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp39_ = -1;
#line 551 "TokenStream.c"
		} else {
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp39_ = 1;
#line 555 "TokenStream.c"
		}
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp41_ = i;
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = _tmp41_ + _tmp39_;
#line 561 "TokenStream.c"
	}
}


JSDOCToken* jsdoc_token_stream_lookAny (JSDOCTokenStream* self, gint n) {
	JSDOCToken* result = NULL;
	gboolean _tmp0_ = FALSE;
	gint _tmp1_;
	gint _tmp2_;
	GeeArrayList* _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	gpointer _tmp12_;
#line 84 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = self->cursor;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = n;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if ((_tmp1_ + _tmp2_) < 0) {
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = TRUE;
#line 585 "TokenStream.c"
	} else {
		gint _tmp3_;
		gint _tmp4_;
		GeeArrayList* _tmp5_;
		gint _tmp6_;
		gint _tmp7_;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp3_ = self->cursor;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = n;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp5_ = self->tokens;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp6_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp5_);
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp7_ = _tmp6_;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = (_tmp3_ + _tmp4_) > (_tmp7_ - 1);
#line 604 "TokenStream.c"
	}
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp0_) {
#line 608 "TokenStream.c"
		JSDOCToken* _tmp8_;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp8_ = jsdoc_token_new ("", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_START_OF_STREAM, -1);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		result = _tmp8_;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return result;
#line 616 "TokenStream.c"
	}
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp9_ = self->tokens;
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp10_ = self->cursor;
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp11_ = n;
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_ + _tmp11_);
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = (JSDOCToken*) _tmp12_;
#line 91 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 630 "TokenStream.c"
}


gint jsdoc_token_stream_lookFor (JSDOCTokenStream* self, const gchar* data) {
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_;
	gint i = 0;
#line 99 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 99 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (data != NULL, 0);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = self->cursor;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp1_ < 0) {
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = 0;
#line 649 "TokenStream.c"
	} else {
		gint _tmp2_;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp2_ = self->cursor;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = _tmp2_;
#line 656 "TokenStream.c"
	}
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	i = _tmp0_;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 662 "TokenStream.c"
		gint _tmp3_;
		GeeArrayList* _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		GeeArrayList* _tmp7_;
		gint _tmp8_;
		gpointer _tmp9_;
		JSDOCToken* _tmp10_;
		const gchar* _tmp11_;
		const gchar* _tmp12_;
		gboolean _tmp13_;
		gint _tmp14_;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp3_ = i;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = self->tokens;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp5_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp4_);
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp6_ = _tmp5_;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp3_ >= _tmp6_) {
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = -1;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 689 "TokenStream.c"
		}
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp7_ = self->tokens;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp8_ = i;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp9_ = gee_abstract_list_get ((GeeAbstractList*) _tmp7_, _tmp8_);
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp10_ = (JSDOCToken*) _tmp9_;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp11_ = _tmp10_->data;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp12_ = data;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp13_ = g_strcmp0 (_tmp11_, _tmp12_) == 0;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (_tmp10_);
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp13_) {
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = i;
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 713 "TokenStream.c"
		}
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp14_ = i;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = _tmp14_ + 1;
#line 719 "TokenStream.c"
	}
}


/**
 * look ahead (or back) x number of tokens (which are not comment or whitespace)
 * ?? used by scope parser & compress white to look back?
 */
JSDOCToken* jsdoc_token_stream_lookTok (JSDOCTokenStream* self, gint n) {
	JSDOCToken* result = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_;
	gint step = 0;
	gint count = 0;
	gint i = 0;
	gint _tmp2_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = n;
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp1_ < 0) {
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = -1;
#line 744 "TokenStream.c"
	} else {
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = 1;
#line 748 "TokenStream.c"
	}
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	step = _tmp0_;
#line 128 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	count = 0;
#line 130 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = self->cursor;
#line 130 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	i = _tmp2_;
#line 132 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 760 "TokenStream.c"
		gboolean _tmp3_ = FALSE;
		gint _tmp4_;
		gboolean _tmp8_ = FALSE;
		gint _tmp9_;
		gint _tmp12_;
		GeeArrayList* _tmp13_;
		gint _tmp14_;
		gint _tmp15_;
		JSDOCToken* tok = NULL;
		GeeArrayList* _tmp17_;
		gint _tmp18_;
		gpointer _tmp19_;
		gboolean _tmp20_ = FALSE;
		gint _tmp21_;
		gint _tmp22_;
		gint _tmp30_;
		gint _tmp31_;
		gint _tmp35_;
		gint _tmp36_;
		gint _tmp37_;
		gint _tmp38_;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = i;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp4_ < 0) {
#line 786 "TokenStream.c"
			gint _tmp5_;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp5_ = n;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp3_ = _tmp5_ > -1;
#line 792 "TokenStream.c"
		} else {
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp3_ = FALSE;
#line 796 "TokenStream.c"
		}
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp3_) {
#line 800 "TokenStream.c"
			gint _tmp6_;
			gint _tmp7_;
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			i = 0;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp6_ = count;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp7_ = step;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			count = _tmp6_ + _tmp7_;
#line 138 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			continue;
#line 813 "TokenStream.c"
		}
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp9_ = i;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp9_ < 0) {
#line 819 "TokenStream.c"
			gint _tmp10_;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp10_ = n;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp8_ = _tmp10_ < 0;
#line 825 "TokenStream.c"
		} else {
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp8_ = FALSE;
#line 829 "TokenStream.c"
		}
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp8_) {
#line 833 "TokenStream.c"
			JSDOCToken* _tmp11_;
#line 144 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp11_ = jsdoc_token_new ("BEG", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_END_OF_STREAM, -1);
#line 144 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = _tmp11_;
#line 144 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 841 "TokenStream.c"
		}
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp12_ = i;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp13_ = self->tokens;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp14_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp13_);
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp15_ = _tmp14_;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp12_ >= _tmp15_) {
#line 853 "TokenStream.c"
			JSDOCToken* _tmp16_;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp16_ = jsdoc_token_new ("END", JSDOC_TOKEN_TYPE_VOID, JSDOC_TOKEN_NAME_END_OF_STREAM, -1);
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = _tmp16_;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 861 "TokenStream.c"
		}
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp17_ = self->tokens;
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp18_ = i;
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
#line 153 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		tok = (JSDOCToken*) _tmp19_;
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp21_ = i;
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp22_ = self->cursor;
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp21_ != _tmp22_) {
#line 877 "TokenStream.c"
			gboolean _tmp23_ = FALSE;
			JSDOCToken* _tmp24_;
			gboolean _tmp25_;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp24_ = tok;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp25_ = jsdoc_token_isType (_tmp24_, JSDOC_TOKEN_TYPE_WHIT);
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			if (_tmp25_) {
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp23_ = TRUE;
#line 889 "TokenStream.c"
			} else {
				JSDOCToken* _tmp26_;
				gboolean _tmp27_;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp26_ = tok;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp27_ = jsdoc_token_isType (_tmp26_, JSDOC_TOKEN_TYPE_COMM);
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp23_ = _tmp27_;
#line 899 "TokenStream.c"
			}
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp20_ = _tmp23_;
#line 903 "TokenStream.c"
		} else {
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp20_ = FALSE;
#line 907 "TokenStream.c"
		}
#line 155 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp20_) {
#line 911 "TokenStream.c"
			gint _tmp28_;
			gint _tmp29_;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp28_ = i;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp29_ = step;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			i = _tmp28_ + _tmp29_;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (tok);
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			continue;
#line 924 "TokenStream.c"
		}
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp30_ = count;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp31_ = n;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp30_ == _tmp31_) {
#line 932 "TokenStream.c"
			GeeArrayList* _tmp32_;
			gint _tmp33_;
			gpointer _tmp34_;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp32_ = self->tokens;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp33_ = i;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp34_ = gee_abstract_list_get ((GeeAbstractList*) _tmp32_, _tmp33_);
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = (JSDOCToken*) _tmp34_;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (tok);
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 948 "TokenStream.c"
		}
#line 165 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp35_ = count;
#line 165 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp36_ = step;
#line 165 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		count = _tmp35_ + _tmp36_;
#line 166 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp37_ = i;
#line 166 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp38_ = step;
#line 166 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = _tmp37_ + _tmp38_;
#line 132 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (tok);
#line 964 "TokenStream.c"
	}
}


/**
 *  @return {Token|null}
 * next token (with white space)
 */
JSDOCToken* jsdoc_token_stream_next (JSDOCTokenStream* self) {
	JSDOCToken* result = NULL;
	gint _tmp0_;
	GeeArrayList* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	GeeArrayList* _tmp5_;
	gint _tmp6_;
	gpointer _tmp7_;
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = self->cursor;
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = self->tokens;
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp1_);
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = _tmp2_;
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if ((_tmp0_ + 1) >= _tmp3_) {
#line 186 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		result = NULL;
#line 186 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return result;
#line 999 "TokenStream.c"
	}
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp4_ = self->cursor;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self->cursor = _tmp4_ + 1;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp5_ = self->tokens;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp6_ = self->cursor;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp7_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, _tmp6_);
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = (JSDOCToken*) _tmp7_;
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1015 "TokenStream.c"
}


GeeArrayList* jsdoc_token_stream_nextM (JSDOCTokenStream* self, gint howMany, GError** error) {
	GeeArrayList* result = NULL;
	gint _tmp0_;
	GeeArrayList* got = NULL;
	GeeArrayList* _tmp3_;
	gint _tmp19_;
	gint _tmp20_;
	GError * _inner_error_ = NULL;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = howMany;
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp0_ < 2) {
#line 1033 "TokenStream.c"
		gint _tmp1_;
		GError* _tmp2_;
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp1_ = howMany;
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp2_ = g_error_new (JSDOC_TOKEN_STREAM_ERROR, JSDOC_TOKEN_STREAM_ERROR_ArgumentError, "nextM called with wrong number : %d", _tmp1_);
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_inner_error_ = _tmp2_;
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_inner_error_->domain == JSDOC_TOKEN_STREAM_ERROR) {
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_propagate_error (error, _inner_error_);
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1048 "TokenStream.c"
		} else {
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_clear_error (&_inner_error_);
#line 197 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1056 "TokenStream.c"
		}
	}
#line 199 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 199 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	got = _tmp3_;
#line 1063 "TokenStream.c"
	{
		gint i = 0;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = 1;
#line 1068 "TokenStream.c"
		{
			gboolean _tmp4_ = FALSE;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp4_ = TRUE;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			while (TRUE) {
#line 1075 "TokenStream.c"
				gint _tmp6_;
				gint _tmp7_;
				gint _tmp8_;
				gint _tmp9_;
				GeeArrayList* _tmp10_;
				gint _tmp11_;
				gint _tmp12_;
				GeeArrayList* _tmp13_;
				GeeArrayList* _tmp14_;
				gint _tmp15_;
				gint _tmp16_;
				gpointer _tmp17_;
				JSDOCToken* _tmp18_;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!_tmp4_) {
#line 1091 "TokenStream.c"
					gint _tmp5_;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp5_ = i;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					i = _tmp5_ + 1;
#line 1097 "TokenStream.c"
				}
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp4_ = FALSE;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp6_ = i;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp7_ = howMany;
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!(_tmp6_ <= _tmp7_)) {
#line 201 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					break;
#line 1109 "TokenStream.c"
				}
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp8_ = self->cursor;
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp9_ = i;
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp10_ = self->tokens;
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp11_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp10_);
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp12_ = _tmp11_;
#line 202 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if ((_tmp8_ + _tmp9_) >= _tmp12_) {
#line 203 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					result = NULL;
#line 203 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_g_object_unref0 (got);
#line 203 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					return result;
#line 1129 "TokenStream.c"
				}
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp13_ = got;
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp14_ = self->tokens;
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp15_ = self->cursor;
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp16_ = i;
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp17_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp15_ + _tmp16_);
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp18_ = (JSDOCToken*) _tmp17_;
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp13_, _tmp18_);
#line 205 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp18_);
#line 1147 "TokenStream.c"
			}
		}
	}
#line 207 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp19_ = self->cursor;
#line 207 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp20_ = howMany;
#line 207 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self->cursor = _tmp19_ + _tmp20_;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = got;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1161 "TokenStream.c"
}


JSDOCToken* jsdoc_token_stream_nextTok (JSDOCTokenStream* self) {
	JSDOCToken* result = NULL;
	JSDOCToken* _tmp0_;
#line 217 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 218 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = jsdoc_token_stream_nextNonSpace (self);
#line 218 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = _tmp0_;
#line 218 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1176 "TokenStream.c"
}


JSDOCToken* jsdoc_token_stream_nextNonSpace (JSDOCTokenStream* self) {
	JSDOCToken* result = NULL;
#line 221 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 224 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 1186 "TokenStream.c"
		JSDOCToken* tok = NULL;
		JSDOCToken* _tmp0_;
		JSDOCToken* _tmp1_;
		gboolean _tmp2_ = FALSE;
		JSDOCToken* _tmp3_;
		gboolean _tmp4_;
#line 225 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = jsdoc_token_stream_next (self);
#line 225 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		tok = _tmp0_;
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp1_ = tok;
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp1_ == NULL) {
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = NULL;
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (tok);
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 1207 "TokenStream.c"
		}
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp3_ = tok;
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = jsdoc_token_isType (_tmp3_, JSDOC_TOKEN_TYPE_WHIT);
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp4_) {
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp2_ = TRUE;
#line 1217 "TokenStream.c"
		} else {
			JSDOCToken* _tmp5_;
			gboolean _tmp6_;
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp5_ = tok;
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp6_ = jsdoc_token_isType (_tmp5_, JSDOC_TOKEN_TYPE_COMM);
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp2_ = _tmp6_;
#line 1227 "TokenStream.c"
		}
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp2_) {
#line 230 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (tok);
#line 230 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			continue;
#line 1235 "TokenStream.c"
		}
#line 232 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		result = tok;
#line 232 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return result;
#line 1241 "TokenStream.c"
	}
}


/**
 *  balance 
 * -- returns all the tokens betweeen and including stop token eg.. from {... to  }
 * @param start {String}  token name or data (eg. '{'
 * @param stop {String} (Optional) token name or data (eg. '}'
 */
GeeArrayList* jsdoc_token_stream_balance (JSDOCTokenStream* self, JSDOCTokenName in_start, GError** error) {
	GeeArrayList* result = NULL;
	JSDOCTokenName start = 0;
	JSDOCTokenName _tmp0_;
	JSDOCTokenName* stop = NULL;
	JSDOCLang_Class* _tmp1_;
	JSDOCTokenName _tmp2_;
	JSDOCTokenName* _tmp3_;
	JSDOCTokenName* _tmp4_;
	gint depth = 0;
	GeeArrayList* got = NULL;
	GeeArrayList* _tmp8_;
	gboolean started = FALSE;
	JSDOCToken* token = NULL;
	GeeArrayList* _tmp28_;
	GError * _inner_error_ = NULL;
#line 250 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 257 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = in_start;
#line 257 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	start = _tmp0_;
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = jsdoc_Lang;
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = start;
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = jsdoc_langclass_matching (_tmp1_, _tmp2_, &_inner_error_);
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	stop = _tmp3_;
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_inner_error_->domain == JSDOC_TOKEN_STREAM_ERROR) {
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_propagate_error (error, _inner_error_);
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1290 "TokenStream.c"
		} else {
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_clear_error (&_inner_error_);
#line 258 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1298 "TokenStream.c"
		}
	}
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp4_ = stop;
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (_tmp4_ == NULL) {
#line 1305 "TokenStream.c"
		JSDOCTokenName _tmp5_;
		GEnumValue* _tmp6_;
		GError* _tmp7_;
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp5_ = start;
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp6_ = g_enum_get_value (g_type_class_ref (JSDOC_TYPE_TOKEN_NAME), _tmp5_);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp7_ = g_error_new (JSDOC_TOKEN_STREAM_ERROR, JSDOC_TOKEN_STREAM_ERROR_ArgumentError, "balance called with invalid start/stop : %s", (_tmp6_ != NULL) ? _tmp6_->value_name : NULL);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_inner_error_ = _tmp7_;
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_inner_error_->domain == JSDOC_TOKEN_STREAM_ERROR) {
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_propagate_error (error, _inner_error_);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_free0 (stop);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1325 "TokenStream.c"
		} else {
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_free0 (stop);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			g_clear_error (&_inner_error_);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return NULL;
#line 1335 "TokenStream.c"
		}
	}
#line 264 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	depth = 0;
#line 265 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp8_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 265 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	got = _tmp8_;
#line 266 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	started = FALSE;
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 1348 "TokenStream.c"
		JSDOCToken* _tmp9_;
		JSDOCToken* _tmp10_;
		JSDOCToken* _tmp11_;
		JSDOCTokenName _tmp12_;
		gboolean _tmp13_;
		gboolean _tmp15_;
		JSDOCToken* _tmp18_;
		JSDOCTokenName* _tmp19_;
		gboolean _tmp20_;
		JSDOCToken* _tmp25_;
		JSDOCToken* _tmp26_;
		gboolean _tmp27_;
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp9_ = jsdoc_token_stream_lookAny (self, 1);
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (token);
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		token = _tmp9_;
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp10_ = token;
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (!(NULL != _tmp10_)) {
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			break;
#line 1373 "TokenStream.c"
		}
#line 273 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp11_ = token;
#line 273 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp12_ = start;
#line 273 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp13_ = jsdoc_token_isName (_tmp11_, _tmp12_);
#line 273 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp13_) {
#line 1383 "TokenStream.c"
			gint _tmp14_;
#line 275 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp14_ = depth;
#line 275 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			depth = _tmp14_ + 1;
#line 276 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			started = TRUE;
#line 1391 "TokenStream.c"
		}
#line 279 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp15_ = started;
#line 279 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp15_) {
#line 1397 "TokenStream.c"
			GeeArrayList* _tmp16_;
			JSDOCToken* _tmp17_;
#line 280 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp16_ = got;
#line 280 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp17_ = token;
#line 280 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			gee_abstract_collection_add ((GeeAbstractCollection*) _tmp16_, _tmp17_);
#line 1406 "TokenStream.c"
		}
#line 283 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp18_ = token;
#line 283 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp19_ = stop;
#line 283 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp20_ = jsdoc_token_isName (_tmp18_, *_tmp19_);
#line 283 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp20_) {
#line 1416 "TokenStream.c"
			gint _tmp21_;
			gint _tmp22_;
#line 284 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp21_ = depth;
#line 284 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			depth = _tmp21_ - 1;
#line 287 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp22_ = depth;
#line 287 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			if (_tmp22_ < 1) {
#line 1427 "TokenStream.c"
				JSDOCToken* _tmp23_;
				JSDOCToken* _tmp24_;
#line 288 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp23_ = jsdoc_token_stream_next (self);
#line 288 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp24_ = _tmp23_;
#line 288 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp24_);
#line 290 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				result = got;
#line 290 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (token);
#line 290 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_free0 (stop);
#line 290 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				return result;
#line 1444 "TokenStream.c"
			}
		}
#line 294 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp25_ = jsdoc_token_stream_next (self);
#line 294 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp26_ = _tmp25_;
#line 294 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp27_ = NULL == _tmp26_;
#line 294 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (_tmp26_);
#line 294 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp27_) {
#line 295 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			break;
#line 1459 "TokenStream.c"
		}
	}
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp28_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = _tmp28_;
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (token);
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (got);
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_free0 (stop);
#line 298 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1474 "TokenStream.c"
}


JSDOCToken* jsdoc_token_stream_getMatchingTokenEnd (JSDOCTokenStream* self, JSDOCTokenName end) {
	JSDOCToken* result = NULL;
	JSDOCTokenName* _tmp0_ = NULL;
	JSDOCLang_Class* _tmp1_;
	JSDOCTokenName _tmp2_;
	JSDOCTokenName* _tmp3_;
	JSDOCToken* _tmp4_;
	GError * _inner_error_ = NULL;
#line 303 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = jsdoc_Lang;
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = end;
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = jsdoc_langclass_matching (_tmp1_, _tmp2_, &_inner_error_);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = _tmp3_;
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		g_clear_error (&_inner_error_);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return NULL;
#line 1504 "TokenStream.c"
	}
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp4_ = jsdoc_token_stream_getMatchingToken (self, *_tmp0_, 1);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = _tmp4_;
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_free0 (_tmp0_);
#line 305 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1514 "TokenStream.c"
}


JSDOCToken* jsdoc_token_stream_getMatchingToken (JSDOCTokenStream* self, JSDOCTokenName start, gint depth) {
	JSDOCToken* result = NULL;
	gint cursor = 0;
	gint _tmp0_;
	JSDOCTokenName* stop = NULL;
	JSDOCLang_Class* _tmp1_;
	JSDOCTokenName _tmp2_;
	JSDOCTokenName* _tmp3_;
	JSDOCToken* token = NULL;
	GError * _inner_error_ = NULL;
#line 308 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 311 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = self->cursor;
#line 311 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	cursor = _tmp0_;
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = jsdoc_Lang;
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = start;
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = jsdoc_langclass_matching (_tmp1_, _tmp2_, &_inner_error_);
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	stop = _tmp3_;
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		g_clear_error (&_inner_error_);
#line 314 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		return NULL;
#line 1550 "TokenStream.c"
	}
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 1554 "TokenStream.c"
		GeeArrayList* _tmp4_;
		gint _tmp5_;
		gpointer _tmp6_;
		JSDOCToken* _tmp7_;
		JSDOCToken* _tmp8_;
		JSDOCTokenName _tmp9_;
		gboolean _tmp10_;
		gboolean _tmp12_ = FALSE;
		JSDOCToken* _tmp13_;
		JSDOCTokenName* _tmp14_;
		gboolean _tmp15_;
		gint _tmp22_;
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = self->tokens;
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp5_ = cursor;
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp6_ = gee_abstract_list_get ((GeeAbstractList*) _tmp4_, _tmp5_);
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (token);
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		token = (JSDOCToken*) _tmp6_;
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp7_ = token;
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (!(NULL != _tmp7_)) {
#line 317 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			break;
#line 1583 "TokenStream.c"
		}
#line 318 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp8_ = token;
#line 318 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp9_ = start;
#line 318 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp10_ = jsdoc_token_isName (_tmp8_, _tmp9_);
#line 318 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp10_) {
#line 1593 "TokenStream.c"
			gint _tmp11_;
#line 319 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp11_ = depth;
#line 319 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			depth = _tmp11_ + 1;
#line 1599 "TokenStream.c"
		}
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp13_ = token;
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp14_ = stop;
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp15_ = jsdoc_token_isName (_tmp13_, *_tmp14_);
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp15_) {
#line 1609 "TokenStream.c"
			gint _tmp16_;
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp16_ = cursor;
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp12_ = _tmp16_ != 0;
#line 1615 "TokenStream.c"
		} else {
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp12_ = FALSE;
#line 1619 "TokenStream.c"
		}
#line 322 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp12_) {
#line 1623 "TokenStream.c"
			gint _tmp17_;
			gint _tmp18_;
#line 323 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp17_ = depth;
#line 323 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			depth = _tmp17_ - 1;
#line 324 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp18_ = depth;
#line 324 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			if (_tmp18_ == 0) {
#line 1634 "TokenStream.c"
				GeeArrayList* _tmp19_;
				gint _tmp20_;
				gpointer _tmp21_;
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp19_ = self->tokens;
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp20_ = cursor;
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp21_ = gee_abstract_list_get ((GeeAbstractList*) _tmp19_, _tmp20_);
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				result = (JSDOCToken*) _tmp21_;
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (token);
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_free0 (stop);
#line 325 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				return result;
#line 1652 "TokenStream.c"
			}
		}
#line 328 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp22_ = cursor;
#line 328 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		cursor = _tmp22_ + 1;
#line 1659 "TokenStream.c"
	}
#line 330 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	result = NULL;
#line 330 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (token);
#line 330 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_free0 (stop);
#line 330 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	return result;
#line 1669 "TokenStream.c"
}


GeeArrayList* jsdoc_token_stream_remaining (JSDOCTokenStream* self) {
	GeeArrayList* result = NULL;
	GeeArrayList* ret = NULL;
	GeeArrayList* _tmp0_;
#line 339 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 340 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
#line 340 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	ret = _tmp0_;
#line 341 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	while (TRUE) {
#line 1685 "TokenStream.c"
		JSDOCToken* tok = NULL;
		JSDOCToken* _tmp1_;
		JSDOCToken* _tmp2_;
		gboolean _tmp3_;
		JSDOCToken* nt = NULL;
		JSDOCToken* _tmp4_;
		JSDOCToken* _tmp5_;
#line 342 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp1_ = jsdoc_token_stream_look (self, 1, TRUE);
#line 342 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		tok = _tmp1_;
#line 343 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp2_ = tok;
#line 343 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp3_ = jsdoc_token_isType (_tmp2_, JSDOC_TOKEN_TYPE_VOID);
#line 343 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp3_) {
#line 344 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			result = ret;
#line 344 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_g_object_unref0 (tok);
#line 344 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			return result;
#line 1709 "TokenStream.c"
		}
#line 346 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp4_ = jsdoc_token_stream_next (self);
#line 346 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		nt = _tmp4_;
#line 347 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp5_ = nt;
#line 347 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		if (_tmp5_ != NULL) {
#line 1719 "TokenStream.c"
			GeeArrayList* _tmp6_;
			JSDOCToken* _tmp7_;
#line 348 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp6_ = ret;
#line 348 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp7_ = nt;
#line 348 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			gee_abstract_collection_add ((GeeAbstractCollection*) _tmp6_, _tmp7_);
#line 1728 "TokenStream.c"
		}
#line 341 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (nt);
#line 341 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_g_object_unref0 (tok);
#line 1734 "TokenStream.c"
	}
#line 339 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (ret);
#line 1738 "TokenStream.c"
}


void jsdoc_token_stream_printRange (JSDOCTokenStream* self, gint start, gint end) {
#line 354 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (self != NULL);
#line 1745 "TokenStream.c"
	{
		gint i = 0;
		gint _tmp0_;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp0_ = start;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = _tmp0_;
#line 1753 "TokenStream.c"
		{
			gboolean _tmp1_ = FALSE;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp1_ = TRUE;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			while (TRUE) {
#line 1760 "TokenStream.c"
				gint _tmp3_;
				gint _tmp4_;
				GeeArrayList* _tmp5_;
				gint _tmp6_;
				gpointer _tmp7_;
				JSDOCToken* _tmp8_;
				gchar* _tmp9_;
				gchar* _tmp10_;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!_tmp1_) {
#line 1771 "TokenStream.c"
					gint _tmp2_;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp2_ = i;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					i = _tmp2_ + 1;
#line 1777 "TokenStream.c"
				}
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp1_ = FALSE;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp3_ = i;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp4_ = end;
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!(_tmp3_ < (_tmp4_ + 1))) {
#line 356 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					break;
#line 1789 "TokenStream.c"
				}
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp5_ = self->tokens;
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp6_ = i;
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp7_ = gee_abstract_list_get ((GeeAbstractList*) _tmp5_, _tmp6_);
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp8_ = (JSDOCToken*) _tmp7_;
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp9_ = jsdoc_token_asString (_tmp8_);
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp10_ = _tmp9_;
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				g_print ("%s", _tmp10_);
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_free0 (_tmp10_);
#line 357 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp8_);
#line 1809 "TokenStream.c"
			}
		}
	}
}


void jsdoc_token_stream_dump (JSDOCTokenStream* self, gint start, gint end) {
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	GeeArrayList* _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gchar* outs = NULL;
	gchar* _tmp7_;
	const gchar* _tmp32_;
#line 371 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (self != NULL);
#line 373 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp0_ = start;
#line 373 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp1_ = MAX (_tmp0_, 0);
#line 373 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	start = _tmp1_;
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp2_ = end;
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp3_ = self->tokens;
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp5_ = _tmp4_;
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp6_ = MIN (_tmp2_, _tmp5_);
#line 374 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	end = _tmp6_;
#line 375 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp7_ = g_strdup ("");
#line 375 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	outs = _tmp7_;
#line 1851 "TokenStream.c"
	{
		gint i = 0;
		gint _tmp8_;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		_tmp8_ = start;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = _tmp8_;
#line 1859 "TokenStream.c"
		{
			gboolean _tmp9_ = FALSE;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp9_ = TRUE;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			while (TRUE) {
#line 1866 "TokenStream.c"
				gint _tmp11_;
				gint _tmp12_;
				const gchar* _tmp13_ = NULL;
				GeeArrayList* _tmp14_;
				gint _tmp15_;
				gpointer _tmp16_;
				JSDOCToken* _tmp17_;
				const gchar* _tmp18_;
				gboolean _tmp19_;
				const gchar* _tmp30_;
				gchar* _tmp31_;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!_tmp9_) {
#line 1880 "TokenStream.c"
					gint _tmp10_;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp10_ = i;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					i = _tmp10_ + 1;
#line 1886 "TokenStream.c"
				}
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp9_ = FALSE;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp11_ = i;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp12_ = end;
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!(_tmp11_ < _tmp12_)) {
#line 376 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					break;
#line 1898 "TokenStream.c"
				}
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp14_ = self->tokens;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp15_ = i;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp14_, _tmp15_);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp17_ = (JSDOCToken*) _tmp16_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp18_ = _tmp17_->outData;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp19_ = g_strcmp0 (_tmp18_, "") == 0;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp17_);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (_tmp19_) {
#line 1916 "TokenStream.c"
					GeeArrayList* _tmp20_;
					gint _tmp21_;
					gpointer _tmp22_;
					JSDOCToken* _tmp23_;
					const gchar* _tmp24_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp20_ = self->tokens;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp21_ = i;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp22_ = gee_abstract_list_get ((GeeAbstractList*) _tmp20_, _tmp21_);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp23_ = (JSDOCToken*) _tmp22_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp24_ = _tmp23_->data;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp13_ = _tmp24_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_g_object_unref0 (_tmp23_);
#line 1936 "TokenStream.c"
				} else {
					GeeArrayList* _tmp25_;
					gint _tmp26_;
					gpointer _tmp27_;
					JSDOCToken* _tmp28_;
					const gchar* _tmp29_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp25_ = self->tokens;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp26_ = i;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp27_ = gee_abstract_list_get ((GeeAbstractList*) _tmp25_, _tmp26_);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp28_ = (JSDOCToken*) _tmp27_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp29_ = _tmp28_->outData;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp13_ = _tmp29_;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_g_object_unref0 (_tmp28_);
#line 1957 "TokenStream.c"
				}
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp30_ = outs;
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp31_ = g_strconcat (_tmp30_, _tmp13_, NULL);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_free0 (outs);
#line 378 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				outs = _tmp31_;
#line 1967 "TokenStream.c"
			}
		}
	}
#line 380 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_tmp32_ = outs;
#line 380 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_print ("%s", _tmp32_);
#line 371 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_free0 (outs);
#line 1977 "TokenStream.c"
}


void jsdoc_token_stream_dumpAll (JSDOCTokenStream* self, const gchar* indent) {
#line 383 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (self != NULL);
#line 383 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (indent != NULL);
#line 1986 "TokenStream.c"
	{
		gint i = 0;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = 0;
#line 1991 "TokenStream.c"
		{
			gboolean _tmp0_ = FALSE;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp0_ = TRUE;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			while (TRUE) {
#line 1998 "TokenStream.c"
				gint _tmp2_;
				GeeArrayList* _tmp3_;
				gint _tmp4_;
				gint _tmp5_;
				GeeArrayList* _tmp6_;
				gint _tmp7_;
				gpointer _tmp8_;
				JSDOCToken* _tmp9_;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!_tmp0_) {
#line 2009 "TokenStream.c"
					gint _tmp1_;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp1_ = i;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					i = _tmp1_ + 1;
#line 2015 "TokenStream.c"
				}
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp0_ = FALSE;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp2_ = i;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp3_ = self->tokens;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp5_ = _tmp4_;
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!(_tmp2_ < _tmp5_)) {
#line 385 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					break;
#line 2031 "TokenStream.c"
				}
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp6_ = self->tokens;
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp7_ = i;
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp8_ = gee_abstract_list_get ((GeeAbstractList*) _tmp6_, _tmp7_);
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp9_ = (JSDOCToken*) _tmp8_;
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				jsdoc_token_dump (_tmp9_, "");
#line 387 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp9_);
#line 2045 "TokenStream.c"
			}
		}
	}
}


void jsdoc_token_stream_dumpAllFlat (JSDOCTokenStream* self) {
#line 391 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	g_return_if_fail (self != NULL);
#line 2055 "TokenStream.c"
	{
		gint i = 0;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
		i = 0;
#line 2060 "TokenStream.c"
		{
			gboolean _tmp0_ = FALSE;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			_tmp0_ = TRUE;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
			while (TRUE) {
#line 2067 "TokenStream.c"
				gint _tmp2_;
				GeeArrayList* _tmp3_;
				gint _tmp4_;
				gint _tmp5_;
				gint _tmp6_;
				GeeArrayList* _tmp7_;
				gint _tmp8_;
				gpointer _tmp9_;
				JSDOCToken* _tmp10_;
				gchar* _tmp11_;
				gchar* _tmp12_;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!_tmp0_) {
#line 2081 "TokenStream.c"
					gint _tmp1_;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					_tmp1_ = i;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					i = _tmp1_ + 1;
#line 2087 "TokenStream.c"
				}
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp0_ = FALSE;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp2_ = i;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp3_ = self->tokens;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp4_ = gee_abstract_collection_get_size ((GeeAbstractCollection*) _tmp3_);
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp5_ = _tmp4_;
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				if (!(_tmp2_ < _tmp5_)) {
#line 393 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
					break;
#line 2103 "TokenStream.c"
				}
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp6_ = i;
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp7_ = self->tokens;
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp8_ = i;
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp9_ = gee_abstract_list_get ((GeeAbstractList*) _tmp7_, _tmp8_);
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp10_ = (JSDOCToken*) _tmp9_;
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp11_ = jsdoc_token_asString (_tmp10_);
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_tmp12_ = _tmp11_;
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				g_print ("%d: %s\n", _tmp6_, _tmp12_);
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_free0 (_tmp12_);
#line 395 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
				_g_object_unref0 (_tmp10_);
#line 2125 "TokenStream.c"
			}
		}
	}
}


static void jsdoc_token_stream_class_init (JSDOCTokenStreamClass * klass) {
#line 18 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	jsdoc_token_stream_parent_class = g_type_class_peek_parent (klass);
#line 18 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_token_stream_finalize;
#line 2137 "TokenStream.c"
}


static void jsdoc_token_stream_instance_init (JSDOCTokenStream * self) {
}


static void jsdoc_token_stream_finalize (GObject * obj) {
	JSDOCTokenStream * self;
#line 18 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStream);
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	_g_object_unref0 (self->tokens);
#line 18 "/home/alan/gitlive/roojspacker/src/jsdoc/TokenStream.vala"
	G_OBJECT_CLASS (jsdoc_token_stream_parent_class)->finalize (obj);
#line 2153 "TokenStream.c"
}


GType jsdoc_token_stream_get_type (void) {
	static volatile gsize jsdoc_token_stream_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_token_stream_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCTokenStreamClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_token_stream_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCTokenStream), 0, (GInstanceInitFunc) jsdoc_token_stream_instance_init, NULL };
		GType jsdoc_token_stream_type_id;
		jsdoc_token_stream_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCTokenStream", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_token_stream_type_id__volatile, jsdoc_token_stream_type_id);
	}
	return jsdoc_token_stream_type_id__volatile;
}



