/* Collapse.c generated by valac 0.28.1, the Vala compiler
 * generated from Collapse.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define JSDOC_TYPE_TOKEN_STREAM (jsdoc_token_stream_get_type ())
#define JSDOC_TOKEN_STREAM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStream))
#define JSDOC_TOKEN_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStreamClass))
#define JSDOC_IS_TOKEN_STREAM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN_STREAM))
#define JSDOC_IS_TOKEN_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN_STREAM))
#define JSDOC_TOKEN_STREAM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN_STREAM, JSDOCTokenStreamClass))

typedef struct _JSDOCTokenStream JSDOCTokenStream;
typedef struct _JSDOCTokenStreamClass JSDOCTokenStreamClass;
typedef struct _JSDOCTokenStreamPrivate JSDOCTokenStreamPrivate;

#define JSDOC_TYPE_TOKEN (jsdoc_token_get_type ())
#define JSDOC_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN, JSDOCToken))
#define JSDOC_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN, JSDOCTokenClass))
#define JSDOC_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN))
#define JSDOC_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN))
#define JSDOC_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN, JSDOCTokenClass))

typedef struct _JSDOCToken JSDOCToken;
typedef struct _JSDOCTokenClass JSDOCTokenClass;

#define JSDOC_TYPE_COLLAPSE (jsdoc_collapse_get_type ())
#define JSDOC_COLLAPSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_COLLAPSE, JSDOCCollapse))
#define JSDOC_COLLAPSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_COLLAPSE, JSDOCCollapseClass))
#define JSDOC_IS_COLLAPSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_COLLAPSE))
#define JSDOC_IS_COLLAPSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_COLLAPSE))
#define JSDOC_COLLAPSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_COLLAPSE, JSDOCCollapseClass))

typedef struct _JSDOCCollapse JSDOCCollapse;
typedef struct _JSDOCCollapseClass JSDOCCollapseClass;
typedef struct _JSDOCCollapsePrivate JSDOCCollapsePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _JSDOCTokenPrivate JSDOCTokenPrivate;

#define JSDOC_TYPE_IDENTIFIER (jsdoc_identifier_get_type ())
#define JSDOC_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifier))
#define JSDOC_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))
#define JSDOC_IS_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IS_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IDENTIFIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))

typedef struct _JSDOCIdentifier JSDOCIdentifier;
typedef struct _JSDOCIdentifierClass JSDOCIdentifierClass;

#define JSDOC_TYPE_TOKEN_KEY_MAP (jsdoc_token_key_map_get_type ())
#define JSDOC_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMap))
#define JSDOC_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))
#define JSDOC_IS_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_IS_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_TOKEN_KEY_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))

typedef struct _JSDOCTokenKeyMap JSDOCTokenKeyMap;
typedef struct _JSDOCTokenKeyMapClass JSDOCTokenKeyMapClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _JSDOCTokenKeyMapPrivate JSDOCTokenKeyMapPrivate;

struct _JSDOCTokenStream {
	GObject parent_instance;
	JSDOCTokenStreamPrivate * priv;
	GeeArrayList* tokens;
	gint cursor;
};

struct _JSDOCTokenStreamClass {
	GObjectClass parent_class;
};

struct _JSDOCCollapse {
	JSDOCTokenStream parent_instance;
	JSDOCCollapsePrivate * priv;
};

struct _JSDOCCollapseClass {
	JSDOCTokenStreamClass parent_class;
};

struct _JSDOCToken {
	GObject parent_instance;
	JSDOCTokenPrivate * priv;
	gint id;
	gchar* data;
	gchar* type;
	gchar* name;
	gint line;
	gchar* prefix;
	gchar* outData;
	JSDOCIdentifier* identifier;
	GeeArrayList* items;
	GeeHashMap* props;
};

struct _JSDOCTokenClass {
	GObjectClass parent_class;
};

typedef enum  {
	JSDOC_TOKEN_STREAM_ERROR_ArgumentError
} JSDOCTokenStreamError;
#define JSDOC_TOKEN_STREAM_ERROR jsdoc_token_stream_error_quark ()
struct _JSDOCTokenKeyMap {
	GObject parent_instance;
	JSDOCTokenKeyMapPrivate * priv;
	JSDOCToken* key;
	GeeArrayList* vals;
};

struct _JSDOCTokenKeyMapClass {
	GObjectClass parent_class;
};


static gpointer jsdoc_collapse_parent_class = NULL;

GType jsdoc_token_stream_get_type (void) G_GNUC_CONST;
GType jsdoc_token_get_type (void) G_GNUC_CONST;
GType jsdoc_collapse_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_COLLAPSE_DUMMY_PROPERTY
};
JSDOCCollapse* jsdoc_collapse_new (GeeArrayList* tokens);
JSDOCCollapse* jsdoc_collapse_construct (GType object_type, GeeArrayList* tokens);
JSDOCTokenStream* jsdoc_token_stream_new (GeeArrayList* tokens);
JSDOCTokenStream* jsdoc_token_stream_construct (GType object_type, GeeArrayList* tokens);
static void jsdoc_collapse_spaces (JSDOCCollapse* self);
static GeeArrayList* jsdoc_collapse_collapse (JSDOCCollapse* self, GeeArrayList* ar);
gboolean jsdoc_token_is (JSDOCToken* self, const gchar* what);
GType jsdoc_identifier_get_type (void) G_GNUC_CONST;
GType jsdoc_token_key_map_get_type (void) G_GNUC_CONST;
JSDOCToken* jsdoc_token_stream_look (JSDOCTokenStream* self, gint n, gboolean considerWhitespace);
gchar* jsdoc_token_asString (JSDOCToken* self);
JSDOCToken* jsdoc_token_stream_next (JSDOCTokenStream* self);
GQuark jsdoc_token_stream_error_quark (void);
GeeArrayList* jsdoc_token_stream_balance (JSDOCTokenStream* self, const gchar* start, const gchar* in_stop, GError** error);
static GeeArrayList* jsdoc_collapse_toItems (JSDOCCollapse* self, GeeArrayList* ar, const gchar* sep);
static GeeHashMap* jsdoc_collapse_toProps (JSDOCCollapse* self, GeeArrayList* ar);
JSDOCTokenKeyMap* jsdoc_token_key_map_new (void);
JSDOCTokenKeyMap* jsdoc_token_key_map_construct (GType object_type);


static gpointer _g_object_ref0 (gpointer self) {
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	return self ? g_object_ref (self) : NULL;
#line 155 "Collapse.c"
}


JSDOCCollapse* jsdoc_collapse_construct (GType object_type, GeeArrayList* tokens) {
	JSDOCCollapse * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* ar = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
#line 34 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (tokens != NULL, NULL);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp0_ = tokens;
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	self = (JSDOCCollapse*) jsdoc_token_stream_construct (object_type, _tmp0_);
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	jsdoc_collapse_spaces (self);
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp1_ = ((JSDOCTokenStream*) self)->tokens;
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp2_ = jsdoc_collapse_collapse (self, _tmp1_);
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	ar = _tmp2_;
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp3_ = _g_object_ref0 (ar);
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (((JSDOCTokenStream*) self)->tokens);
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	((JSDOCTokenStream*) self)->tokens = _tmp3_;
#line 34 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (ar);
#line 34 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	return self;
#line 190 "Collapse.c"
}


JSDOCCollapse* jsdoc_collapse_new (GeeArrayList* tokens) {
#line 34 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	return jsdoc_collapse_construct (JSDOC_TYPE_COLLAPSE, tokens);
#line 197 "Collapse.c"
}


static void jsdoc_collapse_spaces (JSDOCCollapse* self) {
	GeeArrayList* ar = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* pref = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp43_ = NULL;
	GeeArrayList* _tmp44_ = NULL;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_if_fail (self != NULL);
#line 52 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp0_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 52 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	ar = _tmp0_;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp1_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	pref = _tmp1_;
#line 218 "Collapse.c"
	{
		gint i = 0;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		i = 0;
#line 223 "Collapse.c"
		{
			gboolean _tmp2_ = FALSE;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			_tmp2_ = TRUE;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			while (TRUE) {
#line 230 "Collapse.c"
				gint _tmp4_ = 0;
				GeeArrayList* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				JSDOCToken* tok = NULL;
				GeeArrayList* _tmp8_ = NULL;
				gint _tmp9_ = 0;
				gpointer _tmp10_ = NULL;
				gboolean _tmp11_ = FALSE;
				JSDOCToken* _tmp12_ = NULL;
				gboolean _tmp13_ = FALSE;
				JSDOCToken* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				GeeArrayList* _tmp20_ = NULL;
				gint _tmp21_ = 0;
				gint _tmp22_ = 0;
				GeeArrayList* _tmp41_ = NULL;
				JSDOCToken* _tmp42_ = NULL;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!_tmp2_) {
#line 251 "Collapse.c"
					gint _tmp3_ = 0;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp3_ = i;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					i = _tmp3_ + 1;
#line 257 "Collapse.c"
				}
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp2_ = FALSE;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp4_ = i;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp5_ = ((JSDOCTokenStream*) self)->tokens;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp6_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp5_);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp7_ = _tmp6_;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!(_tmp4_ < _tmp7_)) {
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					break;
#line 273 "Collapse.c"
				}
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp8_ = ((JSDOCTokenStream*) self)->tokens;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp9_ = i;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				tok = (JSDOCToken*) _tmp10_;
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp12_ = tok;
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp13_ = jsdoc_token_is (_tmp12_, "COMM");
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp13_) {
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp11_ = TRUE;
#line 291 "Collapse.c"
				} else {
					JSDOCToken* _tmp14_ = NULL;
					gboolean _tmp15_ = FALSE;
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp14_ = tok;
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp15_ = jsdoc_token_is (_tmp14_, "WHIT");
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp11_ = _tmp15_;
#line 301 "Collapse.c"
				}
#line 59 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp11_) {
#line 305 "Collapse.c"
					GeeArrayList* _tmp16_ = NULL;
					JSDOCToken* _tmp17_ = NULL;
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp16_ = pref;
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp17_ = tok;
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp16_, _tmp17_);
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (tok);
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 318 "Collapse.c"
				}
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp18_ = tok;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp19_ = g_strdup ("");
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_free0 (_tmp18_->prefix);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp18_->prefix = _tmp19_;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp20_ = pref;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp21_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp20_);
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp22_ = _tmp21_;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp22_ > 0) {
#line 336 "Collapse.c"
					GeeArrayList* _tmp40_ = NULL;
					{
						GeeArrayList* _e_list = NULL;
						GeeArrayList* _tmp23_ = NULL;
						GeeArrayList* _tmp24_ = NULL;
						gint _e_size = 0;
						GeeArrayList* _tmp25_ = NULL;
						gint _tmp26_ = 0;
						gint _tmp27_ = 0;
						gint _e_index = 0;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp23_ = pref;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp24_ = _g_object_ref0 (_tmp23_);
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_e_list = _tmp24_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp25_ = _e_list;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp26_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp25_);
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp27_ = _tmp26_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_e_size = _tmp27_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_e_index = -1;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						while (TRUE) {
#line 365 "Collapse.c"
							gint _tmp28_ = 0;
							gint _tmp29_ = 0;
							gint _tmp30_ = 0;
							JSDOCToken* e = NULL;
							GeeArrayList* _tmp31_ = NULL;
							gint _tmp32_ = 0;
							gpointer _tmp33_ = NULL;
							JSDOCToken* _tmp34_ = NULL;
							JSDOCToken* _tmp35_ = NULL;
							const gchar* _tmp36_ = NULL;
							JSDOCToken* _tmp37_ = NULL;
							const gchar* _tmp38_ = NULL;
							gchar* _tmp39_ = NULL;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp28_ = _e_index;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_e_index = _tmp28_ + 1;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp29_ = _e_index;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp30_ = _e_size;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							if (!(_tmp29_ < _tmp30_)) {
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								break;
#line 391 "Collapse.c"
							}
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp31_ = _e_list;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp32_ = _e_index;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp33_ = gee_abstract_list_get ((GeeAbstractList*) _tmp31_, _tmp32_);
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							e = (JSDOCToken*) _tmp33_;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp34_ = tok;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp35_ = tok;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp36_ = _tmp35_->prefix;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp37_ = e;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp38_ = _tmp37_->data;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp39_ = g_strconcat (_tmp36_, _tmp38_, NULL);
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_g_free0 (_tmp35_->prefix);
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_tmp35_->prefix = _tmp39_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							_g_object_unref0 (e);
#line 419 "Collapse.c"
						}
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (_e_list);
#line 423 "Collapse.c"
					}
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp40_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (pref);
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					pref = _tmp40_;
#line 431 "Collapse.c"
				}
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp41_ = ar;
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp42_ = tok;
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp41_, _tmp42_);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_object_unref0 (tok);
#line 441 "Collapse.c"
			}
		}
	}
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp43_ = ar;
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp44_ = _g_object_ref0 (_tmp43_);
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (((JSDOCTokenStream*) self)->tokens);
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	((JSDOCTokenStream*) self)->tokens = _tmp44_;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (pref);
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (ar);
#line 457 "Collapse.c"
}


static GeeArrayList* jsdoc_collapse_collapse (JSDOCCollapse* self, GeeArrayList* ar) {
	GeeArrayList* result = NULL;
	JSDOCTokenStream* st = NULL;
	GeeArrayList* _tmp0_ = NULL;
	JSDOCTokenStream* _tmp1_ = NULL;
	GeeArrayList* ret = NULL;
	GeeArrayList* _tmp2_ = NULL;
	GError * _inner_error_ = NULL;
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (ar != NULL, NULL);
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp0_ = ar;
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp1_ = jsdoc_token_stream_new (_tmp0_);
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	st = _tmp1_;
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp2_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	ret = _tmp2_;
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	while (TRUE) {
#line 485 "Collapse.c"
		JSDOCToken* tok = NULL;
		JSDOCTokenStream* _tmp3_ = NULL;
		JSDOCToken* _tmp4_ = NULL;
		JSDOCToken* _tmp5_ = NULL;
		JSDOCToken* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		JSDOCToken* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		GQuark _tmp13_ = 0U;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label0 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label1 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label2 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label3 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label4 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label5 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label6 = 0;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		static GQuark _tmp12_label7 = 0;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp3_ = st;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp4_ = jsdoc_token_stream_look (_tmp3_, 1, TRUE);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		tok = _tmp4_;
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp5_ = tok;
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		if (_tmp5_ == NULL) {
#line 92 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			result = ret;
#line 92 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			_g_object_unref0 (tok);
#line 92 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			_g_object_unref0 (st);
#line 92 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			return result;
#line 531 "Collapse.c"
		}
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp6_ = tok;
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp7_ = jsdoc_token_asString (_tmp6_);
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp8_ = _tmp7_;
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		g_debug ("Collapse.vala:96: COL: %s", _tmp8_);
#line 96 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_g_free0 (_tmp8_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp9_ = tok;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp10_ = _tmp9_->type;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp11_ = _tmp10_;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp13_ = (NULL == _tmp11_) ? 0 : g_quark_from_string (_tmp11_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		if (_tmp13_ == ((0 != _tmp12_label0) ? _tmp12_label0 : (_tmp12_label0 = g_quark_from_static_string ("VOID")))) {
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			switch (0) {
#line 555 "Collapse.c"
				default:
				{
#line 100 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					result = ret;
#line 100 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (tok);
#line 100 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (st);
#line 100 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					return result;
#line 566 "Collapse.c"
				}
			}
		} else if ((((((_tmp13_ == ((0 != _tmp12_label1) ? _tmp12_label1 : (_tmp12_label1 = g_quark_from_static_string ("KEYW")))) || (_tmp13_ == ((0 != _tmp12_label2) ? _tmp12_label2 : (_tmp12_label2 = g_quark_from_static_string ("TOKN"))))) || (_tmp13_ == ((0 != _tmp12_label3) ? _tmp12_label3 : (_tmp12_label3 = g_quark_from_static_string ("NAME"))))) || (_tmp13_ == ((0 != _tmp12_label4) ? _tmp12_label4 : (_tmp12_label4 = g_quark_from_static_string ("STRN"))))) || (_tmp13_ == ((0 != _tmp12_label5) ? _tmp12_label5 : (_tmp12_label5 = g_quark_from_static_string ("NUMB"))))) || (_tmp13_ == ((0 != _tmp12_label6) ? _tmp12_label6 : (_tmp12_label6 = g_quark_from_static_string ("REGX"))))) {
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			switch (0) {
#line 572 "Collapse.c"
				default:
				{
					JSDOCToken* nn = NULL;
					JSDOCTokenStream* _tmp14_ = NULL;
					JSDOCToken* _tmp15_ = NULL;
					JSDOCToken* _tmp16_ = NULL;
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp14_ = st;
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp15_ = jsdoc_token_stream_next (_tmp14_);
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					nn = _tmp15_;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp16_ = nn;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					if (_tmp16_ != NULL) {
#line 589 "Collapse.c"
						GeeArrayList* _tmp17_ = NULL;
						JSDOCToken* _tmp18_ = NULL;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp17_ = ret;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp18_ = nn;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						gee_abstract_collection_add ((GeeAbstractCollection*) _tmp17_, _tmp18_);
#line 598 "Collapse.c"
					}
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (nn);
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 604 "Collapse.c"
				}
			}
		} else if (_tmp13_ == ((0 != _tmp12_label7) ? _tmp12_label7 : (_tmp12_label7 = g_quark_from_static_string ("PUNC")))) {
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			switch (0) {
#line 610 "Collapse.c"
				default:
				{
					JSDOCToken* _tmp19_ = NULL;
					const gchar* _tmp20_ = NULL;
					const gchar* _tmp21_ = NULL;
					GQuark _tmp23_ = 0U;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					static GQuark _tmp22_label0 = 0;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					static GQuark _tmp22_label1 = 0;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					static GQuark _tmp22_label2 = 0;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp19_ = tok;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp20_ = _tmp19_->data;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp21_ = _tmp20_;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp23_ = (NULL == _tmp21_) ? 0 : g_quark_from_string (_tmp21_);
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					if (((_tmp23_ == ((0 != _tmp22_label0) ? _tmp22_label0 : (_tmp22_label0 = g_quark_from_static_string ("[")))) || (_tmp23_ == ((0 != _tmp22_label1) ? _tmp22_label1 : (_tmp22_label1 = g_quark_from_static_string ("{"))))) || (_tmp23_ == ((0 != _tmp22_label2) ? _tmp22_label2 : (_tmp22_label2 = g_quark_from_static_string ("("))))) {
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						switch (0) {
#line 635 "Collapse.c"
							default:
							{
								gint start = 0;
								JSDOCTokenStream* _tmp24_ = NULL;
								gint _tmp25_ = 0;
								GeeArrayList* add = NULL;
								JSDOCTokenStream* _tmp26_ = NULL;
								JSDOCToken* _tmp27_ = NULL;
								const gchar* _tmp28_ = NULL;
								GeeArrayList* _tmp29_ = NULL;
								GeeArrayList* _tmp30_ = NULL;
								gint _tmp31_ = 0;
								gint _tmp32_ = 0;
								GeeArrayList* _tmp33_ = NULL;
								gint _tmp34_ = 0;
								gint _tmp35_ = 0;
								GeeArrayList* _tmp39_ = NULL;
								GeeArrayList* _tmp40_ = NULL;
								gint _tmp41_ = 0;
								gint _tmp42_ = 0;
								GeeArrayList* toks = NULL;
								GeeArrayList* _tmp47_ = NULL;
								JSDOCToken* _tmp48_ = NULL;
								GeeArrayList* _tmp49_ = NULL;
								JSDOCToken* _tmp50_ = NULL;
								GeeHashMap* _tmp51_ = NULL;
								JSDOCToken* _tmp52_ = NULL;
								const gchar* _tmp53_ = NULL;
								GeeArrayList* _tmp74_ = NULL;
								JSDOCToken* _tmp75_ = NULL;
#line 121 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp24_ = st;
#line 121 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp25_ = _tmp24_->cursor;
#line 121 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								start = _tmp25_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp26_ = st;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp27_ = tok;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp28_ = _tmp27_->data;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp29_ = jsdoc_token_stream_balance (_tmp26_, _tmp28_, "", &_inner_error_);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								add = _tmp29_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (tok);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (ret);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (st);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									g_clear_error (&_inner_error_);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									return NULL;
#line 696 "Collapse.c"
								}
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp30_ = add;
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp31_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp30_);
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp32_ = _tmp31_;
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								g_debug ("Collapse.vala:126: BALANCE returned %d items\n", _tmp32_);
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp33_ = add;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp34_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp33_);
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp35_ = _tmp34_;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								if (_tmp35_ > 0) {
#line 714 "Collapse.c"
									GeeArrayList* _tmp36_ = NULL;
									gpointer _tmp37_ = NULL;
									JSDOCToken* _tmp38_ = NULL;
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp36_ = add;
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp37_ = gee_abstract_list_remove_at ((GeeAbstractList*) _tmp36_, 0);
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp38_ = (JSDOCToken*) _tmp37_;
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (_tmp38_);
#line 726 "Collapse.c"
								}
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp40_ = add;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp41_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp40_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp42_ = _tmp41_;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								if (_tmp42_ > 0) {
#line 736 "Collapse.c"
									GeeArrayList* _tmp43_ = NULL;
									GeeArrayList* _tmp44_ = NULL;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp43_ = add;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp44_ = jsdoc_collapse_collapse (self, _tmp43_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (_tmp39_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp39_ = _tmp44_;
#line 747 "Collapse.c"
								} else {
									GeeArrayList* _tmp45_ = NULL;
									GeeArrayList* _tmp46_ = NULL;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp45_ = add;
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp46_ = _g_object_ref0 (_tmp45_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (_tmp39_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp39_ = _tmp46_;
#line 759 "Collapse.c"
								}
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp47_ = _g_object_ref0 (_tmp39_);
#line 143 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								toks = _tmp47_;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp48_ = tok;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp49_ = gee_array_list_new (GEE_TYPE_ARRAY_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (_tmp48_->items);
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp48_->items = _tmp49_;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp50_ = tok;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp51_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, JSDOC_TYPE_TOKEN_KEY_MAP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (_tmp50_->props);
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp50_->props = _tmp51_;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp52_ = tok;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp53_ = _tmp52_->data;
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								if (g_strcmp0 (_tmp53_, "{") != 0) {
#line 787 "Collapse.c"
									JSDOCToken* _tmp54_ = NULL;
									GeeArrayList* _tmp55_ = NULL;
									GeeArrayList* _tmp56_ = NULL;
#line 151 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp54_ = tok;
#line 151 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp55_ = toks;
#line 151 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp56_ = jsdoc_collapse_toItems (self, _tmp55_, ",");
#line 151 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (_tmp54_->items);
#line 151 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp54_->items = _tmp56_;
#line 801 "Collapse.c"
								} else {
									JSDOCTokenStream* ost = NULL;
									GeeArrayList* _tmp57_ = NULL;
									JSDOCTokenStream* _tmp58_ = NULL;
									gboolean _tmp59_ = FALSE;
									JSDOCTokenStream* _tmp60_ = NULL;
									JSDOCToken* _tmp61_ = NULL;
									JSDOCToken* _tmp62_ = NULL;
									gboolean _tmp63_ = FALSE;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp57_ = toks;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp58_ = jsdoc_token_stream_new (_tmp57_);
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									ost = _tmp58_;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp60_ = ost;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp61_ = jsdoc_token_stream_look (_tmp60_, 2, TRUE);
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp62_ = _tmp61_;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_tmp63_ = _tmp62_ != NULL;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (_tmp62_);
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									if (_tmp63_) {
#line 829 "Collapse.c"
										JSDOCTokenStream* _tmp64_ = NULL;
										JSDOCToken* _tmp65_ = NULL;
										JSDOCToken* _tmp66_ = NULL;
										const gchar* _tmp67_ = NULL;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp64_ = ost;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp65_ = jsdoc_token_stream_look (_tmp64_, 2, TRUE);
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp66_ = _tmp65_;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp67_ = _tmp66_->data;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp59_ = g_strcmp0 (_tmp67_, ":") == 0;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_g_object_unref0 (_tmp66_);
#line 846 "Collapse.c"
									} else {
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp59_ = FALSE;
#line 850 "Collapse.c"
									}
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									if (_tmp59_) {
#line 854 "Collapse.c"
										JSDOCToken* _tmp68_ = NULL;
										GeeArrayList* _tmp69_ = NULL;
										GeeHashMap* _tmp70_ = NULL;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp68_ = tok;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp69_ = toks;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp70_ = jsdoc_collapse_toProps (self, _tmp69_);
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_g_object_unref0 (_tmp68_->props);
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp68_->props = _tmp70_;
#line 868 "Collapse.c"
									} else {
										JSDOCToken* _tmp71_ = NULL;
										GeeArrayList* _tmp72_ = NULL;
										GeeArrayList* _tmp73_ = NULL;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp71_ = tok;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp72_ = toks;
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp73_ = jsdoc_collapse_toItems (self, _tmp72_, ";{");
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_g_object_unref0 (_tmp71_->items);
#line 163 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
										_tmp71_->items = _tmp73_;
#line 883 "Collapse.c"
									}
#line 149 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
									_g_object_unref0 (ost);
#line 887 "Collapse.c"
								}
#line 177 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp74_ = ret;
#line 177 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp75_ = tok;
#line 177 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								gee_abstract_collection_add ((GeeAbstractCollection*) _tmp74_, _tmp75_);
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (toks);
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (_tmp39_);
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (add);
#line 179 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								continue;
#line 903 "Collapse.c"
							}
						}
					} else {
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						switch (0) {
#line 909 "Collapse.c"
							default:
							{
								GeeArrayList* _tmp76_ = NULL;
								JSDOCTokenStream* _tmp77_ = NULL;
								JSDOCToken* _tmp78_ = NULL;
								JSDOCToken* _tmp79_ = NULL;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp76_ = ret;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp77_ = st;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp78_ = jsdoc_token_stream_next (_tmp77_);
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_tmp79_ = _tmp78_;
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								gee_abstract_collection_add ((GeeAbstractCollection*) _tmp76_, _tmp79_);
#line 182 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								_g_object_unref0 (_tmp79_);
#line 183 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
								continue;
#line 930 "Collapse.c"
							}
						}
					}
#line 185 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					g_print ("OOPS");
#line 186 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 938 "Collapse.c"
				}
			}
		} else {
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			switch (0) {
#line 944 "Collapse.c"
				default:
				{
					JSDOCToken* _tmp80_ = NULL;
					const gchar* _tmp81_ = NULL;
					gchar* _tmp82_ = NULL;
					gchar* _tmp83_ = NULL;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp80_ = tok;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp81_ = _tmp80_->type;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp82_ = g_strconcat ("OOPS", _tmp81_, NULL);
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp83_ = _tmp82_;
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					g_print ("%s", _tmp83_);
#line 188 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_free0 (_tmp83_);
#line 189 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 965 "Collapse.c"
				}
			}
		}
#line 88 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_g_object_unref0 (tok);
#line 971 "Collapse.c"
	}
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (ret);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (st);
#line 977 "Collapse.c"
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 900 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 900 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 901 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 903 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 903 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 1004 "Collapse.c"
		gchar* _tmp4_ = NULL;
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 904 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 1012 "Collapse.c"
	} else {
#line 906 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = -1;
#line 906 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 1018 "Collapse.c"
	}
}


static GeeArrayList* jsdoc_collapse_toItems (JSDOCCollapse* self, GeeArrayList* ar, const gchar* sep) {
	GeeArrayList* result = NULL;
	GeeArrayList* ret = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* g = NULL;
	GeeArrayList* _tmp1_ = NULL;
	GeeArrayList* _tmp49_ = NULL;
	gint _tmp50_ = 0;
	gint _tmp51_ = 0;
#line 204 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 204 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (ar != NULL, NULL);
#line 204 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (sep != NULL, NULL);
#line 206 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp0_ = gee_array_list_new (GEE_TYPE_ARRAY_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 206 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	ret = _tmp0_;
#line 207 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp1_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 207 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g = _tmp1_;
#line 1046 "Collapse.c"
	{
		gint i = 0;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		i = 0;
#line 1051 "Collapse.c"
		{
			gboolean _tmp2_ = FALSE;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			_tmp2_ = TRUE;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			while (TRUE) {
#line 1058 "Collapse.c"
				gint _tmp4_ = 0;
				GeeArrayList* _tmp5_ = NULL;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				const gchar* _tmp8_ = NULL;
				GeeArrayList* _tmp9_ = NULL;
				gint _tmp10_ = 0;
				gpointer _tmp11_ = NULL;
				JSDOCToken* _tmp12_ = NULL;
				const gchar* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				gboolean _tmp15_ = FALSE;
				gboolean _tmp21_ = FALSE;
				gboolean _tmp22_ = FALSE;
				GeeArrayList* _tmp23_ = NULL;
				gint _tmp24_ = 0;
				gpointer _tmp25_ = NULL;
				JSDOCToken* _tmp26_ = NULL;
				const gchar* _tmp27_ = NULL;
				gboolean _tmp28_ = FALSE;
				GeeArrayList* _tmp41_ = NULL;
				GeeArrayList* _tmp42_ = NULL;
				gint _tmp43_ = 0;
				gpointer _tmp44_ = NULL;
				JSDOCToken* _tmp45_ = NULL;
				GeeArrayList* _tmp46_ = NULL;
				GeeArrayList* _tmp47_ = NULL;
				GeeArrayList* _tmp48_ = NULL;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!_tmp2_) {
#line 1089 "Collapse.c"
					gint _tmp3_ = 0;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp3_ = i;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					i = _tmp3_ + 1;
#line 1095 "Collapse.c"
				}
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp2_ = FALSE;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp4_ = i;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp5_ = ar;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp6_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp5_);
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp7_ = _tmp6_;
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!(_tmp4_ < _tmp7_)) {
#line 209 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					break;
#line 1111 "Collapse.c"
				}
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp8_ = sep;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp9_ = ar;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp10_ = i;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp12_ = (JSDOCToken*) _tmp11_;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp13_ = _tmp12_->data;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp14_ = string_index_of (_tmp8_, _tmp13_, 0);
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp15_ = _tmp14_ < 0;
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_object_unref0 (_tmp12_);
#line 210 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp15_) {
#line 1133 "Collapse.c"
					GeeArrayList* _tmp16_ = NULL;
					GeeArrayList* _tmp17_ = NULL;
					gint _tmp18_ = 0;
					gpointer _tmp19_ = NULL;
					JSDOCToken* _tmp20_ = NULL;
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp16_ = g;
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp17_ = ar;
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp18_ = i;
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp20_ = (JSDOCToken*) _tmp19_;
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp16_, _tmp20_);
#line 211 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (_tmp20_);
#line 212 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 1155 "Collapse.c"
				}
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp23_ = ar;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp24_ = i;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp25_ = gee_abstract_list_get ((GeeAbstractList*) _tmp23_, _tmp24_);
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp26_ = (JSDOCToken*) _tmp25_;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp27_ = _tmp26_->data;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp28_ = g_strcmp0 (_tmp27_, ";") != 0;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_object_unref0 (_tmp26_);
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp28_) {
#line 1173 "Collapse.c"
					GeeArrayList* _tmp29_ = NULL;
					gint _tmp30_ = 0;
					gint _tmp31_ = 0;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp29_ = g;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp30_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp29_);
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp31_ = _tmp30_;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp22_ = _tmp31_ > 0;
#line 1185 "Collapse.c"
				} else {
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp22_ = FALSE;
#line 1189 "Collapse.c"
				}
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp22_) {
#line 1193 "Collapse.c"
					GeeArrayList* _tmp32_ = NULL;
					gpointer _tmp33_ = NULL;
					JSDOCToken* _tmp34_ = NULL;
					const gchar* _tmp35_ = NULL;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp32_ = g;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp33_ = gee_abstract_list_get ((GeeAbstractList*) _tmp32_, 0);
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp34_ = (JSDOCToken*) _tmp33_;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp35_ = _tmp34_->name;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp21_ = g_strcmp0 (_tmp35_, "VAR") == 0;
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (_tmp34_);
#line 1210 "Collapse.c"
				} else {
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp21_ = FALSE;
#line 1214 "Collapse.c"
				}
#line 215 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (_tmp21_) {
#line 1218 "Collapse.c"
					GeeArrayList* _tmp36_ = NULL;
					GeeArrayList* _tmp37_ = NULL;
					gint _tmp38_ = 0;
					gpointer _tmp39_ = NULL;
					JSDOCToken* _tmp40_ = NULL;
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp36_ = g;
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp37_ = ar;
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp38_ = i;
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp39_ = gee_abstract_list_get ((GeeAbstractList*) _tmp37_, _tmp38_);
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp40_ = (JSDOCToken*) _tmp39_;
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp36_, _tmp40_);
#line 216 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_g_object_unref0 (_tmp40_);
#line 217 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					continue;
#line 1240 "Collapse.c"
				}
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp41_ = g;
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp42_ = ar;
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp43_ = i;
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp44_ = gee_abstract_list_get ((GeeAbstractList*) _tmp42_, _tmp43_);
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp45_ = (JSDOCToken*) _tmp44_;
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp41_, _tmp45_);
#line 220 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_object_unref0 (_tmp45_);
#line 221 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp46_ = ret;
#line 221 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp47_ = g;
#line 221 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp46_, _tmp47_);
#line 222 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp48_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 222 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_g_object_unref0 (g);
#line 222 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				g = _tmp48_;
#line 1268 "Collapse.c"
			}
		}
	}
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp49_ = g;
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp50_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp49_);
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp51_ = _tmp50_;
#line 226 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	if (_tmp51_ > 0) {
#line 1280 "Collapse.c"
		GeeArrayList* _tmp52_ = NULL;
		GeeArrayList* _tmp53_ = NULL;
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp52_ = ret;
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp53_ = g;
#line 227 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp52_, _tmp53_);
#line 1289 "Collapse.c"
	}
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	result = ret;
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (g);
#line 229 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	return result;
#line 1297 "Collapse.c"
}


static GeeHashMap* jsdoc_collapse_toProps (JSDOCCollapse* self, GeeArrayList* ar) {
	GeeHashMap* result = NULL;
	GeeHashMap* ret = NULL;
	GeeHashMap* _tmp0_ = NULL;
	JSDOCTokenKeyMap* g = NULL;
	JSDOCTokenKeyMap* _tmp1_ = NULL;
	gchar* k = NULL;
	gchar* _tmp2_ = NULL;
	gint state = 0;
	gboolean _tmp36_ = FALSE;
	const gchar* _tmp37_ = NULL;
	gint _tmp38_ = 0;
	gint _tmp39_ = 0;
#line 233 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 233 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g_return_val_if_fail (ar != NULL, NULL);
#line 236 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, JSDOC_TYPE_TOKEN_KEY_MAP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 236 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	ret = _tmp0_;
#line 238 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp1_ = jsdoc_token_key_map_new ();
#line 238 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	g = _tmp1_;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp2_ = g_strdup ("");
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	k = _tmp2_;
#line 242 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	state = 0;
#line 1332 "Collapse.c"
	{
		gint i = 0;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		i = 0;
#line 1337 "Collapse.c"
		{
			gboolean _tmp3_ = FALSE;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			_tmp3_ = TRUE;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
			while (TRUE) {
#line 1344 "Collapse.c"
				gint _tmp5_ = 0;
				GeeArrayList* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				gint _tmp9_ = 0;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!_tmp3_) {
#line 1352 "Collapse.c"
					gint _tmp4_ = 0;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					_tmp4_ = i;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					i = _tmp4_ + 1;
#line 1358 "Collapse.c"
				}
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp3_ = FALSE;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp5_ = i;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp6_ = ar;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp7_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp6_);
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp8_ = _tmp7_;
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				if (!(_tmp5_ < _tmp8_)) {
#line 243 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					break;
#line 1374 "Collapse.c"
				}
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				_tmp9_ = state;
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
				switch (_tmp9_) {
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					case 0:
#line 1382 "Collapse.c"
					{
						GeeArrayList* _tmp10_ = NULL;
						gint _tmp11_ = 0;
						gpointer _tmp12_ = NULL;
						JSDOCToken* _tmp13_ = NULL;
						const gchar* _tmp14_ = NULL;
						gchar* _tmp15_ = NULL;
						JSDOCTokenKeyMap* _tmp16_ = NULL;
						GeeArrayList* _tmp17_ = NULL;
						gint _tmp18_ = 0;
						gpointer _tmp19_ = NULL;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp10_ = ar;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp11_ = i;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_);
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp13_ = (JSDOCToken*) _tmp12_;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp14_ = _tmp13_->data;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp15_ = g_strdup (_tmp14_);
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_free0 (k);
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						k = _tmp15_;
#line 247 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (_tmp13_);
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp16_ = g;
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp17_ = ar;
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp18_ = i;
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (_tmp16_->key);
#line 248 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp16_->key = (JSDOCToken*) _tmp19_;
#line 249 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						state = 1;
#line 250 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						continue;
#line 1428 "Collapse.c"
					}
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					case 1:
#line 1432 "Collapse.c"
					{
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						state = 2;
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						continue;
#line 1438 "Collapse.c"
					}
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					case 2:
#line 1442 "Collapse.c"
					{
						JSDOCTokenKeyMap* _tmp20_ = NULL;
						GeeArrayList* _tmp21_ = NULL;
						GeeArrayList* _tmp22_ = NULL;
						gint _tmp23_ = 0;
						gpointer _tmp24_ = NULL;
						JSDOCToken* _tmp25_ = NULL;
						GeeArrayList* _tmp26_ = NULL;
						gint _tmp27_ = 0;
						gpointer _tmp28_ = NULL;
						JSDOCToken* _tmp29_ = NULL;
						const gchar* _tmp30_ = NULL;
						gboolean _tmp31_ = FALSE;
						GeeHashMap* _tmp32_ = NULL;
						const gchar* _tmp33_ = NULL;
						JSDOCTokenKeyMap* _tmp34_ = NULL;
						JSDOCTokenKeyMap* _tmp35_ = NULL;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp20_ = g;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp21_ = _tmp20_->vals;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp22_ = ar;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp23_ = i;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp24_ = gee_abstract_list_get ((GeeAbstractList*) _tmp22_, _tmp23_);
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp25_ = (JSDOCToken*) _tmp24_;
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						gee_abstract_collection_add ((GeeAbstractCollection*) _tmp21_, _tmp25_);
#line 255 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (_tmp25_);
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp26_ = ar;
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp27_ = i;
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp28_ = gee_abstract_list_get ((GeeAbstractList*) _tmp26_, _tmp27_);
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp29_ = (JSDOCToken*) _tmp28_;
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp30_ = _tmp29_->data;
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp31_ = g_strcmp0 (_tmp30_, ",") != 0;
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (_tmp29_);
#line 256 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						if (_tmp31_) {
#line 257 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
							continue;
#line 1494 "Collapse.c"
						}
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp32_ = ret;
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp33_ = k;
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp34_ = g;
#line 259 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						gee_abstract_map_set ((GeeAbstractMap*) _tmp32_, _tmp33_, _tmp34_);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_tmp35_ = jsdoc_token_key_map_new ();
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						_g_object_unref0 (g);
#line 260 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						g = _tmp35_;
#line 261 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						state = 0;
#line 262 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
						continue;
#line 1514 "Collapse.c"
					}
					default:
#line 245 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
					break;
#line 1519 "Collapse.c"
				}
			}
		}
	}
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp37_ = k;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp38_ = strlen (_tmp37_);
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_tmp39_ = _tmp38_;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	if (_tmp39_ > 0) {
#line 1532 "Collapse.c"
		JSDOCTokenKeyMap* _tmp40_ = NULL;
		GeeArrayList* _tmp41_ = NULL;
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp40_ = g;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp41_ = _tmp40_->vals;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp42_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp41_);
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp43_ = _tmp42_;
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp36_ = _tmp43_ > 0;
#line 1547 "Collapse.c"
	} else {
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp36_ = FALSE;
#line 1551 "Collapse.c"
	}
#line 268 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	if (_tmp36_) {
#line 1555 "Collapse.c"
		GeeHashMap* _tmp44_ = NULL;
		const gchar* _tmp45_ = NULL;
		JSDOCTokenKeyMap* _tmp46_ = NULL;
#line 269 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp44_ = ret;
#line 269 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp45_ = k;
#line 269 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		_tmp46_ = g;
#line 269 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
		gee_abstract_map_set ((GeeAbstractMap*) _tmp44_, _tmp45_, _tmp46_);
#line 1567 "Collapse.c"
	}
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	result = ret;
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_free0 (k);
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	_g_object_unref0 (g);
#line 271 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	return result;
#line 1577 "Collapse.c"
}


static void jsdoc_collapse_class_init (JSDOCCollapseClass * klass) {
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/Collapse.vala"
	jsdoc_collapse_parent_class = g_type_class_peek_parent (klass);
#line 1584 "Collapse.c"
}


static void jsdoc_collapse_instance_init (JSDOCCollapse * self) {
}


GType jsdoc_collapse_get_type (void) {
	static volatile gsize jsdoc_collapse_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_collapse_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCCollapseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_collapse_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCCollapse), 0, (GInstanceInitFunc) jsdoc_collapse_instance_init, NULL };
		GType jsdoc_collapse_type_id;
		jsdoc_collapse_type_id = g_type_register_static (JSDOC_TYPE_TOKEN_STREAM, "JSDOCCollapse", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_collapse_type_id__volatile, jsdoc_collapse_type_id);
	}
	return jsdoc_collapse_type_id__volatile;
}



