/* Lang.c generated by valac 0.28.1, the Vala compiler
 * generated from Lang.vala, do not modify */

/*<script type="text/javscript">*/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define JSDOC_TYPE_LANGCLASS (jsdoc_langclass_get_type ())
#define JSDOC_LANGCLASS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_LANGCLASS, JSDOCLang_Class))
#define JSDOC_LANGCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_LANGCLASS, JSDOCLang_ClassClass))
#define JSDOC_IS_LANGCLASS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_LANGCLASS))
#define JSDOC_IS_LANGCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_LANGCLASS))
#define JSDOC_LANGCLASS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_LANGCLASS, JSDOCLang_ClassClass))

typedef struct _JSDOCLang_Class JSDOCLang_Class;
typedef struct _JSDOCLang_ClassClass JSDOCLang_ClassClass;
typedef struct _JSDOCLang_ClassPrivate JSDOCLang_ClassPrivate;
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _JSDOCLang_Class {
	GObject parent_instance;
	JSDOCLang_ClassPrivate * priv;
	GeeArrayList* match_strings;
};

struct _JSDOCLang_ClassClass {
	GObjectClass parent_class;
};

struct _JSDOCLang_ClassPrivate {
	GList* coreObjects;
	GeeHashMap* whitespaceNames;
	GeeHashMap* newlineNames;
	GeeHashMap* keywordNames;
	GeeHashMap* puncNames;
	GeeHashMap* matchingNames;
};


extern JSDOCLang_Class* jsdoc_Lang;
JSDOCLang_Class* jsdoc_Lang = NULL;
static gpointer jsdoc_langclass_parent_class = NULL;

GType jsdoc_langclass_get_type (void) G_GNUC_CONST;
#define JSDOC_LANGCLASS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JSDOC_TYPE_LANGCLASS, JSDOCLang_ClassPrivate))
enum  {
	JSDOC_LANGCLASS_DUMMY_PROPERTY
};
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
JSDOCLang_Class* jsdoc_langclass_new (void);
JSDOCLang_Class* jsdoc_langclass_construct (GType object_type);
static void jsdoc_langclass_init (JSDOCLang_Class* self);
gboolean jsdoc_langclass_isBuiltin (JSDOCLang_Class* self, const gchar* name);
gchar* jsdoc_langclass_whitespace (JSDOCLang_Class* self, const gchar* ch);
gchar* jsdoc_langclass_newline (JSDOCLang_Class* self, const gchar* ch);
gchar* jsdoc_langclass_keyword (JSDOCLang_Class* self, const gchar* word);
gchar* jsdoc_langclass_matching (JSDOCLang_Class* self, const gchar* name);
gboolean jsdoc_langclass_isKeyword (JSDOCLang_Class* self, const gchar* word);
gchar* jsdoc_langclass_punc (JSDOCLang_Class* self, const gchar* ch);
gboolean jsdoc_langclass_isNumber (JSDOCLang_Class* self, const gchar* str);
gboolean jsdoc_langclass_isHexDec (JSDOCLang_Class* self, const gchar* str);
gboolean jsdoc_langclass_isWordChar (JSDOCLang_Class* self, const gchar* str);
gboolean jsdoc_langclass_isSpace (JSDOCLang_Class* self, const gchar* str);
gboolean jsdoc_langclass_isSpaceC (JSDOCLang_Class* self, gchar str);
gboolean jsdoc_langclass_isNewline (JSDOCLang_Class* self, const gchar* str);
gboolean jsdoc_langclass_isNewlineC (JSDOCLang_Class* self, gchar str);
gboolean jsdoc_langclass_isBoolean (JSDOCLang_Class* self, const gchar* str);
static void jsdoc_langclass_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static void _g_free0_ (gpointer var) {
#line 23 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	var = (g_free (var), NULL);
#line 86 "Lang.c"
}


static void _g_list_free__g_free0_ (GList* self) {
#line 23 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
#line 23 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_list_free (self);
#line 95 "Lang.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return self ? g_object_ref (self) : NULL;
#line 102 "Lang.c"
}


JSDOCLang_Class* jsdoc_langclass_construct (GType object_type) {
	JSDOCLang_Class * self = NULL;
	JSDOCLang_Class* _tmp0_ = NULL;
	JSDOCLang_Class* _tmp1_ = NULL;
	JSDOCLang_Class* _tmp2_ = NULL;
#line 31 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self = (JSDOCLang_Class*) g_object_new (object_type, NULL);
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = jsdoc_Lang;
#line 33 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	if (_tmp0_ != NULL) {
#line 35 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		return self;
#line 119 "Lang.c"
	}
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	jsdoc_langclass_init (self);
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = _g_object_ref0 (self);
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (jsdoc_Lang);
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	jsdoc_Lang = _tmp1_;
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = jsdoc_Lang;
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_object_ref ((GObject*) _tmp2_);
#line 31 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return self;
#line 135 "Lang.c"
}


JSDOCLang_Class* jsdoc_langclass_new (void) {
#line 31 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return jsdoc_langclass_construct (JSDOC_TYPE_LANGCLASS);
#line 142 "Lang.c"
}


gboolean jsdoc_langclass_isBuiltin (JSDOCLang_Class* self, const gchar* name) {
	gboolean result = FALSE;
	GList* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (name != NULL, FALSE);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->coreObjects;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = name;
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = g_list_index (_tmp0_, _tmp1_);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp2_ > (-1);
#line 47 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 165 "Lang.c"
}


gchar* jsdoc_langclass_whitespace (JSDOCLang_Class* self, const gchar* ch) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 50 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (ch != NULL, NULL);
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->whitespaceNames;
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = ch;
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = (gchar*) _tmp2_;
#line 51 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 188 "Lang.c"
}


gchar* jsdoc_langclass_newline (JSDOCLang_Class* self, const gchar* ch) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (ch != NULL, NULL);
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->newlineNames;
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = ch;
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = (gchar*) _tmp2_;
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 211 "Lang.c"
}


gchar* jsdoc_langclass_keyword (JSDOCLang_Class* self, const gchar* word) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 56 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 56 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (word != NULL, NULL);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->keywordNames;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = word;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = g_strconcat ("=", _tmp1_, NULL);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = _tmp2_;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp3_);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp5_ = (gchar*) _tmp4_;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp3_);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp5_;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 245 "Lang.c"
}


gchar* jsdoc_langclass_matching (JSDOCLang_Class* self, const gchar* name) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label0 = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label1 = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label2 = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label3 = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label4 = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	static GQuark _tmp2_label5 = 0;
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = name;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = _tmp0_;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("LEFT_PAREN")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 280 "Lang.c"
			default:
			{
				gchar* _tmp4_ = NULL;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp4_ = g_strdup ("RIGHT_PAREN");
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp4_;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 290 "Lang.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("RIGHT_PAREN")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 296 "Lang.c"
			default:
			{
				gchar* _tmp5_ = NULL;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp5_ = g_strdup ("LEFT_PAREN");
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp5_;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 306 "Lang.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("LEFT_CURLY")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 312 "Lang.c"
			default:
			{
				gchar* _tmp6_ = NULL;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp6_ = g_strdup ("RIGHT_CURLY");
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp6_;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 322 "Lang.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("RIGHT_CURLY")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 328 "Lang.c"
			default:
			{
				gchar* _tmp7_ = NULL;
#line 67 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp7_ = g_strdup ("LEFT_CURLY");
#line 67 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp7_;
#line 67 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 338 "Lang.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string ("LEFT_BRACE")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 344 "Lang.c"
			default:
			{
				gchar* _tmp8_ = NULL;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp8_ = g_strdup ("RIGHT_BRACE");
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp8_;
#line 68 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 354 "Lang.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string ("RIGHT_BRACE")))) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 360 "Lang.c"
			default:
			{
				gchar* _tmp9_ = NULL;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp9_ = g_strdup ("LEFT_BRACE");
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = _tmp9_;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 370 "Lang.c"
			}
		}
	} else {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		switch (0) {
#line 376 "Lang.c"
			default:
			{
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				result = NULL;
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				return result;
#line 383 "Lang.c"
			}
		}
	}
}


gboolean jsdoc_langclass_isKeyword (JSDOCLang_Class* self, const gchar* word) {
	gboolean result = FALSE;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gpointer _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (word != NULL, FALSE);
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->keywordNames;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = word;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = g_strconcat ("=", _tmp1_, NULL);
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = _tmp2_;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp3_);
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp5_ = (gchar*) _tmp4_;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp6_ = _tmp5_ != NULL;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp5_);
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp3_);
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp6_;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 425 "Lang.c"
}


gchar* jsdoc_langclass_punc (JSDOCLang_Class* self, const gchar* ch) {
	gchar* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (ch != NULL, NULL);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->puncNames;
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = ch;
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = (gchar*) _tmp2_;
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 448 "Lang.c"
}


gboolean jsdoc_langclass_isNumber (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_regex_match_simple ("^(\\.[0-9]|[0-9]+\\.|[0-9])[0-9]*([eE][+-][0-9]+)?$", _tmp0_, 0, 0);
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp1_;
#line 86 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 468 "Lang.c"
}


gboolean jsdoc_langclass_isHexDec (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 89 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_regex_match_simple ("^0x[0-9A-F]+$", _tmp0_, 0, 0);
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp1_;
#line 90 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 488 "Lang.c"
}


gboolean jsdoc_langclass_isWordChar (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_regex_match_simple ("^[a-zA-Z0-9$_.]+$", _tmp0_, 0, 0);
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp1_;
#line 94 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 508 "Lang.c"
}


gboolean jsdoc_langclass_isSpace (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 97 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->whitespaceNames;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = str;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = (gchar*) _tmp2_;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = _tmp3_ != NULL;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp3_);
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp4_;
#line 98 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 539 "Lang.c"
}


gboolean jsdoc_langclass_isSpaceC (JSDOCLang_Class* self, gchar str) {
	gboolean result = FALSE;
	gchar* s = NULL;
	gchar _tmp0_ = '\0';
	gchar* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
#line 100 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_strdup_printf ("%c", _tmp0_);
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	s = _tmp1_;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = self->priv->whitespaceNames;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, s);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = (gchar*) _tmp3_;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp5_ = _tmp4_ != NULL;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp4_);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp5_;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (s);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 576 "Lang.c"
}


gboolean jsdoc_langclass_isNewline (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = self->priv->newlineNames;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = str;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = (gchar*) _tmp2_;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = _tmp3_ != NULL;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp3_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp4_;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 607 "Lang.c"
}


gboolean jsdoc_langclass_isNewlineC (JSDOCLang_Class* self, gchar str) {
	gboolean result = FALSE;
	gchar* s = NULL;
	gchar _tmp0_ = '\0';
	gchar* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
#line 108 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_strdup_printf ("%c", _tmp0_);
#line 109 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	s = _tmp1_;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = self->priv->newlineNames;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, s);
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = (gchar*) _tmp3_;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp5_ = _tmp4_ != NULL;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (_tmp4_);
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp5_;
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (s);
#line 110 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 644 "Lang.c"
}


gboolean jsdoc_langclass_isBoolean (JSDOCLang_Class* self, const gchar* str) {
	gboolean result = FALSE;
	gchar* ss = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_ = NULL;
#line 112 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 112 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_val_if_fail (str != NULL, FALSE);
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = str;
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = g_utf8_strdown (_tmp0_, (gssize) (-1));
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ss = _tmp1_;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = ss;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	if (g_strcmp0 (_tmp3_, "false") == 0) {
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		_tmp2_ = TRUE;
#line 671 "Lang.c"
	} else {
		const gchar* _tmp4_ = NULL;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		_tmp4_ = ss;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		_tmp2_ = g_strcmp0 (_tmp4_, "true") == 0;
#line 678 "Lang.c"
	}
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	result = _tmp2_;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_free0 (ss);
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	return result;
#line 686 "Lang.c"
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 1197 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1197 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1197 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1197 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1198 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1198 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 709 "Lang.c"
		glong _tmp4_ = 0L;
#line 1199 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1199 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1199 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 717 "Lang.c"
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 1201 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1201 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1201 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1201 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		return result;
#line 729 "Lang.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
#line 1208 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 753 "Lang.c"
		glong _tmp2_ = 0L;
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 759 "Lang.c"
	} else {
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 763 "Lang.c"
	}
#line 1210 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp0_) {
#line 767 "Lang.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
#line 1212 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp3_ = offset;
#line 1212 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp4_ = len;
#line 1212 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
#line 1212 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		string_length = _tmp5_;
#line 779 "Lang.c"
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 1214 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp6_ = strlen (self);
#line 1214 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp7_ = _tmp6_;
#line 1214 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp7_;
#line 789 "Lang.c"
	}
#line 1217 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp8_ = offset;
#line 1217 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp8_ < ((glong) 0)) {
#line 795 "Lang.c"
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1218 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp9_ = string_length;
#line 1218 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp10_ = offset;
#line 1218 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		offset = _tmp9_ + _tmp10_;
#line 1219 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1219 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
#line 809 "Lang.c"
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
#line 1221 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1221 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp13_ = string_length;
#line 1221 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
#line 819 "Lang.c"
	}
#line 1223 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp14_ = len;
#line 1223 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	if (_tmp14_ < ((glong) 0)) {
#line 825 "Lang.c"
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
#line 1224 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1224 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		_tmp16_ = offset;
#line 1224 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
		len = _tmp15_ - _tmp16_;
#line 834 "Lang.c"
	}
#line 1226 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp17_ = offset;
#line 1226 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp18_ = len;
#line 1226 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp19_ = string_length;
#line 1226 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
#line 1227 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp20_ = offset;
#line 1227 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp21_ = len;
#line 1227 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
#line 1227 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	result = _tmp22_;
#line 1227 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	return result;
#line 854 "Lang.c"
}


static void jsdoc_langclass_init (JSDOCLang_Class* self) {
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GeeHashMap* _tmp3_ = NULL;
	GeeHashMap* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	gchar** co = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar** _tmp17_ = NULL;
	gint co_length1 = 0;
	gint _co_size_ = 0;
	gchar** ws = NULL;
	gchar* _tmp30_ = NULL;
	gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar** _tmp33_ = NULL;
	gint ws_length1 = 0;
	gint _ws_size_ = 0;
	gchar* _tmp48_ = NULL;
	gchar* _tmp49_ = NULL;
	gchar** _tmp50_ = NULL;
	gchar* _tmp65_ = NULL;
	gchar* _tmp66_ = NULL;
	gchar* _tmp67_ = NULL;
	gchar* _tmp68_ = NULL;
	gchar* _tmp69_ = NULL;
	gchar* _tmp70_ = NULL;
	gchar* _tmp71_ = NULL;
	gchar* _tmp72_ = NULL;
	gchar* _tmp73_ = NULL;
	gchar* _tmp74_ = NULL;
	gchar* _tmp75_ = NULL;
	gchar* _tmp76_ = NULL;
	gchar* _tmp77_ = NULL;
	gchar* _tmp78_ = NULL;
	gchar* _tmp79_ = NULL;
	gchar* _tmp80_ = NULL;
	gchar* _tmp81_ = NULL;
	gchar* _tmp82_ = NULL;
	gchar* _tmp83_ = NULL;
	gchar* _tmp84_ = NULL;
	gchar* _tmp85_ = NULL;
	gchar* _tmp86_ = NULL;
	gchar* _tmp87_ = NULL;
	gchar* _tmp88_ = NULL;
	gchar* _tmp89_ = NULL;
	gchar* _tmp90_ = NULL;
	gchar* _tmp91_ = NULL;
	gchar* _tmp92_ = NULL;
	gchar* _tmp93_ = NULL;
	gchar** _tmp94_ = NULL;
	gchar* _tmp114_ = NULL;
	gchar* _tmp115_ = NULL;
	gchar* _tmp116_ = NULL;
	gchar* _tmp117_ = NULL;
	gchar* _tmp118_ = NULL;
	gchar* _tmp119_ = NULL;
	gchar* _tmp120_ = NULL;
	gchar* _tmp121_ = NULL;
	gchar* _tmp122_ = NULL;
	gchar* _tmp123_ = NULL;
	gchar* _tmp124_ = NULL;
	gchar* _tmp125_ = NULL;
	gchar* _tmp126_ = NULL;
	gchar* _tmp127_ = NULL;
	gchar* _tmp128_ = NULL;
	gchar* _tmp129_ = NULL;
	gchar* _tmp130_ = NULL;
	gchar* _tmp131_ = NULL;
	gchar* _tmp132_ = NULL;
	gchar* _tmp133_ = NULL;
	gchar* _tmp134_ = NULL;
	gchar* _tmp135_ = NULL;
	gchar* _tmp136_ = NULL;
	gchar* _tmp137_ = NULL;
	gchar* _tmp138_ = NULL;
	gchar* _tmp139_ = NULL;
	gchar* _tmp140_ = NULL;
	gchar* _tmp141_ = NULL;
	gchar* _tmp142_ = NULL;
	gchar* _tmp143_ = NULL;
	gchar* _tmp144_ = NULL;
	gchar* _tmp145_ = NULL;
	gchar* _tmp146_ = NULL;
	gchar* _tmp147_ = NULL;
	gchar* _tmp148_ = NULL;
	gchar* _tmp149_ = NULL;
	gchar* _tmp150_ = NULL;
	gchar** _tmp151_ = NULL;
	gchar** wsp = NULL;
	gchar* _tmp166_ = NULL;
	gchar* _tmp167_ = NULL;
	gchar* _tmp168_ = NULL;
	gchar* _tmp169_ = NULL;
	gchar* _tmp170_ = NULL;
	gchar* _tmp171_ = NULL;
	gchar** _tmp172_ = NULL;
	gint wsp_length1 = 0;
	gint _wsp_size_ = 0;
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_return_if_fail (self != NULL);
#line 121 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	__g_list_free__g_free0_0 (self->priv->coreObjects);
#line 121 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->coreObjects = NULL;
#line 123 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 123 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->whitespaceNames);
#line 123 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->whitespaceNames = _tmp0_;
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->newlineNames);
#line 124 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->newlineNames = _tmp1_;
#line 125 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp2_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 125 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->keywordNames);
#line 125 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->keywordNames = _tmp2_;
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp3_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->puncNames);
#line 126 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->puncNames = _tmp3_;
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp4_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->matchingNames);
#line 127 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv->matchingNames = _tmp4_;
#line 128 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp5_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL);
#line 128 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->match_strings);
#line 128 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->match_strings = _tmp5_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp6_ = g_strdup ("_global_");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp7_ = g_strdup ("Array");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp8_ = g_strdup ("Boolean");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp9_ = g_strdup ("Date");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp10_ = g_strdup ("Error");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp11_ = g_strdup ("Function");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp12_ = g_strdup ("Math");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp13_ = g_strdup ("Number");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp14_ = g_strdup ("Object");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp15_ = g_strdup ("RegExp");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp16_ = g_strdup ("String");
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_ = g_new0 (gchar*, 11 + 1);
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[0] = _tmp6_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[1] = _tmp7_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[2] = _tmp8_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[3] = _tmp9_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[4] = _tmp10_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[5] = _tmp11_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[6] = _tmp12_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[7] = _tmp13_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[8] = _tmp14_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[9] = _tmp15_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp17_[10] = _tmp16_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	co = _tmp17_;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	co_length1 = 11;
#line 131 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_co_size_ = co_length1;
#line 1062 "Lang.c"
	{
		gint i = 0;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1067 "Lang.c"
		{
			gboolean _tmp18_ = FALSE;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp18_ = TRUE;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1074 "Lang.c"
				gint _tmp20_ = 0;
				gchar** _tmp21_ = NULL;
				gint _tmp21__length1 = 0;
				gchar** _tmp22_ = NULL;
				gint _tmp22__length1 = 0;
				gint _tmp23_ = 0;
				const gchar* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				GeeArrayList* _tmp26_ = NULL;
				gchar** _tmp27_ = NULL;
				gint _tmp27__length1 = 0;
				gint _tmp28_ = 0;
				const gchar* _tmp29_ = NULL;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp18_) {
#line 1090 "Lang.c"
					gint _tmp19_ = 0;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp19_ = i;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp19_ + 1;
#line 1096 "Lang.c"
				}
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp18_ = FALSE;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp20_ = i;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp21_ = co;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp21__length1 = co_length1;
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp20_ < _tmp21__length1)) {
#line 133 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1110 "Lang.c"
				}
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp22_ = co;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp22__length1 = co_length1;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp23_ = i;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp24_ = _tmp22_[_tmp23_];
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp25_ = g_strdup (_tmp24_);
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				self->priv->coreObjects = g_list_append (self->priv->coreObjects, _tmp25_);
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp26_ = self->match_strings;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp27_ = co;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp27__length1 = co_length1;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp28_ = i;
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp29_ = _tmp27_[_tmp28_];
#line 135 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp26_, _tmp29_);
#line 1136 "Lang.c"
			}
		}
	}
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp30_ = g_strdup (" :SPACE");
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp31_ = g_strdup ("\f:FORMFEED");
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp32_ = g_strdup ("\t:TAB");
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp33_ = g_new0 (gchar*, 3 + 1);
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp33_[0] = _tmp30_;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp33_[1] = _tmp31_;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp33_[2] = _tmp32_;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = _tmp33_;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws_length1 = 3;
#line 137 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_ws_size_ = ws_length1;
#line 1160 "Lang.c"
	{
		gint i = 0;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1165 "Lang.c"
		{
			gboolean _tmp34_ = FALSE;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp34_ = TRUE;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1172 "Lang.c"
				gint _tmp36_ = 0;
				gchar** _tmp37_ = NULL;
				gint _tmp37__length1 = 0;
				gchar** x = NULL;
				gchar** _tmp38_ = NULL;
				gint _tmp38__length1 = 0;
				gint _tmp39_ = 0;
				const gchar* _tmp40_ = NULL;
				gchar** _tmp41_ = NULL;
				gchar** _tmp42_ = NULL;
				gint x_length1 = 0;
				gint _x_size_ = 0;
				GeeHashMap* _tmp43_ = NULL;
				gchar** _tmp44_ = NULL;
				gint _tmp44__length1 = 0;
				const gchar* _tmp45_ = NULL;
				gchar** _tmp46_ = NULL;
				gint _tmp46__length1 = 0;
				const gchar* _tmp47_ = NULL;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp34_) {
#line 1194 "Lang.c"
					gint _tmp35_ = 0;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp35_ = i;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp35_ + 1;
#line 1200 "Lang.c"
				}
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp34_ = FALSE;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp36_ = i;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp37_ = ws;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp37__length1 = ws_length1;
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp36_ < _tmp37__length1)) {
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1214 "Lang.c"
				}
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp38_ = ws;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp38__length1 = ws_length1;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp39_ = i;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp40_ = _tmp38_[_tmp39_];
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp42_ = _tmp41_ = g_strsplit (_tmp40_, ":", 0);
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = _tmp42_;
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x_length1 = _vala_array_length (_tmp41_);
#line 146 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_x_size_ = x_length1;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp43_ = self->priv->whitespaceNames;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp44_ = x;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp44__length1 = x_length1;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp45_ = _tmp44_[0];
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp46_ = x;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp46__length1 = x_length1;
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp47_ = _tmp46_[1];
#line 147 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_map_set ((GeeAbstractMap*) _tmp43_, _tmp45_, _tmp47_);
#line 145 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = (_vala_array_free (x, x_length1, (GDestroyNotify) g_free), NULL);
#line 1250 "Lang.c"
			}
		}
	}
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp48_ = g_strdup ("\n:NEWLINE");
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp49_ = g_strdup ("\r:RETURN");
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp50_ = g_new0 (gchar*, 2 + 1);
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp50_[0] = _tmp48_;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp50_[1] = _tmp49_;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = (_vala_array_free (ws, ws_length1, (GDestroyNotify) g_free), NULL);
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = _tmp50_;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws_length1 = 2;
#line 150 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_ws_size_ = ws_length1;
#line 1272 "Lang.c"
	{
		gint i = 0;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1277 "Lang.c"
		{
			gboolean _tmp51_ = FALSE;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp51_ = TRUE;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1284 "Lang.c"
				gint _tmp53_ = 0;
				gchar** _tmp54_ = NULL;
				gint _tmp54__length1 = 0;
				gchar** x = NULL;
				gchar** _tmp55_ = NULL;
				gint _tmp55__length1 = 0;
				gint _tmp56_ = 0;
				const gchar* _tmp57_ = NULL;
				gchar** _tmp58_ = NULL;
				gchar** _tmp59_ = NULL;
				gint x_length1 = 0;
				gint _x_size_ = 0;
				GeeHashMap* _tmp60_ = NULL;
				gchar** _tmp61_ = NULL;
				gint _tmp61__length1 = 0;
				const gchar* _tmp62_ = NULL;
				gchar** _tmp63_ = NULL;
				gint _tmp63__length1 = 0;
				const gchar* _tmp64_ = NULL;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp51_) {
#line 1306 "Lang.c"
					gint _tmp52_ = 0;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp52_ = i;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp52_ + 1;
#line 1312 "Lang.c"
				}
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp51_ = FALSE;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp53_ = i;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp54_ = ws;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp54__length1 = ws_length1;
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp53_ < _tmp54__length1)) {
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1326 "Lang.c"
				}
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp55_ = ws;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp55__length1 = ws_length1;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp56_ = i;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp57_ = _tmp55_[_tmp56_];
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp59_ = _tmp58_ = g_strsplit (_tmp57_, ":", 0);
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = _tmp59_;
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x_length1 = _vala_array_length (_tmp58_);
#line 159 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_x_size_ = x_length1;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp60_ = self->priv->newlineNames;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp61_ = x;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp61__length1 = x_length1;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp62_ = _tmp61_[0];
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp63_ = x;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp63__length1 = x_length1;
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp64_ = _tmp63_[1];
#line 160 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_map_set ((GeeAbstractMap*) _tmp60_, _tmp62_, _tmp64_);
#line 158 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = (_vala_array_free (x, x_length1, (GDestroyNotify) g_free), NULL);
#line 1362 "Lang.c"
			}
		}
	}
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp65_ = g_strdup ("=break:BREAK");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp66_ = g_strdup ("=case:CASE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp67_ = g_strdup ("=catch:CATCH");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp68_ = g_strdup ("=const:VAR");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp69_ = g_strdup ("=continue:CONTINUE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp70_ = g_strdup ("=default:DEFAULT");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp71_ = g_strdup ("=delete:DELETE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp72_ = g_strdup ("=do:DO");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp73_ = g_strdup ("=else:ELSE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp74_ = g_strdup ("=false:FALSE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp75_ = g_strdup ("=finally:FINALLY");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp76_ = g_strdup ("=for:FOR");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp77_ = g_strdup ("=function:FUNCTION");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp78_ = g_strdup ("=if:IF");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp79_ = g_strdup ("=in:IN");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp80_ = g_strdup ("=instanceof:INSTANCEOF");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp81_ = g_strdup ("=new:NEW");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp82_ = g_strdup ("=null:NULL");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp83_ = g_strdup ("=return:RETURN");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp84_ = g_strdup ("=switch:SWITCH");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp85_ = g_strdup ("=this:THIS");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp86_ = g_strdup ("=throw:THROW");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp87_ = g_strdup ("=true:TRUE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp88_ = g_strdup ("=try:TRY");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp89_ = g_strdup ("=typeof:TYPEOF");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp90_ = g_strdup ("=void:VOID");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp91_ = g_strdup ("=while:WHILE");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp92_ = g_strdup ("=with:WITH");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp93_ = g_strdup ("=var:VAR");
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_ = g_new0 (gchar*, 29 + 1);
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[0] = _tmp65_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[1] = _tmp66_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[2] = _tmp67_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[3] = _tmp68_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[4] = _tmp69_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[5] = _tmp70_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[6] = _tmp71_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[7] = _tmp72_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[8] = _tmp73_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[9] = _tmp74_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[10] = _tmp75_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[11] = _tmp76_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[12] = _tmp77_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[13] = _tmp78_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[14] = _tmp79_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[15] = _tmp80_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[16] = _tmp81_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[17] = _tmp82_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[18] = _tmp83_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[19] = _tmp84_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[20] = _tmp85_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[21] = _tmp86_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[22] = _tmp87_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[23] = _tmp88_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[24] = _tmp89_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[25] = _tmp90_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[26] = _tmp91_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[27] = _tmp92_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp94_[28] = _tmp93_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = (_vala_array_free (ws, ws_length1, (GDestroyNotify) g_free), NULL);
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = _tmp94_;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws_length1 = 29;
#line 162 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_ws_size_ = ws_length1;
#line 1492 "Lang.c"
	{
		gint i = 0;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1497 "Lang.c"
		{
			gboolean _tmp95_ = FALSE;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp95_ = TRUE;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1504 "Lang.c"
				gint _tmp97_ = 0;
				gchar** _tmp98_ = NULL;
				gint _tmp98__length1 = 0;
				gchar** x = NULL;
				gchar** _tmp99_ = NULL;
				gint _tmp99__length1 = 0;
				gint _tmp100_ = 0;
				const gchar* _tmp101_ = NULL;
				gchar** _tmp102_ = NULL;
				gchar** _tmp103_ = NULL;
				gint x_length1 = 0;
				gint _x_size_ = 0;
				GeeHashMap* _tmp104_ = NULL;
				gchar** _tmp105_ = NULL;
				gint _tmp105__length1 = 0;
				const gchar* _tmp106_ = NULL;
				gchar** _tmp107_ = NULL;
				gint _tmp107__length1 = 0;
				const gchar* _tmp108_ = NULL;
				GeeArrayList* _tmp109_ = NULL;
				gchar** _tmp110_ = NULL;
				gint _tmp110__length1 = 0;
				const gchar* _tmp111_ = NULL;
				gchar* _tmp112_ = NULL;
				gchar* _tmp113_ = NULL;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp95_) {
#line 1532 "Lang.c"
					gint _tmp96_ = 0;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp96_ = i;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp96_ + 1;
#line 1538 "Lang.c"
				}
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp95_ = FALSE;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp97_ = i;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp98_ = ws;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp98__length1 = ws_length1;
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp97_ < _tmp98__length1)) {
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1552 "Lang.c"
				}
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp99_ = ws;
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp99__length1 = ws_length1;
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp100_ = i;
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp101_ = _tmp99_[_tmp100_];
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp103_ = _tmp102_ = g_strsplit (_tmp101_, ":", 0);
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = _tmp103_;
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x_length1 = _vala_array_length (_tmp102_);
#line 194 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_x_size_ = x_length1;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp104_ = self->priv->keywordNames;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp105_ = x;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp105__length1 = x_length1;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp106_ = _tmp105_[0];
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp107_ = x;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp107__length1 = x_length1;
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp108_ = _tmp107_[1];
#line 195 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_map_set ((GeeAbstractMap*) _tmp104_, _tmp106_, _tmp108_);
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp109_ = self->match_strings;
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp110_ = x;
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp110__length1 = x_length1;
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp111_ = _tmp110_[0];
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp112_ = string_substring (_tmp111_, (glong) 1, (glong) (-1));
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp113_ = _tmp112_;
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp109_, _tmp113_);
#line 196 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_g_free0 (_tmp113_);
#line 193 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = (_vala_array_free (x, x_length1, (GDestroyNotify) g_free), NULL);
#line 1604 "Lang.c"
			}
		}
	}
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp114_ = g_strdup ("; SEMICOLON");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp115_ = g_strdup (", COMMA");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp116_ = g_strdup ("? HOOK");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp117_ = g_strdup (": COLON");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp118_ = g_strdup ("|| OR");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp119_ = g_strdup ("&& AND");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp120_ = g_strdup ("| BITWISE_OR");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp121_ = g_strdup ("^ BITWISE_XOR");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp122_ = g_strdup ("& BITWISE_AND");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp123_ = g_strdup ("=== STRICT_EQ");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp124_ = g_strdup ("== EQ");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp125_ = g_strdup ("= ASSIGN");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp126_ = g_strdup ("!== STRICT_NE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp127_ = g_strdup ("!= NE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp128_ = g_strdup ("<< LSH");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp129_ = g_strdup ("<= LE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp130_ = g_strdup ("< LT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp131_ = g_strdup (">>> URSH");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp132_ = g_strdup (">> RSH");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp133_ = g_strdup (">= GE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp134_ = g_strdup ("> GT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp135_ = g_strdup ("++ INCREMENT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp136_ = g_strdup ("-- DECREMENT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp137_ = g_strdup ("+ PLUS");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp138_ = g_strdup ("- MINUS");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp139_ = g_strdup ("* MUL");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp140_ = g_strdup ("/ DIV");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp141_ = g_strdup ("% MOD");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp142_ = g_strdup ("! NOT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp143_ = g_strdup ("~ BITWISE_NOT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp144_ = g_strdup (". DOT");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp145_ = g_strdup ("[ LEFT_BRACE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp146_ = g_strdup ("] RIGHT_BRACE");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp147_ = g_strdup ("{ LEFT_CURLY");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp148_ = g_strdup ("} RIGHT_CURLY");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp149_ = g_strdup ("( LEFT_PAREN");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp150_ = g_strdup (") RIGHT_PAREN");
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_ = g_new0 (gchar*, 37 + 1);
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[0] = _tmp114_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[1] = _tmp115_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[2] = _tmp116_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[3] = _tmp117_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[4] = _tmp118_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[5] = _tmp119_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[6] = _tmp120_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[7] = _tmp121_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[8] = _tmp122_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[9] = _tmp123_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[10] = _tmp124_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[11] = _tmp125_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[12] = _tmp126_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[13] = _tmp127_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[14] = _tmp128_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[15] = _tmp129_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[16] = _tmp130_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[17] = _tmp131_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[18] = _tmp132_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[19] = _tmp133_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[20] = _tmp134_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[21] = _tmp135_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[22] = _tmp136_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[23] = _tmp137_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[24] = _tmp138_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[25] = _tmp139_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[26] = _tmp140_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[27] = _tmp141_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[28] = _tmp142_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[29] = _tmp143_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[30] = _tmp144_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[31] = _tmp145_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[32] = _tmp146_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[33] = _tmp147_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[34] = _tmp148_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[35] = _tmp149_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp151_[36] = _tmp150_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = (_vala_array_free (ws, ws_length1, (GDestroyNotify) g_free), NULL);
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = _tmp151_;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws_length1 = 37;
#line 200 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_ws_size_ = ws_length1;
#line 1766 "Lang.c"
	{
		gint i = 0;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1771 "Lang.c"
		{
			gboolean _tmp152_ = FALSE;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp152_ = TRUE;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1778 "Lang.c"
				gint _tmp154_ = 0;
				gchar** _tmp155_ = NULL;
				gint _tmp155__length1 = 0;
				gchar** x = NULL;
				gchar** _tmp156_ = NULL;
				gint _tmp156__length1 = 0;
				gint _tmp157_ = 0;
				const gchar* _tmp158_ = NULL;
				gchar** _tmp159_ = NULL;
				gchar** _tmp160_ = NULL;
				gint x_length1 = 0;
				gint _x_size_ = 0;
				GeeHashMap* _tmp161_ = NULL;
				gchar** _tmp162_ = NULL;
				gint _tmp162__length1 = 0;
				const gchar* _tmp163_ = NULL;
				gchar** _tmp164_ = NULL;
				gint _tmp164__length1 = 0;
				const gchar* _tmp165_ = NULL;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp152_) {
#line 1800 "Lang.c"
					gint _tmp153_ = 0;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp153_ = i;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp153_ + 1;
#line 1806 "Lang.c"
				}
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp152_ = FALSE;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp154_ = i;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp155_ = ws;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp155__length1 = ws_length1;
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp154_ < _tmp155__length1)) {
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1820 "Lang.c"
				}
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp156_ = ws;
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp156__length1 = ws_length1;
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp157_ = i;
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp158_ = _tmp156_[_tmp157_];
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp160_ = _tmp159_ = g_strsplit (_tmp158_, " ", 0);
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = _tmp160_;
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x_length1 = _vala_array_length (_tmp159_);
#line 240 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_x_size_ = x_length1;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp161_ = self->priv->puncNames;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp162_ = x;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp162__length1 = x_length1;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp163_ = _tmp162_[0];
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp164_ = x;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp164__length1 = x_length1;
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp165_ = _tmp164_[1];
#line 241 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_map_set ((GeeAbstractMap*) _tmp161_, _tmp163_, _tmp165_);
#line 239 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = (_vala_array_free (x, x_length1, (GDestroyNotify) g_free), NULL);
#line 1856 "Lang.c"
			}
		}
	}
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp166_ = g_strdup ("LEFT_PAREN:RIGHT_PAREN");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp167_ = g_strdup ("RIGHT_PAREN:LEFT_PAREN");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp168_ = g_strdup ("LEFT_CURLY:RIGHT_CURLY");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp169_ = g_strdup ("RIGHT_CURLY:LEFT_CURLY");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp170_ = g_strdup ("LEFT_BRACE:RIGHT_BRACE");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp171_ = g_strdup ("RIGHT_BRACE:LEFT_BRACE");
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_ = g_new0 (gchar*, 6 + 1);
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[0] = _tmp166_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[1] = _tmp167_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[2] = _tmp168_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[3] = _tmp169_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[4] = _tmp170_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_tmp172_[5] = _tmp171_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	wsp = _tmp172_;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	wsp_length1 = 6;
#line 244 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_wsp_size_ = wsp_length1;
#line 1892 "Lang.c"
	{
		gint i = 0;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
		i = 0;
#line 1897 "Lang.c"
		{
			gboolean _tmp173_ = FALSE;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			_tmp173_ = TRUE;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
			while (TRUE) {
#line 1904 "Lang.c"
				gint _tmp175_ = 0;
				gchar** _tmp176_ = NULL;
				gint _tmp176__length1 = 0;
				gchar** x = NULL;
				gchar** _tmp177_ = NULL;
				gint _tmp177__length1 = 0;
				gint _tmp178_ = 0;
				const gchar* _tmp179_ = NULL;
				gchar** _tmp180_ = NULL;
				gchar** _tmp181_ = NULL;
				gint x_length1 = 0;
				gint _x_size_ = 0;
				GeeHashMap* _tmp182_ = NULL;
				gchar** _tmp183_ = NULL;
				gint _tmp183__length1 = 0;
				const gchar* _tmp184_ = NULL;
				gchar** _tmp185_ = NULL;
				gint _tmp185__length1 = 0;
				const gchar* _tmp186_ = NULL;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!_tmp173_) {
#line 1926 "Lang.c"
					gint _tmp174_ = 0;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					_tmp174_ = i;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					i = _tmp174_ + 1;
#line 1932 "Lang.c"
				}
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp173_ = FALSE;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp175_ = i;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp176_ = wsp;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp176__length1 = wsp_length1;
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				if (!(_tmp175_ < _tmp176__length1)) {
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
					break;
#line 1946 "Lang.c"
				}
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp177_ = wsp;
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp177__length1 = wsp_length1;
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp178_ = i;
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp179_ = _tmp177_[_tmp178_];
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp181_ = _tmp180_ = g_strsplit (_tmp179_, ":", 0);
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = _tmp181_;
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x_length1 = _vala_array_length (_tmp180_);
#line 253 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_x_size_ = x_length1;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp182_ = self->priv->matchingNames;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp183_ = x;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp183__length1 = x_length1;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp184_ = _tmp183_[0];
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp185_ = x;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp185__length1 = x_length1;
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				_tmp186_ = _tmp185_[1];
#line 254 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				gee_abstract_map_set ((GeeAbstractMap*) _tmp182_, _tmp184_, _tmp186_);
#line 252 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
				x = (_vala_array_free (x, x_length1, (GDestroyNotify) g_free), NULL);
#line 1982 "Lang.c"
			}
		}
	}
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	wsp = (_vala_array_free (wsp, wsp_length1, (GDestroyNotify) g_free), NULL);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	ws = (_vala_array_free (ws, ws_length1, (GDestroyNotify) g_free), NULL);
#line 119 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	co = (_vala_array_free (co, co_length1, (GDestroyNotify) g_free), NULL);
#line 1992 "Lang.c"
}


static void jsdoc_langclass_class_init (JSDOCLang_ClassClass * klass) {
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	jsdoc_langclass_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	g_type_class_add_private (klass, sizeof (JSDOCLang_ClassPrivate));
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_langclass_finalize;
#line 2003 "Lang.c"
}


static void jsdoc_langclass_instance_init (JSDOCLang_Class * self) {
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self->priv = JSDOC_LANGCLASS_GET_PRIVATE (self);
#line 2010 "Lang.c"
}


static void jsdoc_langclass_finalize (GObject* obj) {
	JSDOCLang_Class * self;
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_LANGCLASS, JSDOCLang_Class);
#line 23 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	__g_list_free__g_free0_0 (self->priv->coreObjects);
#line 24 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->whitespaceNames);
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->newlineNames);
#line 26 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->keywordNames);
#line 27 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->puncNames);
#line 28 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->priv->matchingNames);
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	_g_object_unref0 (self->match_strings);
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/Lang.vala"
	G_OBJECT_CLASS (jsdoc_langclass_parent_class)->finalize (obj);
#line 2034 "Lang.c"
}


GType jsdoc_langclass_get_type (void) {
	static volatile gsize jsdoc_langclass_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_langclass_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCLang_ClassClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_langclass_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCLang_Class), 0, (GInstanceInitFunc) jsdoc_langclass_instance_init, NULL };
		GType jsdoc_langclass_type_id;
		jsdoc_langclass_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCLang_Class", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_langclass_type_id__volatile, jsdoc_langclass_type_id);
	}
	return jsdoc_langclass_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



