/* TextStream.c generated by valac 0.28.1, the Vala compiler
 * generated from TextStream.vala, do not modify */

/*<script type="text/javscript">*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define JSDOC_TYPE_TEXT_STREAM_CHAR (jsdoc_text_stream_char_get_type ())
#define JSDOC_TEXT_STREAM_CHAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TEXT_STREAM_CHAR, JSDOCTextStreamChar))
#define JSDOC_TEXT_STREAM_CHAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TEXT_STREAM_CHAR, JSDOCTextStreamCharClass))
#define JSDOC_IS_TEXT_STREAM_CHAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TEXT_STREAM_CHAR))
#define JSDOC_IS_TEXT_STREAM_CHAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TEXT_STREAM_CHAR))
#define JSDOC_TEXT_STREAM_CHAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TEXT_STREAM_CHAR, JSDOCTextStreamCharClass))

typedef struct _JSDOCTextStreamChar JSDOCTextStreamChar;
typedef struct _JSDOCTextStreamCharClass JSDOCTextStreamCharClass;
typedef struct _JSDOCTextStreamCharPrivate JSDOCTextStreamCharPrivate;

#define JSDOC_TYPE_TEXT_STREAM (jsdoc_text_stream_get_type ())
#define JSDOC_TEXT_STREAM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TEXT_STREAM, JSDOCTextStream))
#define JSDOC_TEXT_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TEXT_STREAM, JSDOCTextStreamClass))
#define JSDOC_IS_TEXT_STREAM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TEXT_STREAM))
#define JSDOC_IS_TEXT_STREAM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TEXT_STREAM))
#define JSDOC_TEXT_STREAM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TEXT_STREAM, JSDOCTextStreamClass))

typedef struct _JSDOCTextStream JSDOCTextStream;
typedef struct _JSDOCTextStreamClass JSDOCTextStreamClass;
typedef struct _JSDOCTextStreamPrivate JSDOCTextStreamPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _JSDOCTextStreamChar {
	GObject parent_instance;
	JSDOCTextStreamCharPrivate * priv;
	gchar c;
	gboolean eof;
};

struct _JSDOCTextStreamCharClass {
	GObjectClass parent_class;
};

struct _JSDOCTextStream {
	GObject parent_instance;
	JSDOCTextStreamPrivate * priv;
};

struct _JSDOCTextStreamClass {
	GObjectClass parent_class;
};

struct _JSDOCTextStreamPrivate {
	gchar* text;
	gint cursor;
	gint length;
};


static gpointer jsdoc_text_stream_char_parent_class = NULL;
static gpointer jsdoc_text_stream_parent_class = NULL;

GType jsdoc_text_stream_char_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_TEXT_STREAM_CHAR_DUMMY_PROPERTY
};
JSDOCTextStreamChar* jsdoc_text_stream_char_new (gchar val, gboolean eof);
JSDOCTextStreamChar* jsdoc_text_stream_char_construct (GType object_type, gchar val, gboolean eof);
static void jsdoc_text_stream_char_finalize (GObject* obj);
GType jsdoc_text_stream_get_type (void) G_GNUC_CONST;
#define JSDOC_TEXT_STREAM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JSDOC_TYPE_TEXT_STREAM, JSDOCTextStreamPrivate))
enum  {
	JSDOC_TEXT_STREAM_DUMMY_PROPERTY
};
JSDOCTextStream* jsdoc_text_stream_new (const gchar* text);
JSDOCTextStream* jsdoc_text_stream_construct (GType object_type, const gchar* text);
gchar jsdoc_text_stream_look (JSDOCTextStream* self, gint n);
gboolean jsdoc_text_stream_lookEOF (JSDOCTextStream* self, gint n);
gchar* jsdoc_text_stream_next (JSDOCTextStream* self, gint n);
static void jsdoc_text_stream_finalize (GObject* obj);


JSDOCTextStreamChar* jsdoc_text_stream_char_construct (GType object_type, gchar val, gboolean eof) {
	JSDOCTextStreamChar * self = NULL;
	gchar _tmp0_ = '\0';
	gboolean _tmp1_ = FALSE;
#line 13 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self = (JSDOCTextStreamChar*) g_object_new (object_type, NULL);
#line 14 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp0_ = val;
#line 14 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->c = _tmp0_;
#line 15 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp1_ = eof;
#line 15 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->eof = _tmp1_;
#line 13 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return self;
#line 102 "TextStream.c"
}


JSDOCTextStreamChar* jsdoc_text_stream_char_new (gchar val, gboolean eof) {
#line 13 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return jsdoc_text_stream_char_construct (JSDOC_TYPE_TEXT_STREAM_CHAR, val, eof);
#line 109 "TextStream.c"
}


static void jsdoc_text_stream_char_class_init (JSDOCTextStreamCharClass * klass) {
#line 10 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	jsdoc_text_stream_char_parent_class = g_type_class_peek_parent (klass);
#line 10 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_text_stream_char_finalize;
#line 118 "TextStream.c"
}


static void jsdoc_text_stream_char_instance_init (JSDOCTextStreamChar * self) {
}


static void jsdoc_text_stream_char_finalize (GObject* obj) {
	JSDOCTextStreamChar * self;
#line 10 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_TEXT_STREAM_CHAR, JSDOCTextStreamChar);
#line 10 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	G_OBJECT_CLASS (jsdoc_text_stream_char_parent_class)->finalize (obj);
#line 132 "TextStream.c"
}


GType jsdoc_text_stream_char_get_type (void) {
	static volatile gsize jsdoc_text_stream_char_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_text_stream_char_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCTextStreamCharClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_text_stream_char_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCTextStreamChar), 0, (GInstanceInitFunc) jsdoc_text_stream_char_instance_init, NULL };
		GType jsdoc_text_stream_char_type_id;
		jsdoc_text_stream_char_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCTextStreamChar", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_text_stream_char_type_id__volatile, jsdoc_text_stream_char_type_id);
	}
	return jsdoc_text_stream_char_type_id__volatile;
}


JSDOCTextStream* jsdoc_text_stream_construct (GType object_type, const gchar* text) {
	JSDOCTextStream * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	g_return_val_if_fail (text != NULL, NULL);
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self = (JSDOCTextStream*) g_object_new (object_type, NULL);
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp0_ = text;
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_g_free0 (self->priv->text);
#line 29 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->priv->text = _tmp1_;
#line 30 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp2_ = text;
#line 30 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp3_ = strlen (_tmp2_);
#line 30 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp4_ = _tmp3_;
#line 30 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->priv->length = _tmp4_;
#line 31 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->priv->cursor = 0;
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return self;
#line 179 "TextStream.c"
}


JSDOCTextStream* jsdoc_text_stream_new (const gchar* text) {
#line 25 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return jsdoc_text_stream_construct (JSDOC_TYPE_TEXT_STREAM, text);
#line 186 "TextStream.c"
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
#line 996 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, '\0');
#line 997 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp0_ = index;
#line 997 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	_tmp1_ = ((gchar*) self)[_tmp0_];
#line 997 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	result = _tmp1_;
#line 997 "/usr/share/vala-0.28/vapi/glib-2.0.vapi"
	return result;
#line 204 "TextStream.c"
}


gchar jsdoc_text_stream_look (JSDOCTextStream* self, gint n) {
	gchar result = '\0';
	gboolean _tmp0_ = FALSE;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	const gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gchar _tmp9_ = '\0';
#line 34 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	g_return_val_if_fail (self != NULL, '\0');
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp1_ = self->priv->cursor;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp2_ = n;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	if ((_tmp1_ + _tmp2_) < 0) {
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp0_ = TRUE;
#line 227 "TextStream.c"
	} else {
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp3_ = self->priv->cursor;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp4_ = n;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp5_ = self->priv->length;
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp0_ = (_tmp3_ + _tmp4_) >= _tmp5_;
#line 240 "TextStream.c"
	}
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	if (_tmp0_) {
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		result = '\0';
#line 38 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		return result;
#line 248 "TextStream.c"
	}
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp6_ = self->priv->text;
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp7_ = self->priv->cursor;
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp8_ = n;
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp9_ = string_get (_tmp6_, (glong) (_tmp7_ + _tmp8_));
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	result = _tmp9_;
#line 40 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return result;
#line 262 "TextStream.c"
}


gboolean jsdoc_text_stream_lookEOF (JSDOCTextStream* self, gint n) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 43 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp1_ = self->priv->cursor;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp2_ = n;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	if ((_tmp1_ + _tmp2_) < 0) {
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp0_ = TRUE;
#line 281 "TextStream.c"
	} else {
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp3_ = self->priv->cursor;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp4_ = n;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp5_ = self->priv->length;
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp0_ = (_tmp3_ + _tmp4_) >= _tmp5_;
#line 294 "TextStream.c"
	}
#line 45 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	if (_tmp0_) {
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		result = TRUE;
#line 46 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		return result;
#line 302 "TextStream.c"
	}
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	result = FALSE;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return result;
#line 308 "TextStream.c"
}


/**
         * @param n - number of characters to return..
         */
gchar* jsdoc_text_stream_next (JSDOCTextStream* self, gint n) {
	gchar* result = NULL;
	gint _tmp0_ = 0;
	gchar* pulled = NULL;
	gchar* _tmp2_ = NULL;
	gint i = 0;
	gint _tmp19_ = 0;
	const gchar* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp0_ = n;
#line 57 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	if (_tmp0_ < 1) {
#line 331 "TextStream.c"
		gchar* _tmp1_ = NULL;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp1_ = g_strdup ("\0");
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		result = _tmp1_;
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		return result;
#line 339 "TextStream.c"
	}
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp2_ = g_strdup ("");
#line 61 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	pulled = _tmp2_;
#line 62 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	i = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	while (TRUE) {
#line 349 "TextStream.c"
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp3_ = i;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp4_ = n;
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		if (!(_tmp3_ < _tmp4_)) {
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			break;
#line 363 "TextStream.c"
		}
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp5_ = self->priv->cursor;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp6_ = i;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		_tmp7_ = self->priv->length;
#line 64 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
		if ((_tmp5_ + _tmp6_) < _tmp7_) {
#line 373 "TextStream.c"
			gchar add = '\0';
			const gchar* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			gchar _tmp11_ = '\0';
			const gchar* _tmp12_ = NULL;
			gchar _tmp13_ = '\0';
			gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
			gint _tmp17_ = 0;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp8_ = self->priv->text;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp9_ = self->priv->cursor;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp10_ = i;
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp11_ = string_get (_tmp8_, (glong) (_tmp9_ + _tmp10_));
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			add = _tmp11_;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp12_ = pulled;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp13_ = add;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp14_ = g_strdup_printf ("%c", _tmp13_);
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp15_ = _tmp14_;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp16_ = g_strconcat (_tmp12_, _tmp15_, NULL);
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_g_free0 (pulled);
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			pulled = _tmp16_;
#line 66 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_g_free0 (_tmp15_);
#line 67 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp17_ = i;
#line 67 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			i = _tmp17_ + 1;
#line 415 "TextStream.c"
		} else {
			gchar* _tmp18_ = NULL;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_tmp18_ = g_strdup ("");
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			result = _tmp18_;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			_g_free0 (pulled);
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
			return result;
#line 426 "TextStream.c"
		}
	}
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp19_ = self->priv->cursor;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp20_ = pulled;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp21_ = strlen (_tmp20_);
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_tmp22_ = _tmp21_;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->priv->cursor = _tmp19_ + _tmp22_;
#line 75 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	result = pulled;
#line 75 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	return result;
#line 443 "TextStream.c"
}


static void jsdoc_text_stream_class_init (JSDOCTextStreamClass * klass) {
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	jsdoc_text_stream_parent_class = g_type_class_peek_parent (klass);
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	g_type_class_add_private (klass, sizeof (JSDOCTextStreamPrivate));
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_text_stream_finalize;
#line 454 "TextStream.c"
}


static void jsdoc_text_stream_instance_init (JSDOCTextStream * self) {
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self->priv = JSDOC_TEXT_STREAM_GET_PRIVATE (self);
#line 461 "TextStream.c"
}


static void jsdoc_text_stream_finalize (GObject* obj) {
	JSDOCTextStream * self;
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_TEXT_STREAM, JSDOCTextStream);
#line 21 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	_g_free0 (self->priv->text);
#line 19 "/home/alan/gitlive/roojspacker/src/jsdoc/TextStream.vala"
	G_OBJECT_CLASS (jsdoc_text_stream_parent_class)->finalize (obj);
#line 473 "TextStream.c"
}


GType jsdoc_text_stream_get_type (void) {
	static volatile gsize jsdoc_text_stream_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_text_stream_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCTextStreamClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_text_stream_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCTextStream), 0, (GInstanceInitFunc) jsdoc_text_stream_instance_init, NULL };
		GType jsdoc_text_stream_type_id;
		jsdoc_text_stream_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCTextStream", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_text_stream_type_id__volatile, jsdoc_text_stream_type_id);
	}
	return jsdoc_text_stream_type_id__volatile;
}



