/* Token.c generated by valac 0.28.1, the Vala compiler
 * generated from Token.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define JSDOC_TYPE_TOKEN_KEY_MAP (jsdoc_token_key_map_get_type ())
#define JSDOC_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMap))
#define JSDOC_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))
#define JSDOC_IS_TOKEN_KEY_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_IS_TOKEN_KEY_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN_KEY_MAP))
#define JSDOC_TOKEN_KEY_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMapClass))

typedef struct _JSDOCTokenKeyMap JSDOCTokenKeyMap;
typedef struct _JSDOCTokenKeyMapClass JSDOCTokenKeyMapClass;
typedef struct _JSDOCTokenKeyMapPrivate JSDOCTokenKeyMapPrivate;

#define JSDOC_TYPE_TOKEN (jsdoc_token_get_type ())
#define JSDOC_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_TOKEN, JSDOCToken))
#define JSDOC_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_TOKEN, JSDOCTokenClass))
#define JSDOC_IS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_TOKEN))
#define JSDOC_IS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_TOKEN))
#define JSDOC_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_TOKEN, JSDOCTokenClass))

typedef struct _JSDOCToken JSDOCToken;
typedef struct _JSDOCTokenClass JSDOCTokenClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _JSDOCTokenPrivate JSDOCTokenPrivate;

#define JSDOC_TYPE_IDENTIFIER (jsdoc_identifier_get_type ())
#define JSDOC_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifier))
#define JSDOC_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))
#define JSDOC_IS_IDENTIFIER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IS_IDENTIFIER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JSDOC_TYPE_IDENTIFIER))
#define JSDOC_IDENTIFIER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JSDOC_TYPE_IDENTIFIER, JSDOCIdentifierClass))

typedef struct _JSDOCIdentifier JSDOCIdentifier;
typedef struct _JSDOCIdentifierClass JSDOCIdentifierClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _JSDOCTokenKeyMap {
	GObject parent_instance;
	JSDOCTokenKeyMapPrivate * priv;
	JSDOCToken* key;
	GeeArrayList* vals;
};

struct _JSDOCTokenKeyMapClass {
	GObjectClass parent_class;
};

struct _JSDOCToken {
	GObject parent_instance;
	JSDOCTokenPrivate * priv;
	gint id;
	gchar* data;
	gchar* type;
	gchar* name;
	gint line;
	gchar* prefix;
	gchar* outData;
	JSDOCIdentifier* identifier;
	GeeArrayList* items;
	GeeHashMap* props;
};

struct _JSDOCTokenClass {
	GObjectClass parent_class;
};


extern gint jsdoc_Token_id;
gint jsdoc_Token_id = 1;
static gpointer jsdoc_token_key_map_parent_class = NULL;
static gpointer jsdoc_token_parent_class = NULL;

GType jsdoc_token_key_map_get_type (void) G_GNUC_CONST;
GType jsdoc_token_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_TOKEN_KEY_MAP_DUMMY_PROPERTY
};
JSDOCTokenKeyMap* jsdoc_token_key_map_new (void);
JSDOCTokenKeyMap* jsdoc_token_key_map_construct (GType object_type);
JSDOCToken* jsdoc_token_new (const gchar* data, const gchar* type, const gchar* name, gint line);
JSDOCToken* jsdoc_token_construct (GType object_type, const gchar* data, const gchar* type, const gchar* name, gint line);
static void jsdoc_token_key_map_finalize (GObject* obj);
GType jsdoc_identifier_get_type (void) G_GNUC_CONST;
enum  {
	JSDOC_TOKEN_DUMMY_PROPERTY
};
gchar* jsdoc_token_asString (JSDOCToken* self);
void jsdoc_token_dump (JSDOCToken* self, const gchar* indent);
gchar* jsdoc_token_toRaw (JSDOCToken* self, gint lvl);
gboolean jsdoc_token_is (JSDOCToken* self, const gchar* what);
static void jsdoc_token_finalize (GObject* obj);


JSDOCTokenKeyMap* jsdoc_token_key_map_construct (GType object_type) {
	JSDOCTokenKeyMap * self = NULL;
	JSDOCToken* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
#line 39 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self = (JSDOCTokenKeyMap*) g_object_new (object_type, NULL);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp0_ = jsdoc_token_new ("", "VOID", "VOID", -1);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->key);
#line 41 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->key = _tmp0_;
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = gee_array_list_new (JSDOC_TYPE_TOKEN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->vals);
#line 42 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->vals = _tmp1_;
#line 39 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return self;
#line 124 "Token.c"
}


JSDOCTokenKeyMap* jsdoc_token_key_map_new (void) {
#line 39 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return jsdoc_token_key_map_construct (JSDOC_TYPE_TOKEN_KEY_MAP);
#line 131 "Token.c"
}


static void jsdoc_token_key_map_class_init (JSDOCTokenKeyMapClass * klass) {
#line 35 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	jsdoc_token_key_map_parent_class = g_type_class_peek_parent (klass);
#line 35 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_token_key_map_finalize;
#line 140 "Token.c"
}


static void jsdoc_token_key_map_instance_init (JSDOCTokenKeyMap * self) {
}


static void jsdoc_token_key_map_finalize (GObject* obj) {
	JSDOCTokenKeyMap * self;
#line 35 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_TOKEN_KEY_MAP, JSDOCTokenKeyMap);
#line 36 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->key);
#line 37 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->vals);
#line 35 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	G_OBJECT_CLASS (jsdoc_token_key_map_parent_class)->finalize (obj);
#line 158 "Token.c"
}


GType jsdoc_token_key_map_get_type (void) {
	static volatile gsize jsdoc_token_key_map_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_token_key_map_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCTokenKeyMapClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_token_key_map_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCTokenKeyMap), 0, (GInstanceInitFunc) jsdoc_token_key_map_instance_init, NULL };
		GType jsdoc_token_key_map_type_id;
		jsdoc_token_key_map_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCTokenKeyMap", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_token_key_map_type_id__volatile, jsdoc_token_key_map_type_id);
	}
	return jsdoc_token_key_map_type_id__volatile;
}


JSDOCToken* jsdoc_token_construct (GType object_type, const gchar* data, const gchar* type, const gchar* name, gint line) {
	JSDOCToken * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GeeArrayList* _tmp10_ = NULL;
	GeeHashMap* _tmp11_ = NULL;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (data != NULL, NULL);
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (type != NULL, NULL);
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self = (JSDOCToken*) g_object_new (object_type, NULL);
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp0_ = data;
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->data);
#line 71 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->data = _tmp1_;
#line 72 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp2_ = type;
#line 72 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 72 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->type);
#line 72 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->type = _tmp3_;
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp4_ = name;
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->name);
#line 73 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->name = _tmp5_;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp6_ = line;
#line 74 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->line = _tmp6_;
#line 75 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp7_ = g_strdup ("");
#line 75 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->prefix);
#line 75 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->prefix = _tmp7_;
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp8_ = g_strdup ("");
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->outData);
#line 76 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->outData = _tmp8_;
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->identifier);
#line 77 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->identifier = NULL;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp9_ = jsdoc_Token_id;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	jsdoc_Token_id = _tmp9_ + 1;
#line 78 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->id = _tmp9_;
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp10_ = gee_array_list_new (GEE_TYPE_ARRAY_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->items);
#line 81 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->items = _tmp10_;
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp11_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, JSDOC_TYPE_TOKEN_KEY_MAP, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->props);
#line 82 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self->props = _tmp11_;
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return self;
#line 260 "Token.c"
}


JSDOCToken* jsdoc_token_new (const gchar* data, const gchar* type, const gchar* name, gint line) {
#line 69 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return jsdoc_token_construct (JSDOC_TYPE_TOKEN, data, type, name, line);
#line 267 "Token.c"
}


gchar* jsdoc_token_asString (JSDOCToken* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
#line 85 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = self->outData;
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	if (_tmp1_ == NULL) {
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp0_ = "";
#line 289 "Token.c"
	} else {
		const gchar* _tmp2_ = NULL;
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp2_ = self->outData;
#line 93 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp0_ = _tmp2_;
#line 296 "Token.c"
	}
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp3_ = self->line;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp4_ = self->id;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp5_ = self->type;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp6_ = self->data;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp7_ = self->name;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp8_ = g_strdup_printf ("line:%d, id %d, type %s, data : %s,  name %s, , outData: %s", _tmp3_, _tmp4_, _tmp5_, _tmp6_, _tmp7_, _tmp0_);
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	result = _tmp8_;
#line 87 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return result;
#line 314 "Token.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return self ? g_object_ref (self) : NULL;
#line 321 "Token.c"
}


void jsdoc_token_dump (JSDOCToken* self, const gchar* indent) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GeeArrayList* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	GeeHashMap* _tmp34_ = NULL;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
#line 99 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_if_fail (self != NULL);
#line 99 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_if_fail (indent != NULL);
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp0_ = indent;
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = jsdoc_token_asString (self);
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp2_ = _tmp1_;
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_print ("%s%s\n", _tmp0_, _tmp2_);
#line 101 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (_tmp2_);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp3_ = self->items;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp5_ = _tmp4_;
#line 102 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	if (_tmp5_ > 0) {
#line 357 "Token.c"
		{
			gint i = 0;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			i = 0;
#line 362 "Token.c"
			{
				gboolean _tmp6_ = FALSE;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
				_tmp6_ = TRUE;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
				while (TRUE) {
#line 369 "Token.c"
					gint _tmp8_ = 0;
					GeeArrayList* _tmp9_ = NULL;
					gint _tmp10_ = 0;
					gint _tmp11_ = 0;
					const gchar* _tmp12_ = NULL;
					gint _tmp13_ = 0;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					if (!_tmp6_) {
#line 378 "Token.c"
						gint _tmp7_ = 0;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp7_ = i;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						i = _tmp7_ + 1;
#line 384 "Token.c"
					}
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp6_ = FALSE;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp8_ = i;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp9_ = self->items;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp10_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp9_);
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp11_ = _tmp10_;
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					if (!(_tmp8_ < _tmp11_)) {
#line 104 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						break;
#line 400 "Token.c"
					}
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp12_ = indent;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp13_ = i;
#line 105 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					g_print ("%s --ITEMS[%d] [ \n", _tmp12_, _tmp13_);
#line 408 "Token.c"
					{
						gint j = 0;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						j = 0;
#line 413 "Token.c"
						{
							gboolean _tmp14_ = FALSE;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
							_tmp14_ = TRUE;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
							while (TRUE) {
#line 420 "Token.c"
								gint _tmp16_ = 0;
								GeeArrayList* _tmp17_ = NULL;
								gint _tmp18_ = 0;
								gpointer _tmp19_ = NULL;
								GeeArrayList* _tmp20_ = NULL;
								gint _tmp21_ = 0;
								gint _tmp22_ = 0;
								gboolean _tmp23_ = FALSE;
								GeeArrayList* _tmp24_ = NULL;
								gint _tmp25_ = 0;
								gpointer _tmp26_ = NULL;
								GeeArrayList* _tmp27_ = NULL;
								gint _tmp28_ = 0;
								gpointer _tmp29_ = NULL;
								JSDOCToken* _tmp30_ = NULL;
								const gchar* _tmp31_ = NULL;
								gchar* _tmp32_ = NULL;
								gchar* _tmp33_ = NULL;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								if (!_tmp14_) {
#line 441 "Token.c"
									gint _tmp15_ = 0;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
									_tmp15_ = j;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
									j = _tmp15_ + 1;
#line 447 "Token.c"
								}
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp14_ = FALSE;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp16_ = j;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp17_ = self->items;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp18_ = i;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp19_ = gee_abstract_list_get ((GeeAbstractList*) _tmp17_, _tmp18_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp20_ = (GeeArrayList*) _tmp19_;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp21_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp20_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp22_ = _tmp21_;
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp23_ = !(_tmp16_ < _tmp22_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_g_object_unref0 (_tmp20_);
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								if (_tmp23_) {
#line 106 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
									break;
#line 473 "Token.c"
								}
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp24_ = self->items;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp25_ = i;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp26_ = gee_abstract_list_get ((GeeAbstractList*) _tmp24_, _tmp25_);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp27_ = (GeeArrayList*) _tmp26_;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp28_ = j;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp29_ = gee_abstract_list_get ((GeeAbstractList*) _tmp27_, _tmp28_);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp30_ = (JSDOCToken*) _tmp29_;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp31_ = indent;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp32_ = g_strconcat (_tmp31_, "  ", NULL);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_tmp33_ = _tmp32_;
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								jsdoc_token_dump (_tmp30_, _tmp33_);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_g_free0 (_tmp33_);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_g_object_unref0 (_tmp30_);
#line 107 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
								_g_object_unref0 (_tmp27_);
#line 503 "Token.c"
							}
						}
					}
				}
			}
		}
	}
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp34_ = self->props;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp35_ = gee_abstract_map_get_size ((GeeMap*) _tmp34_);
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp36_ = _tmp35_;
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	if (_tmp36_ > 0) {
#line 519 "Token.c"
		GeeMapIterator* m = NULL;
		GeeHashMap* _tmp37_ = NULL;
		GeeMapIterator* _tmp38_ = NULL;
#line 112 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp37_ = self->props;
#line 112 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp38_ = gee_abstract_map_map_iterator ((GeeAbstractMap*) _tmp37_);
#line 112 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		m = _tmp38_;
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		while (TRUE) {
#line 531 "Token.c"
			GeeMapIterator* _tmp39_ = NULL;
			gboolean _tmp40_ = FALSE;
			const gchar* _tmp41_ = NULL;
			GeeMapIterator* _tmp42_ = NULL;
			gpointer _tmp43_ = NULL;
			gchar* _tmp44_ = NULL;
			GeeArrayList* vals = NULL;
			GeeMapIterator* _tmp45_ = NULL;
			gpointer _tmp46_ = NULL;
			JSDOCTokenKeyMap* _tmp47_ = NULL;
			GeeArrayList* _tmp48_ = NULL;
			GeeArrayList* _tmp49_ = NULL;
			GeeArrayList* _tmp50_ = NULL;
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp39_ = m;
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp40_ = gee_map_iterator_next (_tmp39_);
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			if (!_tmp40_) {
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
				break;
#line 553 "Token.c"
			}
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp41_ = indent;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp42_ = m;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp43_ = gee_map_iterator_get_key (_tmp42_);
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp44_ = (gchar*) _tmp43_;
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			g_print ("%s --KEY %s ::  \n", _tmp41_, _tmp44_);
#line 114 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_free0 (_tmp44_);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp45_ = m;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp46_ = gee_map_iterator_get_value (_tmp45_);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp47_ = (JSDOCTokenKeyMap*) _tmp46_;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp48_ = _tmp47_->vals;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp49_ = _g_object_ref0 (_tmp48_);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp50_ = _tmp49_;
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_object_unref0 (_tmp47_);
#line 115 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			vals = _tmp50_;
#line 583 "Token.c"
			{
				gint i = 0;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
				i = 0;
#line 588 "Token.c"
				{
					gboolean _tmp51_ = FALSE;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					_tmp51_ = TRUE;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
					while (TRUE) {
#line 595 "Token.c"
						gint _tmp53_ = 0;
						GeeArrayList* _tmp54_ = NULL;
						gint _tmp55_ = 0;
						gint _tmp56_ = 0;
						GeeArrayList* _tmp57_ = NULL;
						gint _tmp58_ = 0;
						gpointer _tmp59_ = NULL;
						JSDOCToken* _tmp60_ = NULL;
						const gchar* _tmp61_ = NULL;
						gchar* _tmp62_ = NULL;
						gchar* _tmp63_ = NULL;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						if (!_tmp51_) {
#line 609 "Token.c"
							gint _tmp52_ = 0;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
							_tmp52_ = i;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
							i = _tmp52_ + 1;
#line 615 "Token.c"
						}
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp51_ = FALSE;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp53_ = i;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp54_ = vals;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp55_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp54_);
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp56_ = _tmp55_;
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						if (!(_tmp53_ < _tmp56_)) {
#line 116 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
							break;
#line 631 "Token.c"
						}
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp57_ = vals;
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp58_ = i;
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp59_ = gee_abstract_list_get ((GeeAbstractList*) _tmp57_, _tmp58_);
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp60_ = (JSDOCToken*) _tmp59_;
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp61_ = indent;
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp62_ = g_strconcat (_tmp61_, "  ", NULL);
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_tmp63_ = _tmp62_;
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						jsdoc_token_dump (_tmp60_, _tmp63_);
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_g_free0 (_tmp63_);
#line 118 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
						_g_object_unref0 (_tmp60_);
#line 653 "Token.c"
					}
				}
			}
#line 113 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_object_unref0 (vals);
#line 659 "Token.c"
		}
#line 111 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_g_object_unref0 (m);
#line 663 "Token.c"
	}
}


gchar* jsdoc_token_toRaw (JSDOCToken* self, gint lvl) {
	gchar* result = NULL;
	gchar* ret = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
#line 128 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 132 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp0_ = self->data;
#line 132 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 132 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	ret = _tmp1_;
#line 684 "Token.c"
	{
		GeeArrayList* _ai_list = NULL;
		GeeArrayList* _tmp2_ = NULL;
		GeeArrayList* _tmp3_ = NULL;
		gint _ai_size = 0;
		GeeArrayList* _tmp4_ = NULL;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _ai_index = 0;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp2_ = self->items;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp3_ = _g_object_ref0 (_tmp2_);
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_ai_list = _tmp3_;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp4_ = _ai_list;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp5_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp4_);
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp6_ = _tmp5_;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_ai_size = _tmp6_;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_ai_index = -1;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		while (TRUE) {
#line 712 "Token.c"
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			gint _tmp9_ = 0;
			GeeArrayList* ai = NULL;
			GeeArrayList* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gpointer _tmp12_ = NULL;
			gchar* str = NULL;
			gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
			gchar* _tmp16_ = NULL;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp7_ = _ai_index;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_ai_index = _tmp7_ + 1;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp8_ = _ai_index;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp9_ = _ai_size;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			if (!(_tmp8_ < _tmp9_)) {
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
				break;
#line 737 "Token.c"
			}
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp10_ = _ai_list;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp11_ = _ai_index;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp12_ = gee_abstract_list_get ((GeeAbstractList*) _tmp10_, _tmp11_);
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			ai = (GeeArrayList*) _tmp12_;
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp13_ = g_strdup ("");
#line 136 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			str = _tmp13_;
#line 140 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp14_ = ret;
#line 140 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp15_ = str;
#line 140 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_tmp16_ = g_strconcat (_tmp14_, _tmp15_, NULL);
#line 140 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_free0 (ret);
#line 140 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			ret = _tmp16_;
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_free0 (str);
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
			_g_object_unref0 (ai);
#line 765 "Token.c"
		}
#line 134 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_g_object_unref0 (_ai_list);
#line 769 "Token.c"
	}
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp17_ = self->prefix;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp18_ = ret;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp19_ = g_strconcat (_tmp17_, _tmp18_, NULL);
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	result = _tmp19_;
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (ret);
#line 156 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return result;
#line 783 "Token.c"
}


gboolean jsdoc_token_is (JSDOCToken* self, const gchar* what) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
#line 173 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 173 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	g_return_val_if_fail (what != NULL, FALSE);
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp1_ = self->name;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_tmp2_ = what;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	if (g_strcmp0 (_tmp1_, _tmp2_) == 0) {
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp0_ = TRUE;
#line 804 "Token.c"
	} else {
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp3_ = self->type;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp4_ = what;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
		_tmp0_ = g_strcmp0 (_tmp3_, _tmp4_) == 0;
#line 814 "Token.c"
	}
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	result = _tmp0_;
#line 174 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	return result;
#line 820 "Token.c"
}


static void jsdoc_token_class_init (JSDOCTokenClass * klass) {
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	jsdoc_token_parent_class = g_type_class_peek_parent (klass);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	G_OBJECT_CLASS (klass)->finalize = jsdoc_token_finalize;
#line 829 "Token.c"
}


static void jsdoc_token_instance_init (JSDOCToken * self) {
}


static void jsdoc_token_finalize (GObject* obj) {
	JSDOCToken * self;
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, JSDOC_TYPE_TOKEN, JSDOCToken);
#line 52 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->data);
#line 53 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->type);
#line 54 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->name);
#line 56 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->prefix);
#line 58 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_free0 (self->outData);
#line 60 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->identifier);
#line 63 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->items);
#line 65 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	_g_object_unref0 (self->props);
#line 48 "/home/alan/gitlive/roojspacker/src/jsdoc/Token.vala"
	G_OBJECT_CLASS (jsdoc_token_parent_class)->finalize (obj);
#line 859 "Token.c"
}


GType jsdoc_token_get_type (void) {
	static volatile gsize jsdoc_token_type_id__volatile = 0;
	if (g_once_init_enter (&jsdoc_token_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JSDOCTokenClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) jsdoc_token_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JSDOCToken), 0, (GInstanceInitFunc) jsdoc_token_instance_init, NULL };
		GType jsdoc_token_type_id;
		jsdoc_token_type_id = g_type_register_static (G_TYPE_OBJECT, "JSDOCToken", &g_define_type_info, 0);
		g_once_init_leave (&jsdoc_token_type_id__volatile, jsdoc_token_type_id);
	}
	return jsdoc_token_type_id__volatile;
}



